//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@protocol EXP_HUBComponentImageDataJSONSchema
@property(retain, nonatomic) id <EXP_HUBJSONDictionaryPath> customDataPath;
@property(retain, nonatomic) id <EXP_HUBJSONStringPath> localImageNamePath;
@property(retain, nonatomic) id <EXP_HUBJSONStringPath> placeholderIconIdentifierPath;
@property(retain, nonatomic) id <EXP_HUBJSONURLPath> URLPath;
- (id <EXP_HUBComponentImageDataJSONSchema>)copy;
@end

