//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@class UIColor;

@interface FBAdInfoButton : UIButton
{
    UIColor *_activeColor;
    UIColor *_inactiveColor;
}

@property(copy, nonatomic) UIColor *inactiveColor; // @synthesize inactiveColor=_inactiveColor;
@property(copy, nonatomic) UIColor *activeColor; // @synthesize activeColor=_activeColor;
- (void).cxx_destruct;
- (void)setHighlighted:(_Bool)arg1;
- (void)drawRect:(struct CGRect)arg1;

@end

