//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface GCKAtomicCounter : NSObject
{
    long long *_value;
}

- (void)dealloc;
- (long long)nextValue;
- (id)initWithInitialValue:(long long)arg1;
- (id)init;

@end

