//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GCKCastChannel.h"

@class GCKDevice, NSArray, NSData;

@interface GCKDeviceAuthChannel : GCKCastChannel
{
    GCKDevice *_device;
    struct __SecTrust *_peerTrust;
    NSArray *_anchorCertArray;
    NSData *_nonce;
    id <GCKDeviceAuthChannelDelegate> _delegate;
}

@property(nonatomic) __weak id <GCKDeviceAuthChannelDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (_Bool)verifyDeviceSignature:(id)arg1 deviceKey:(struct __SecKey *)arg2 deviceDigest:(id)arg3;
- (void)didReceiveBinaryMessage:(id)arg1;
- (void)notifyAuthenticationFailure;
- (void)sendChallengeWithPeerSecTrust:(struct __SecTrust *)arg1;
- (void)dealloc;
- (id)initWithDevice:(id)arg1;

@end

