//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GCKPB_PBGeneratedMessage.h"

@class NSString;

@interface GCKPB_LOGS_MessageDetails_Type : GCKPB_PBGeneratedMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool hasLogType; // @dynamic hasLogType;
@property(nonatomic) _Bool hasSourceType; // @dynamic hasSourceType;
@property(retain, nonatomic) NSString *logType; // @dynamic logType;
@property(retain, nonatomic) NSString *sourceType; // @dynamic sourceType;

@end

