//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GCKCastChannel.h"

#import "GCKRequestTrackerDelegate.h"

@class GCKRequestTracker, NSMutableArray, NSString;

@interface GCKReceiverControlChannel : GCKCastChannel <GCKRequestTrackerDelegate>
{
    NSString *_receiverDestinationID;
    GCKRequestTracker *_launchRequestTracker;
    GCKRequestTracker *_stopRequestTracker;
    GCKRequestTracker *_statusRequestTracker;
    GCKRequestTracker *_volumeRequestTracker;
    GCKRequestTracker *_muteRequestTracker;
    GCKRequestTracker *_appAvailabilityRequestTracker;
    NSMutableArray *_requestTrackers;
    _Bool _awaitingFirstStatus;
    _Bool _lastKnownMute;
    _Bool _pendingMute;
    float _lastKnownVolumeLevel;
    float _pendingVolumeLevel;
    id <GCKReceiverControlChannelDelegate> _delegate;
}

@property(nonatomic) __weak id <GCKReceiverControlChannelDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)notifyRequestReplaced:(long long)arg1;
- (void)notifyRequestDidFailWithID:(long long)arg1 error:(id)arg2;
- (void)notifyDidFailToLaunchAppWithError:(id)arg1;
- (void)requestTracker:(id)arg1 didCancel:(long long)arg2;
- (void)requestTracker:(id)arg1 didTimeOut:(long long)arg2;
- (void)requestTracker:(id)arg1 didReplace:(long long)arg2;
- (void)didReceiveTextMessage:(id)arg1;
- (long long)setMuted:(_Bool)arg1;
- (long long)setVolume:(float)arg1;
- (long long)requestAvailabilityForAppIDs:(id)arg1;
- (long long)requestDeviceStatus;
- (long long)stopApplicationInternalWithSessionID:(id)arg1;
- (long long)stopApplicationWithSessionID:(id)arg1;
- (long long)stopApplication;
- (long long)launchApplication:(id)arg1 senderLanguageCode:(id)arg2;
- (_Bool)isLaunchingApplication;
- (void)didDisconnect;
- (void)cancelRequest:(long long)arg1;
- (id)initWithReceiverDestinationID:(id)arg1;
- (id)initWithNamespace:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

