//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "GLUEStyle.h"

@class GLUELabelStyle, NSString, UIColor;

@interface GLUETabBarItemViewStyle : NSObject <GLUEStyle>
{
    GLUELabelStyle *_normalLabelStyle;
    GLUELabelStyle *_selectedLabelStyle;
    UIColor *_topShadowColor;
    UIColor *_backgroundColor;
    double _minKerning;
    double _maxItemWidth;
    UIColor *_badgeColor;
    struct CGSize _iconSize;
    struct UIOffset _badgeImageOffset;
    struct CGSize _badgeImageSize;
    struct UIEdgeInsets _badgeImageInsets;
}

@property(copy, nonatomic) UIColor *badgeColor; // @synthesize badgeColor=_badgeColor;
@property(nonatomic) struct UIEdgeInsets badgeImageInsets; // @synthesize badgeImageInsets=_badgeImageInsets;
@property(nonatomic) struct CGSize badgeImageSize; // @synthesize badgeImageSize=_badgeImageSize;
@property(nonatomic) struct UIOffset badgeImageOffset; // @synthesize badgeImageOffset=_badgeImageOffset;
@property(nonatomic) double maxItemWidth; // @synthesize maxItemWidth=_maxItemWidth;
@property(nonatomic) double minKerning; // @synthesize minKerning=_minKerning;
@property(copy, nonatomic) UIColor *backgroundColor; // @synthesize backgroundColor=_backgroundColor;
@property(copy, nonatomic) UIColor *topShadowColor; // @synthesize topShadowColor=_topShadowColor;
@property(copy, nonatomic) GLUELabelStyle *selectedLabelStyle; // @synthesize selectedLabelStyle=_selectedLabelStyle;
@property(copy, nonatomic) GLUELabelStyle *normalLabelStyle; // @synthesize normalLabelStyle=_normalLabelStyle;
@property(nonatomic) struct CGSize iconSize; // @synthesize iconSize=_iconSize;
- (void).cxx_destruct;
- (double)maxItemWidthForSizeClass:(long long)arg1;
@property(readonly) unsigned long long hash;
- (_Bool)isEqualToTabBarItemStyle:(id)arg1;
- (_Bool)isEqual:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)iconTintColorForSelectedState:(_Bool)arg1;
- (id)labelStyleForSelectedState:(_Bool)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) Class superclass;

@end

