//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSData.h"

@interface NSData (Async)
+ (void)spt_dataWithContentsOfURL:(id)arg1 options:(unsigned long long)arg2 completion:(CDUnknownBlockType)arg3 completionQueue:(id)arg4;
+ (void)spt_dataWithContentsOfURL:(id)arg1 completion:(CDUnknownBlockType)arg2 completionQueue:(id)arg3;
@end

