//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSDictionary.h"

@class NSIndexPath;

@interface NSDictionary (DrivingChangeContextActionCustomData)
+ (id)changeContextActionCustomDataWithFromIndexPath:(id)arg1 toIndexPath:(id)arg2;
@property(readonly, nonatomic) _Bool shelfChanged;
@property(readonly, nonatomic) NSIndexPath *toIndexPath;
@property(readonly, nonatomic) NSIndexPath *fromIndexPath;
@end

