//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SettingsViewController.h"

#import "SPTAbbaFeatureFlagsObserver.h"
#import "SPTGaiaDeviceStateManagerObserver.h"
#import "SPTProductStateObserver.h"
#import "UITableViewDelegate.h"

@class NSArray, NSMutableArray, NSObject<SPTLoginStateController>, NSString, SPSession, SettingsErrorHeaderView;

@interface RootSettingsViewController : SettingsViewController <SPTGaiaDeviceStateManagerObserver, SPTProductStateObserver, SPTAbbaFeatureFlagsObserver, UITableViewDelegate>
{
    _Bool _isPlayingRemotely;
    _Bool _isAdsEnabled;
    SettingsErrorHeaderView *_errorHeaderView;
    NSObject<SPTLoginStateController> *_loginStateController;
    NSMutableArray *_settingsSectionsForConnectObserving;
    NSArray *_settingsSectionsForLocalPlayback;
    id <GaiaFeature> _gaia;
    long long _disabledSettingsIndex;
    id <SPTAbbaFeatureFlags> _featureFlags;
    SPSession *_session;
}

+ (id)rootSettingsViewControllerWithDictionaryRepresentation:(id)arg1 loginStateController:(id)arg2 gaia:(id)arg3 productState:(id)arg4 featureFlags:(id)arg5 session:(id)arg6 navigationItem:(id)arg7 navigationRouter:(id)arg8;
@property(nonatomic) __weak SPSession *session; // @synthesize session=_session;
@property(nonatomic) __weak id <SPTAbbaFeatureFlags> featureFlags; // @synthesize featureFlags=_featureFlags;
@property(nonatomic) _Bool isAdsEnabled; // @synthesize isAdsEnabled=_isAdsEnabled;
@property(nonatomic) long long disabledSettingsIndex; // @synthesize disabledSettingsIndex=_disabledSettingsIndex;
@property(nonatomic) _Bool isPlayingRemotely; // @synthesize isPlayingRemotely=_isPlayingRemotely;
@property(nonatomic) __weak id <GaiaFeature> gaia; // @synthesize gaia=_gaia;
@property(retain, nonatomic) NSArray *settingsSectionsForLocalPlayback; // @synthesize settingsSectionsForLocalPlayback=_settingsSectionsForLocalPlayback;
@property(retain, nonatomic) NSMutableArray *settingsSectionsForConnectObserving; // @synthesize settingsSectionsForConnectObserving=_settingsSectionsForConnectObserving;
@property(nonatomic) __weak NSObject<SPTLoginStateController> *loginStateController; // @synthesize loginStateController=_loginStateController;
@property(retain, nonatomic) SettingsErrorHeaderView *errorHeaderView; // @synthesize errorHeaderView=_errorHeaderView;
- (void).cxx_destruct;
- (void)popAdsViewController;
- (_Bool)shouldShowSponsoredContentRow;
- (_Bool)shouldShowAdsRow;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (_Bool)isSponsoredContentRow:(id)arg1;
- (_Bool)isAdsRow:(id)arg1;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (void)rebuildSettingsSections;
- (void)viewWillAppear:(_Bool)arg1;
- (void)lastConnectionErrorChanged;
- (void)viewDidLoad;
- (void)featureFlagsDidChange:(id)arg1;
- (void)productState:(id)arg1 stateDidChange:(id)arg2;
- (void)deviceStateManager:(id)arg1 activeDeviceDidChange:(id)arg2;
- (id)initWithDictionaryRepresentation:(id)arg1 loginStateController:(id)arg2 gaia:(id)arg3 productState:(id)arg4 featureFlags:(id)arg5 session:(id)arg6 navigationItem:(id)arg7 navigationRouter:(id)arg8;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

