//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SPTAccelerometerFilter.h"

@class NSString;

@interface SPTBandpassFilter : NSObject <SPTAccelerometerFilter>
{
    float *xvx;
    float *yvx;
    float *xvy;
    float *yvy;
    float *xvz;
    float *yvz;
    float x;
    float y;
    float z;
    float amplification;
}

@property(nonatomic) float amplification; // @synthesize amplification;
@property(readonly, nonatomic) float z; // @synthesize z;
@property(readonly, nonatomic) float y; // @synthesize y;
@property(readonly, nonatomic) float x; // @synthesize x;
- (void)dealloc;
- (void)compute:(CDStruct_31142d93)arg1;
- (id)init;
- (float)filter3X:(float *)arg1 Y:(float *)arg2 x:(float)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

