//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GLUEStatefulView.h"

#import "SPTBrowseCategoryCard.h"

@class GLUEImageView, GLUELabel, NSString, SPTBrowseCategoryCardBackgroundView, SPTBrowseCategoryCardStateStyle, UIView;

@interface SPTBrowseCategoryCardView : GLUEStatefulView <SPTBrowseCategoryCard>
{
    GLUELabel *_titleLabel;
    SPTBrowseCategoryCardBackgroundView *_backgroundView;
    UIView *_containerView;
    SPTBrowseCategoryCardStateStyle *_stateStyle;
}

@property(retain, nonatomic) SPTBrowseCategoryCardStateStyle *stateStyle; // @synthesize stateStyle=_stateStyle;
@property(readonly, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
@property(readonly, nonatomic) SPTBrowseCategoryCardBackgroundView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(readonly, nonatomic) GLUELabel *titleLabel; // @synthesize titleLabel=_titleLabel;
- (void).cxx_destruct;
@property(readonly, nonatomic) GLUEImageView *backgroundImageView;
- (id)accessibilityLabel;
- (void)applyStateStyle:(id)arg1;
- (void)addViewConstraints;
- (void)setupContainerAndSubviews;
- (void)setupBackgroundView;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

