//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SPTDrivingBarButtonHandlerDelegate.h"
#import "SPTDrivingFeatureFlagStateObserver.h"
#import "SPTDrivingService.h"
#import "SPTDrivingStateObserver.h"
#import "SPTDrivingTestManagerSettingsDelegate.h"
#import "SPTMetaViewControllerObserver.h"
#import "SPTService.h"

@class NSString, SPTAllocationContext, SPTDrivingBarButtonHandler, SPTDrivingBaselineViewControllerFactory, SPTDrivingLogger, SPTDrivingOnboardingManager, SPTDrivingPlayFirstViewControllerFactory, SPTDrivingPlayer, SPTDrivingRemoteContentURLResolver, SPTDrivingSession, SPTDrivingTestManager, UIViewController;

@interface SPTDrivingServiceImplementation : NSObject <SPTDrivingStateObserver, SPTDrivingTestManagerSettingsDelegate, SPTMetaViewControllerObserver, SPTDrivingBarButtonHandlerDelegate, SPTService, SPTDrivingService, SPTDrivingFeatureFlagStateObserver>
{
    _Bool _onboardingPresented;
    _Bool _wasPlayingBeforeOnboardingPresented;
    SPTDrivingTestManager *_testManager;
    SPTDrivingOnboardingManager *_onboardingManager;
    id <SPTSessionService> _clientSessionService;
    id <SPTGLUEService> _glueService;
    id <SPTHubFrameworkService> _hubFrameworkService;
    id <SPTPlayerFeature> _playerService;
    id <SPTPlaylistPlatformService> _playlistService;
    id <SPTRecentlyPlayedService> _recentlyPlayedService;
    id <SPTSettingsFeature> _settingsService;
    id <SPTCollectionPlatformService> _collectionPlatformService;
    id <SPTNetworkService> _networkService;
    id <SPTDrivingStateDetectionService> _drivingDetectionService;
    id <SPTContainerService> _containerService;
    id <SPTContainerUIService> _containerUIService;
    id <SPTDrivingLiveRadioService> _liveRadioService;
    id <SPTUIPresentationService> _presentationService;
    id <SPTExternalIntegrationDriverDistractionService> _driverDistractionService;
    id <SPTExternalIntegrationPlaybackService> _playbackService;
    id <SPTExternalIntegrationContentService> _contentService;
    id <SPTVoiceService> _voiceService;
    id <SPTNavigationFeature> _navigationService;
    id <SlateFeature> _slateService;
    id <SPTFeatureFlaggingService> _featureFlaggingService;
    id <SPTPlayer> _player;
    SPTDrivingPlayer *_drivingPlayer;
    UIViewController *_onboardingViewController;
    SPTDrivingLogger *_logger;
    SPTDrivingSession *_drivingSession;
    SPTDrivingBaselineViewControllerFactory *_drivingBaselineViewControllerFactory;
    SPTDrivingPlayFirstViewControllerFactory *_drivingPlayFirstViewControllerFactory;
    SPTDrivingRemoteContentURLResolver *_remoteContentURLResolver;
    id <SPTDrivingVoiceFeedbackEngine> _voiceFeedbackEngine;
    SPTDrivingBarButtonHandler *_barButtonHandler;
}

+ (id)serviceIdentifier;
@property(nonatomic) _Bool wasPlayingBeforeOnboardingPresented; // @synthesize wasPlayingBeforeOnboardingPresented=_wasPlayingBeforeOnboardingPresented;
@property(nonatomic, getter=isOnboardingPresented) _Bool onboardingPresented; // @synthesize onboardingPresented=_onboardingPresented;
@property(retain, nonatomic) SPTDrivingBarButtonHandler *barButtonHandler; // @synthesize barButtonHandler=_barButtonHandler;
@property(retain, nonatomic) id <SPTDrivingVoiceFeedbackEngine> voiceFeedbackEngine; // @synthesize voiceFeedbackEngine=_voiceFeedbackEngine;
@property(retain, nonatomic) SPTDrivingRemoteContentURLResolver *remoteContentURLResolver; // @synthesize remoteContentURLResolver=_remoteContentURLResolver;
@property(retain, nonatomic) SPTDrivingPlayFirstViewControllerFactory *drivingPlayFirstViewControllerFactory; // @synthesize drivingPlayFirstViewControllerFactory=_drivingPlayFirstViewControllerFactory;
@property(retain, nonatomic) SPTDrivingBaselineViewControllerFactory *drivingBaselineViewControllerFactory; // @synthesize drivingBaselineViewControllerFactory=_drivingBaselineViewControllerFactory;
@property(retain, nonatomic) SPTDrivingSession *drivingSession; // @synthesize drivingSession=_drivingSession;
@property(retain, nonatomic) SPTDrivingLogger *logger; // @synthesize logger=_logger;
@property(retain, nonatomic) UIViewController *onboardingViewController; // @synthesize onboardingViewController=_onboardingViewController;
@property(retain, nonatomic) SPTDrivingPlayer *drivingPlayer; // @synthesize drivingPlayer=_drivingPlayer;
@property(retain, nonatomic) id <SPTPlayer> player; // @synthesize player=_player;
@property(nonatomic) __weak id <SPTFeatureFlaggingService> featureFlaggingService; // @synthesize featureFlaggingService=_featureFlaggingService;
@property(nonatomic) __weak id <SlateFeature> slateService; // @synthesize slateService=_slateService;
@property(nonatomic) __weak id <SPTNavigationFeature> navigationService; // @synthesize navigationService=_navigationService;
@property(nonatomic) __weak id <SPTVoiceService> voiceService; // @synthesize voiceService=_voiceService;
@property(nonatomic) __weak id <SPTExternalIntegrationContentService> contentService; // @synthesize contentService=_contentService;
@property(nonatomic) __weak id <SPTExternalIntegrationPlaybackService> playbackService; // @synthesize playbackService=_playbackService;
@property(nonatomic) __weak id <SPTExternalIntegrationDriverDistractionService> driverDistractionService; // @synthesize driverDistractionService=_driverDistractionService;
@property(nonatomic) __weak id <SPTUIPresentationService> presentationService; // @synthesize presentationService=_presentationService;
@property(nonatomic) __weak id <SPTDrivingLiveRadioService> liveRadioService; // @synthesize liveRadioService=_liveRadioService;
@property(nonatomic) __weak id <SPTContainerUIService> containerUIService; // @synthesize containerUIService=_containerUIService;
@property(nonatomic) __weak id <SPTContainerService> containerService; // @synthesize containerService=_containerService;
@property(nonatomic) __weak id <SPTDrivingStateDetectionService> drivingDetectionService; // @synthesize drivingDetectionService=_drivingDetectionService;
@property(nonatomic) __weak id <SPTNetworkService> networkService; // @synthesize networkService=_networkService;
@property(nonatomic) __weak id <SPTCollectionPlatformService> collectionPlatformService; // @synthesize collectionPlatformService=_collectionPlatformService;
@property(nonatomic) __weak id <SPTSettingsFeature> settingsService; // @synthesize settingsService=_settingsService;
@property(nonatomic) __weak id <SPTRecentlyPlayedService> recentlyPlayedService; // @synthesize recentlyPlayedService=_recentlyPlayedService;
@property(nonatomic) __weak id <SPTPlaylistPlatformService> playlistService; // @synthesize playlistService=_playlistService;
@property(nonatomic) __weak id <SPTPlayerFeature> playerService; // @synthesize playerService=_playerService;
@property(nonatomic) __weak id <SPTHubFrameworkService> hubFrameworkService; // @synthesize hubFrameworkService=_hubFrameworkService;
@property(nonatomic) __weak id <SPTGLUEService> glueService; // @synthesize glueService=_glueService;
@property(nonatomic) __weak id <SPTSessionService> clientSessionService; // @synthesize clientSessionService=_clientSessionService;
@property(retain, nonatomic) SPTDrivingOnboardingManager *onboardingManager; // @synthesize onboardingManager=_onboardingManager;
@property(retain, nonatomic) SPTDrivingTestManager *testManager; // @synthesize testManager=_testManager;
- (void).cxx_destruct;
- (id)provideCarsSettingsWithSettingsViewController:(id)arg1;
- (void)registerDrivingSettingsSection;
- (void)didChangeRootViewOfMetaViewController:(id)arg1;
- (void)drivingBarButtonHandlerDidTapBarButton:(id)arg1;
- (void)drivingStateDetector:(id)arg1 drivingStateDidChange:(id)arg2;
- (void)testManagerDidTapResetOnboardingButton:(id)arg1;
- (void)registerFeatureSettingsPage;
- (id)createContentOperationFactory;
- (id)createOfflineContentOperationFactory;
- (id)createYourMusicContentOperationFactory;
- (id)createRemoteContentOperationFactory;
- (id)createRecentlyPlayedContentOperationFactory;
- (void)deregisterDrivingHub;
- (void)registerDrivingHub;
- (void)featureEnabledStateChanged:(_Bool)arg1;
- (void)launchDrivingModeOnboarding;
- (void)launchDrivingModeWithOrigin:(unsigned long long)arg1;
- (id)provideDrivingViewController;
- (void)disable;
- (void)enable;
- (void)unload;
- (void)load;
- (void)configureWithServices:(id)arg1;

// Remaining properties
@property(retain, nonatomic) SPTAllocationContext *allocationContext;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

