//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "SPTDrivingViewModelDelegate.h"
#import "SPTHubContainerViewControllerDelegate.h"
#import "SPTPageContainer.h"
#import "SPTPageController.h"

@class NSLayoutConstraint, NSString, NSURL, SPTDrivingColorExtractor, SPTDrivingHeaderView, SPTDrivingLogger, SPTDrivingOnboardingInteractionsHintView, SPTDrivingPlayerBarView, SPTDrivingSkipLimitOverlayPresenter, SPTDrivingViewModel, UITapGestureRecognizer, UIView, UIViewController<SPTPageController><SPTHubContainerViewController>;

@interface SPTDrivingViewController : UIViewController <SPTPageContainer, SPTDrivingViewModelDelegate, SPTHubContainerViewControllerDelegate, SPTPageController>
{
    _Bool _hasScrolledToInitialShelf;
    NSLayoutConstraint *_playerTopConstraint;
    SPTDrivingHeaderView *_headerView;
    SPTDrivingPlayerBarView *_playerBarView;
    UIView *_adView;
    UIViewController<SPTPageController><SPTHubContainerViewController> *_contentViewController;
    SPTDrivingLogger *_logger;
    SPTDrivingOnboardingInteractionsHintView *_interactionsHintView;
    SPTDrivingColorExtractor *_colorExtractor;
    SPTDrivingSkipLimitOverlayPresenter *_skipLimitOverlayPresenter;
    SPTDrivingViewModel *_viewModel;
    UITapGestureRecognizer *_contentViewTapGestureRecognizer;
    UITapGestureRecognizer *_adViewTapGestureRecognizer;
    UITapGestureRecognizer *_interactionsHintViewTapGestureRecognizer;
}

@property(retain, nonatomic) UITapGestureRecognizer *interactionsHintViewTapGestureRecognizer; // @synthesize interactionsHintViewTapGestureRecognizer=_interactionsHintViewTapGestureRecognizer;
@property(retain, nonatomic) UITapGestureRecognizer *adViewTapGestureRecognizer; // @synthesize adViewTapGestureRecognizer=_adViewTapGestureRecognizer;
@property(retain, nonatomic) UITapGestureRecognizer *contentViewTapGestureRecognizer; // @synthesize contentViewTapGestureRecognizer=_contentViewTapGestureRecognizer;
@property(readonly, nonatomic) SPTDrivingViewModel *viewModel; // @synthesize viewModel=_viewModel;
@property(readonly, nonatomic) SPTDrivingSkipLimitOverlayPresenter *skipLimitOverlayPresenter; // @synthesize skipLimitOverlayPresenter=_skipLimitOverlayPresenter;
@property(readonly, nonatomic) SPTDrivingColorExtractor *colorExtractor; // @synthesize colorExtractor=_colorExtractor;
@property(retain, nonatomic) SPTDrivingOnboardingInteractionsHintView *interactionsHintView; // @synthesize interactionsHintView=_interactionsHintView;
@property(nonatomic) _Bool hasScrolledToInitialShelf; // @synthesize hasScrolledToInitialShelf=_hasScrolledToInitialShelf;
@property(readonly, nonatomic) SPTDrivingLogger *logger; // @synthesize logger=_logger;
@property(readonly, nonatomic) UIViewController<SPTPageController><SPTHubContainerViewController> *contentViewController; // @synthesize contentViewController=_contentViewController;
@property(retain, nonatomic) UIView *adView; // @synthesize adView=_adView;
@property(retain, nonatomic) SPTDrivingPlayerBarView *playerBarView; // @synthesize playerBarView=_playerBarView;
@property(retain, nonatomic) SPTDrivingHeaderView *headerView; // @synthesize headerView=_headerView;
@property(retain, nonatomic) NSLayoutConstraint *playerTopConstraint; // @synthesize playerTopConstraint=_playerTopConstraint;
- (void).cxx_destruct;
- (struct CGPoint)centerPointForOverlayComponentInViewController:(id)arg1 proposedCenterPoint:(struct CGPoint)arg2;
- (void)viewController:(id)arg1 didPerformActionWithContext:(id)arg2;
- (void)viewControllerDidFinishRendering:(id)arg1;
- (void)viewModelDidReachSkipLimit:(id)arg1;
- (void)viewModel:(id)arg1 delegateShouldShowIndicatorIcon:(long long)arg2 persistent:(_Bool)arg3;
- (void)viewModelDidUpdate:(id)arg1;
@property(readonly, nonatomic, getter=spt_currentPageController) id <SPTPageController> currentPageController;
@property(readonly, nonatomic, getter=spt_pageContainer) id <SPTPageContainer> pageContainer;
@property(readonly, nonatomic, getter=spt_pageURI) NSURL *pageURI;
@property(readonly, nonatomic, getter=spt_pageIdentifier) NSString *pageIdentifier;
- (void)didNavigateToIndexPath:(id)arg1;
- (id)centeredCardView;
- (void)scrollToRecentlyPlayedShelfAnimated:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)scrollToShelfIndex:(unsigned long long)arg1 animated:(_Bool)arg2 completion:(CDUnknownBlockType)arg3;
- (long long)indexForShelfWithIdentifier:(id)arg1 inViewController:(id)arg2;
- (void)didTapCloseButton;
- (id)createHeaderView;
- (void)applyConstraints;
- (void)didTapHintView:(id)arg1;
- (void)didTapAdView:(id)arg1;
- (void)didSingleTap:(id)arg1;
- (void)setupGestureRecognizers;
- (void)viewDidLoad;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (id)initWithViewModel:(id)arg1 contentViewController:(id)arg2 colorExtractor:(id)arg3 skipLimitOverlayPresenter:(id)arg4 logger:(id)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

