//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class GLUEEntityRowStyle, GLUETrackCloudStyle, SPTFreeTierPlaylistAddSongsViewStyle, SPTFreeTierPlaylistGLUETheme, SPTFreeTierPlaylistSponsoredLogoCellStyle;

@interface SPTFreeTierPlaylistCellConfigurator : NSObject
{
    id <SPTFreeTierPlaylistCellConfiguratorDelegate> _delegate;
    id <SPTFreeTierPlaylistViewModel> _viewModel;
    SPTFreeTierPlaylistGLUETheme *_theme;
    GLUEEntityRowStyle *_trackRowStyle;
    GLUETrackCloudStyle *_cloudStyle;
    GLUETrackCloudStyle *_recommendationsCloudStyle;
    SPTFreeTierPlaylistAddSongsViewStyle *_allSongsViewStyle;
    SPTFreeTierPlaylistSponsoredLogoCellStyle *_sponsorshipStyle;
}

@property(retain, nonatomic) SPTFreeTierPlaylistSponsoredLogoCellStyle *sponsorshipStyle; // @synthesize sponsorshipStyle=_sponsorshipStyle;
@property(retain, nonatomic) SPTFreeTierPlaylistAddSongsViewStyle *allSongsViewStyle; // @synthesize allSongsViewStyle=_allSongsViewStyle;
@property(retain, nonatomic) GLUETrackCloudStyle *recommendationsCloudStyle; // @synthesize recommendationsCloudStyle=_recommendationsCloudStyle;
@property(retain, nonatomic) GLUETrackCloudStyle *cloudStyle; // @synthesize cloudStyle=_cloudStyle;
@property(retain, nonatomic) GLUEEntityRowStyle *trackRowStyle; // @synthesize trackRowStyle=_trackRowStyle;
@property(readonly, nonatomic) SPTFreeTierPlaylistGLUETheme *theme; // @synthesize theme=_theme;
@property(readonly, nonatomic) id <SPTFreeTierPlaylistViewModel> viewModel; // @synthesize viewModel=_viewModel;
@property(nonatomic) __weak id <SPTFreeTierPlaylistCellConfiguratorDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)addSongsAction;
- (void)setupTrailingAccessoryForCell:(id)arg1 trackViewModel:(id)arg2;
- (void)configureMultipleAccessoriesViewForCell:(id)arg1 accessoryLabelType:(long long)arg2;
- (id)contentViewForCell:(id)arg1;
- (void)configureSponsorshipCell:(id)arg1 withSponsoredViewModel:(id)arg2;
- (id)currentCloudStyle;
- (void)configureCloudCell:(id)arg1 withCloudViewModel:(id)arg2 andContainerWidth:(double)arg3;
- (void)configureCell:(id)arg1 withTrackViewModel:(id)arg2;
- (double)preferredCellHeightAtIndexPath:(id)arg1 andContainerWidth:(double)arg2;
- (void)configureSectionHeader:(id)arg1 section:(unsigned long long)arg2;
- (double)preferredHeaderHeightForSection:(unsigned long long)arg1;
- (id)initWithViewModel:(id)arg1 trackRowStyle:(id)arg2 sponsorshipStyle:(id)arg3 theme:(id)arg4;

@end

