//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "GLUEStyleable.h"

@class GLUEButton, GLUEGradientView, NSLayoutConstraint, NSString, SPTFreeTierTasteOnboardingArtistPickerCollectionViewLayout, UICollectionView;

@interface SPTFreeTierTasteOnboardingArtistPickerView : UIView <GLUEStyleable>
{
    SPTFreeTierTasteOnboardingArtistPickerCollectionViewLayout *_collectionViewLayout;
    UICollectionView *_collectionView;
    GLUEGradientView *_overlayGradientView;
    GLUEButton *_actionButton;
    GLUEGradientView *_backgroundGradientView;
    GLUEGradientView *_backgroundOverlayGradientView;
    UIView *_searchBarContainerView;
    NSLayoutConstraint *_searchBarContainerViewTopConstraint;
    NSLayoutConstraint *_searchBarContainerViewHeightConstraint;
    NSLayoutConstraint *_collectionViewTopConstraint;
    NSLayoutConstraint *_actionButtonBottomConstraint;
    NSLayoutConstraint *_actionButtonTopConstraint;
}

@property(retain, nonatomic) NSLayoutConstraint *actionButtonTopConstraint; // @synthesize actionButtonTopConstraint=_actionButtonTopConstraint;
@property(retain, nonatomic) NSLayoutConstraint *actionButtonBottomConstraint; // @synthesize actionButtonBottomConstraint=_actionButtonBottomConstraint;
@property(retain, nonatomic) NSLayoutConstraint *collectionViewTopConstraint; // @synthesize collectionViewTopConstraint=_collectionViewTopConstraint;
@property(retain, nonatomic) NSLayoutConstraint *searchBarContainerViewHeightConstraint; // @synthesize searchBarContainerViewHeightConstraint=_searchBarContainerViewHeightConstraint;
@property(retain, nonatomic) NSLayoutConstraint *searchBarContainerViewTopConstraint; // @synthesize searchBarContainerViewTopConstraint=_searchBarContainerViewTopConstraint;
@property(readonly, nonatomic) UIView *searchBarContainerView; // @synthesize searchBarContainerView=_searchBarContainerView;
@property(readonly, nonatomic) GLUEGradientView *backgroundOverlayGradientView; // @synthesize backgroundOverlayGradientView=_backgroundOverlayGradientView;
@property(readonly, nonatomic) GLUEGradientView *backgroundGradientView; // @synthesize backgroundGradientView=_backgroundGradientView;
@property(readonly, nonatomic) GLUEButton *actionButton; // @synthesize actionButton=_actionButton;
@property(readonly, nonatomic) GLUEGradientView *overlayGradientView; // @synthesize overlayGradientView=_overlayGradientView;
@property(readonly, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(readonly, nonatomic) SPTFreeTierTasteOnboardingArtistPickerCollectionViewLayout *collectionViewLayout; // @synthesize collectionViewLayout=_collectionViewLayout;
- (void).cxx_destruct;
- (void)glue_applyStyle:(id)arg1;
- (void)activateConstraints;
- (void)updateLayoutMarginsWithTopAnchor:(id)arg1 bottomAnchor:(id)arg2;
- (void)addSearchBar:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

