//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, NSURL, SPTViewLogger;

@interface SPTFreeTierPlaylistLogger : NSObject
{
    NSString *_playlistPageIdentifier;
    id <SPTLogCenterProtocol> _logCenter;
    SPTViewLogger *_viewLogger;
    NSURL *_pageURL;
    id <SPTOnDemandSet> _onDemandSet;
}

@property(retain, nonatomic) id <SPTOnDemandSet> onDemandSet; // @synthesize onDemandSet=_onDemandSet;
@property(retain, nonatomic) NSURL *pageURL; // @synthesize pageURL=_pageURL;
@property(retain, nonatomic) SPTViewLogger *viewLogger; // @synthesize viewLogger=_viewLogger;
@property(retain, nonatomic) id <SPTLogCenterProtocol> logCenter; // @synthesize logCenter=_logCenter;
@property(copy, nonatomic) NSString *playlistPageIdentifier; // @synthesize playlistPageIdentifier=_playlistPageIdentifier;
- (void).cxx_destruct;
- (void)logUIInteractionWithSectionId:(id)arg1 itemIndex:(long long)arg2 targetURI:(id)arg3 interactionType:(id)arg4 userIntent:(id)arg5;
- (void)logUIInteractionWithSectionId:(id)arg1 targetURI:(id)arg2 userIntent:(id)arg3;
- (void)logTrackContextMenuSelectedAtIndex:(unsigned long long)arg1 trackURI:(id)arg2;
- (void)logTrackSelectedAtIndex:(unsigned long long)arg1 trackURI:(id)arg2;
- (void)logTrackCloudSelected:(_Bool)arg1;
- (void)logAddSongsSelectedOnEmptyPlaylist:(_Bool)arg1;
- (void)logShuffleBadgeSelected;
- (void)logPlayButtonStartPlaying:(_Bool)arg1;
- (void)logHeaderContextMenuButton;
- (void)logHeartButtonSelected:(_Bool)arg1;
- (void)logViewDidFailToLoadWithError:(id)arg1 pageIdentifier:(id)arg2;
- (void)logViewLoadingCancelledWithPageIdentifier:(id)arg1;
- (void)logViewDidLoadWithPageIdentifier:(id)arg1;
- (void)logViewLoadingStartedWithPageIdentifier:(id)arg1;
- (id)initWithLogCenter:(id)arg1 viewLogger:(id)arg2 pageURL:(id)arg3 onDemandSet:(id)arg4;

@end

