//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SPTService.h"

@class NSString, SPTAllocationContext;

@interface SPTFreeTierPlaylistUIService : NSObject <SPTService>
{
    id <SPTFreeTierAllSongsService> _allSongsService;
    id <SPTAssistedCurationUIService> _assistedCurationUIService;
    id <SPTCollectionPlatformService> _collectionPlatformService;
    id <SPTContainerService> _containerService;
    id <SPTContainerUIService> _containerUIService;
    id <SPContextMenuFeature> _contextMenuService;
    id <SPTCoreService> _coreService;
    id <SPTFormatListPlatformService> _formatListPlatformService;
    id <SPTFreeTierPlaylistService> _freeTierPlaylistService;
    id <SPTGLUEService> _glueService;
    id <SPTNavigationFeature> _navigationService;
    id <SPTNetworkService> _networkService;
    id <SPTOnDemandService> _onDemandService;
    id <SPTPlayerFeature> _playerService;
    id <SPTFreeTierRecommendedPlaylistService> _recommendedPlaylistService;
    id <SPTURIDispatchService> _uriDispatchService;
    id <SPTAdsService> _adsService;
    id <SPTFreeTierEducationService> _educationService;
}

+ (id)serviceIdentifier;
@property(nonatomic) __weak id <SPTFreeTierEducationService> educationService; // @synthesize educationService=_educationService;
@property(nonatomic) __weak id <SPTAdsService> adsService; // @synthesize adsService=_adsService;
@property(nonatomic) __weak id <SPTURIDispatchService> uriDispatchService; // @synthesize uriDispatchService=_uriDispatchService;
@property(nonatomic) __weak id <SPTFreeTierRecommendedPlaylistService> recommendedPlaylistService; // @synthesize recommendedPlaylistService=_recommendedPlaylistService;
@property(nonatomic) __weak id <SPTPlayerFeature> playerService; // @synthesize playerService=_playerService;
@property(nonatomic) __weak id <SPTOnDemandService> onDemandService; // @synthesize onDemandService=_onDemandService;
@property(nonatomic) __weak id <SPTNetworkService> networkService; // @synthesize networkService=_networkService;
@property(nonatomic) __weak id <SPTNavigationFeature> navigationService; // @synthesize navigationService=_navigationService;
@property(nonatomic) __weak id <SPTGLUEService> glueService; // @synthesize glueService=_glueService;
@property(nonatomic) __weak id <SPTFreeTierPlaylistService> freeTierPlaylistService; // @synthesize freeTierPlaylistService=_freeTierPlaylistService;
@property(nonatomic) __weak id <SPTFormatListPlatformService> formatListPlatformService; // @synthesize formatListPlatformService=_formatListPlatformService;
@property(nonatomic) __weak id <SPTCoreService> coreService; // @synthesize coreService=_coreService;
@property(nonatomic) __weak id <SPContextMenuFeature> contextMenuService; // @synthesize contextMenuService=_contextMenuService;
@property(nonatomic) __weak id <SPTContainerUIService> containerUIService; // @synthesize containerUIService=_containerUIService;
@property(nonatomic) __weak id <SPTContainerService> containerService; // @synthesize containerService=_containerService;
@property(nonatomic) __weak id <SPTCollectionPlatformService> collectionPlatformService; // @synthesize collectionPlatformService=_collectionPlatformService;
@property(nonatomic) __weak id <SPTAssistedCurationUIService> assistedCurationUIService; // @synthesize assistedCurationUIService=_assistedCurationUIService;
@property(nonatomic) __weak id <SPTFreeTierAllSongsService> allSongsService; // @synthesize allSongsService=_allSongsService;
- (void).cxx_destruct;
- (id)providerFooterProviderForPlaylistURL:(id)arg1 context:(id)arg2;
- (id)provideLoggerForURI:(id)arg1;
- (id)provideSponsoredViewModelForURL:(id)arg1;
- (id)providePlaylistViewControllerForURL:(id)arg1 withContext:(id)arg2;
- (void)registerPage;
- (void)load;
- (void)configureWithServices:(id)arg1;

// Remaining properties
@property(retain, nonatomic) SPTAllocationContext *allocationContext;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

