//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "EXP_HUBContentOperation.h"

@interface SPTFreeTierEntityUmbrellaHeaderContentOperation : NSObject <EXP_HUBContentOperation>
{
    id <EXP_HUBContentOperationDelegate> delegate;
}

@property(nonatomic) __weak id <EXP_HUBContentOperationDelegate> delegate; // @synthesize delegate;
- (void).cxx_destruct;
- (void)copyComponentModelBuilderFrom:(id)arg1 to:(id)arg2;
- (void)performForViewModelBuilder:(id)arg1 previousError:(id)arg2;

@end

