//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface SPTFeatureManagerLoggerEvent : NSObject
{
    NSString *_identifier;
    double _startTime;
    double _elapsedTime;
    NSString *_serviceIdentifier;
    NSString *_managerIdentifier;
}

+ (id)identifierForServiceManager:(id)arg1 serviceIdentifier:(id)arg2;
@property(copy, nonatomic) NSString *managerIdentifier; // @synthesize managerIdentifier=_managerIdentifier;
@property(copy, nonatomic) NSString *serviceIdentifier; // @synthesize serviceIdentifier=_serviceIdentifier;
@property(nonatomic) double elapsedTime; // @synthesize elapsedTime=_elapsedTime;
@property(nonatomic) double startTime; // @synthesize startTime=_startTime;
@property(readonly, copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (void).cxx_destruct;
@property(readonly, nonatomic) double elapsedTimeInMilliseconds;
- (void)end;
- (void)start;
- (id)initWithManagerIdentifier:(id)arg1 serviceIdentifier:(id)arg2;

@end

