//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UITableViewDataSource.h"

@class NSString, SPTTableView, SettingsSwitchTableViewCell;

@interface SPTLoginInviteDebugViewController : UIViewController <UITableViewDataSource>
{
    SPTTableView *_tableView;
    SettingsSwitchTableViewCell *_marketEndpointCell;
    SettingsSwitchTableViewCell *_inviteEnpointCell;
}

@property(retain, nonatomic) SettingsSwitchTableViewCell *inviteEnpointCell; // @synthesize inviteEnpointCell=_inviteEnpointCell;
@property(retain, nonatomic) SettingsSwitchTableViewCell *marketEndpointCell; // @synthesize marketEndpointCell=_marketEndpointCell;
@property(retain, nonatomic) SPTTableView *tableView; // @synthesize tableView=_tableView;
- (void).cxx_destruct;
- (id)tableView:(id)arg1 titleForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)saveUserDefaults;
- (void)switchValueDidChange:(id)arg1;
- (void)viewWillLayoutSubviews;
- (void)viewDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

