//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SPTDataLoaderDelegate.h"

@class NSString, SPTDataLoader;

@interface SPTLoginValidateCodeRequest : NSObject <SPTDataLoaderDelegate>
{
    id <SPTLoginValidateCodeRequestDelegate> _delegate;
    NSString *_endpointURL;
    NSString *_code;
    NSString *_market;
    SPTDataLoader *_dataLoader;
}

@property(readonly, nonatomic) SPTDataLoader *dataLoader; // @synthesize dataLoader=_dataLoader;
@property(readonly, copy, nonatomic) NSString *market; // @synthesize market=_market;
@property(readonly, copy, nonatomic) NSString *code; // @synthesize code=_code;
@property(readonly, copy, nonatomic) NSString *endpointURL; // @synthesize endpointURL=_endpointURL;
@property(nonatomic) __weak id <SPTLoginValidateCodeRequestDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)dataLoader:(id)arg1 didReceiveErrorResponse:(id)arg2;
- (void)dataLoader:(id)arg1 didReceiveSuccessfulResponse:(id)arg2;
- (void)emitResponseErrorWithCode:(long long)arg1;
- (void)handleResponse:(id)arg1;
- (void)start;
- (id)initWithEndpointURL:(id)arg1 code:(id)arg2 market:(id)arg3 dataLoader:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

