//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "SPTImageLoaderDelegate.h"
#import "SPTLyricsFullScreenHeaderViewDelegate.h"
#import "SPTLyricsTableFooterViewDelegate.h"
#import "SPTPlayerObserver.h"
#import "UIScrollViewDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class CAGradientLayer, GLUEGradientView, NSMutableSet, NSString, NSTimer, SPTImageBlurView, SPTLyricsFullScreenHeaderView, SPTLyricsLineSet, SPTLyricsLoggingService, SPTLyricsService, SPTLyricsTableFooterView, SPTPlayerTrack, UITableView, UIView;

@interface SPTLyricsFullScreenViewController : UIViewController <SPTPlayerObserver, UITableViewDataSource, UITableViewDelegate, UIScrollViewDelegate, SPTLyricsFullScreenHeaderViewDelegate, SPTLyricsTableFooterViewDelegate, SPTImageLoaderDelegate>
{
    _Bool _userInteracted;
    SPTLyricsService *_lyricsService;
    SPTLyricsLoggingService *_loggingService;
    id <SPTPlayer> _player;
    id <SPTImageLoader> _imageLoader;
    SPTImageBlurView *_backgroundView;
    GLUEGradientView *_backgroundGradientView;
    UITableView *_tableView;
    SPTLyricsFullScreenHeaderView *_headerView;
    UIView *_fadeView;
    CAGradientLayer *_fadeMaskLayer;
    SPTPlayerTrack *_track;
    SPTLyricsLineSet *_lyricsLineSet;
    NSTimer *_timer;
    SPTPlayerTrack *_currentTrack;
    SPTLyricsTableFooterView *_footerView;
    NSMutableSet *_lineIndexesLogged;
    double _startingScrollContentYOffset;
    double _lastDeltaContentYOffset;
    long long _selectedLineIndex;
}

@property(nonatomic) long long selectedLineIndex; // @synthesize selectedLineIndex=_selectedLineIndex;
@property(nonatomic) double lastDeltaContentYOffset; // @synthesize lastDeltaContentYOffset=_lastDeltaContentYOffset;
@property(nonatomic) double startingScrollContentYOffset; // @synthesize startingScrollContentYOffset=_startingScrollContentYOffset;
@property(retain, nonatomic) NSMutableSet *lineIndexesLogged; // @synthesize lineIndexesLogged=_lineIndexesLogged;
@property(nonatomic) _Bool userInteracted; // @synthesize userInteracted=_userInteracted;
@property(retain, nonatomic) SPTLyricsTableFooterView *footerView; // @synthesize footerView=_footerView;
@property(retain, nonatomic) SPTPlayerTrack *currentTrack; // @synthesize currentTrack=_currentTrack;
@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
@property(retain, nonatomic) SPTLyricsLineSet *lyricsLineSet; // @synthesize lyricsLineSet=_lyricsLineSet;
@property(retain, nonatomic) SPTPlayerTrack *track; // @synthesize track=_track;
@property(retain, nonatomic) CAGradientLayer *fadeMaskLayer; // @synthesize fadeMaskLayer=_fadeMaskLayer;
@property(retain, nonatomic) UIView *fadeView; // @synthesize fadeView=_fadeView;
@property(retain, nonatomic) SPTLyricsFullScreenHeaderView *headerView; // @synthesize headerView=_headerView;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) GLUEGradientView *backgroundGradientView; // @synthesize backgroundGradientView=_backgroundGradientView;
@property(retain, nonatomic) SPTImageBlurView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(retain, nonatomic) id <SPTImageLoader> imageLoader; // @synthesize imageLoader=_imageLoader;
@property(retain, nonatomic) id <SPTPlayer> player; // @synthesize player=_player;
@property(retain, nonatomic) SPTLyricsLoggingService *loggingService; // @synthesize loggingService=_loggingService;
@property(retain, nonatomic) SPTLyricsService *lyricsService; // @synthesize lyricsService=_lyricsService;
- (void).cxx_destruct;
- (void)imageLoader:(id)arg1 didLoadImage:(id)arg2 forURL:(id)arg3 loadTime:(double)arg4 context:(id)arg5;
- (void)providerLinkButtonPressed;
- (void)closeButtonPressed;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)updateTableViewFooterSize;
- (void)updateBackgroundViewForImageURL:(id)arg1;
- (void)dismissFullScreen;
- (void)dealloc;
- (void)player:(id)arg1 stateDidChange:(id)arg2 fromState:(id)arg3;
- (void)updateState;
- (void)updateWithPlayerState:(id)arg1;
- (void)scheduleNextLineWithPlayerState:(id)arg1;
- (void)showNextCardWithDelay:(double)arg1;
- (void)scrollAndUpdateSelectedLine;
- (void)viewWillLayoutSubviews;
- (id)textLabelColorForSelected:(_Bool)arg1;
- (struct CGRect)fadeViewFrame;
- (struct CGRect)tableViewFrame;
- (double)tableViewFooterHeight;
- (double)tableViewHeaderHeight;
- (struct CGRect)headerViewFrame;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)initWithTrack:(id)arg1 lyricsService:(id)arg2 player:(id)arg3 loggingService:(id)arg4 imageLoader:(id)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

