//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SPTNowPlayingBaseHeadUnitViewController.h"

#import "SPTNowPlayingRemoteControlPolicyUpdateOserver.h"

@class NSString, SPTNowPlayingBaseHeadUnitController, SPTNowPlayingLogger, SPTNowPlayingModel, SPTNowPlayingRadioHeadUnitView, SPTProgressView;

@interface SPTNowPlayingRadioHeadUnitViewController : SPTNowPlayingBaseHeadUnitViewController <SPTNowPlayingRemoteControlPolicyUpdateOserver>
{
    SPTNowPlayingModel *_model;
    SPTNowPlayingBaseHeadUnitController *_headUnitController;
    id <SPTUpsellManager> _upsellManager;
    id <SPTNowPlayingRemoteControlPolicy> _remoteControlPolicy;
    SPTNowPlayingLogger *_logger;
    id <SPTQueueLogger> _queueLogger;
    SPTProgressView *_progressView;
}

@property(retain, nonatomic) SPTProgressView *progressView; // @synthesize progressView=_progressView;
@property(retain, nonatomic) id <SPTQueueLogger> queueLogger; // @synthesize queueLogger=_queueLogger;
@property(retain, nonatomic) SPTNowPlayingLogger *logger; // @synthesize logger=_logger;
@property(retain, nonatomic) id <SPTNowPlayingRemoteControlPolicy> remoteControlPolicy; // @synthesize remoteControlPolicy=_remoteControlPolicy;
@property(nonatomic) __weak id <SPTUpsellManager> upsellManager; // @synthesize upsellManager=_upsellManager;
@property(retain, nonatomic) SPTNowPlayingBaseHeadUnitController *headUnitController; // @synthesize headUnitController=_headUnitController;
@property(retain, nonatomic) SPTNowPlayingModel *model; // @synthesize model=_model;
- (void).cxx_destruct;
- (id)provideRemoteControlPolicy;
- (void)remoteControlPolicyDidChange:(id)arg1;
- (void)hideImprovingStationProgressViewWithError:(id)arg1;
- (void)showImprovingStationProgressView;
- (void)radioThumbButtonTouchedUpInside:(_Bool)arg1;
- (void)needUpdateUI;
- (_Bool)radioThumbDownSelected;
- (_Bool)radioThumbUpSelected;
- (_Bool)radioThumbsEnabled;
- (void)thumbDownButtonTouchedUpInside:(id)arg1;
- (void)thumbUpButtonTouchedUpInside:(id)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)loadView;
- (void)dealloc;
- (id)initWithModel:(id)arg1 theme:(id)arg2 logger:(id)arg3 queueLogger:(id)arg4 upsellManager:(id)arg5 remoteControlPolicy:(id)arg6;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(retain, nonatomic) SPTNowPlayingRadioHeadUnitView *view; // @dynamic view;

@end

