//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@protocol SPTRecentlyPlayedService <NSObject>
- (id <SPTRecentlyPlayedShortcutItemsProvider>)provideShortcutItemsProvider;
- (id <EXP_SPTRecentlyPlayedHubContentOperation>)provideRecentlyPlayedHubContentOperationWithFilterPredicate:(_Bool (^)(id <SPTCollectionEntityListItem>))arg1;
- (id <EXP_SPTRecentlyPlayedHubContentOperation>)provideRecentlyPlayedHubContentOperationWithoutSongs;
- (id <EXP_SPTRecentlyPlayedHubContentOperation>)provideRecentlyPlayedHubContentOperation;
- (id <SPTRecentlyPlayedHubContentOperationFactory>)provideRecentlyPlayedHubContentOperationFactoryWithFilterPredicate:(_Bool (^)(id <SPTCollectionEntityListItem>))arg1;
- (id <SPTRecentlyPlayedHubContentOperationFactory>)provideRecentlyPlayedHubContentOperationFactoryWithoutSongs;
- (id <SPTRecentlyPlayedHubContentOperationFactory>)provideRecentlyPlayedHubContentOperationFactory;
- (void)registerOptionalContentType:(unsigned long long)arg1;
- (id <SPTCollectionEntityList>)provideRecentlyPlayedEntityListWithoutSongs;
- (id <SPTCollectionEntityList>)provideRecentlyPlayedEntityList;
@end

