//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SPTSearchComponentInjector : NSObject
{
}

+ (void)addPageURI:(id)arg1 toComponentModelBuilder:(id)arg2;
+ (void)injectPageURI:(id)arg1 intoViewModelBuilderAndItsChildren:(id)arg2;
+ (void)injectCustomPageURI:(id)arg1 intoBodyComponentsOnViewModelBuilder:(id)arg2;
+ (void)injectPageURIIntoBodyComponentsOnViewModelBuilder:(id)arg1;
+ (void)removeEmptyViewOverlayComponents:(id)arg1;
+ (id)urisFromEntities:(id)arg1;
+ (void)addSeeAllRowForSection:(id)arg1 withSectionIdentifier:(id)arg2 inViewModelBuilder:(id)arg3;
+ (void)addOfflineSectionContentForSection:(id)arg1 toViewModelBuilder:(id)arg2 viewURI:(id)arg3 withQuery:(id)arg4;
+ (void)addSectionHeaderForSection:(id)arg1 withSectionIdentifier:(id)arg2 toViewModelBuilder:(id)arg3;
+ (void)addOfflineResults:(id)arg1 toViewModelBuilder:(id)arg2 viewURI:(id)arg3 forQuery:(id)arg4;

@end

