//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class GLUETableViewCellStyle, NSString, SPTSearchHistory, SPTSearchHistoryLogger, SPTTableView;

@interface SPTSearchHistoryViewController : UIViewController <UITableViewDataSource, UITableViewDelegate>
{
    id <SPTSearchHistoryViewControllerDelegate> _delegate;
    SPTSearchHistory *_searchHistory;
    SPTSearchHistoryLogger *_logger;
    SPTTableView *_tableView;
    id <GLUETheme> _glueTheme;
    GLUETableViewCellStyle *_searchHistoryCellStyle;
}

+ (id)searchHistoryViewControllerForSearchHistory:(id)arg1 glueTheme:(id)arg2 logCenter:(id)arg3 delegate:(id)arg4;
@property(retain, nonatomic) GLUETableViewCellStyle *searchHistoryCellStyle; // @synthesize searchHistoryCellStyle=_searchHistoryCellStyle;
@property(retain, nonatomic) id <GLUETheme> glueTheme; // @synthesize glueTheme=_glueTheme;
@property(retain, nonatomic) SPTTableView *tableView; // @synthesize tableView=_tableView;
@property(retain, nonatomic) SPTSearchHistoryLogger *logger; // @synthesize logger=_logger;
@property(retain, nonatomic) SPTSearchHistory *searchHistory; // @synthesize searchHistory=_searchHistory;
@property(nonatomic) __weak id <SPTSearchHistoryViewControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (struct CGSize)tableViewHeaderViewSize;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)tableView:(id)arg1 commitEditingStyle:(long long)arg2 forRowAtIndexPath:(id)arg3;
- (_Bool)tableView:(id)arg1 canEditRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (struct UIEdgeInsets)tableViewContentInset;
- (void)updateContentOffset;
- (void)updateContentInset;
- (void)viewDidLayoutSubviews;
- (void)viewWillLayoutSubviews;
- (void)viewWillAppear:(_Bool)arg1;
- (void)didMoveToParentViewController:(id)arg1;
- (void)viewDidLoad;
- (void)updateBottomContentInset:(double)arg1;
- (void)addSearchStringToHistory:(id)arg1;
- (_Bool)searchHistoryIsEmpty;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

