//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SPTTabBarControllerFactory.h"

@class NSString, SPTTheme;

@interface SPTTabBarControllerFactoryImplementation : NSObject <SPTTabBarControllerFactory>
{
    id <SPTNavigationTestManager> _testManager;
    id <SPTNavigationConfiguration> _navigationConfiguration;
    NSString *_friendlyName;
    SPTTheme *_theme;
}

@property(readonly, nonatomic) SPTTheme *theme; // @synthesize theme=_theme;
@property(readonly, copy, nonatomic) NSString *friendlyName; // @synthesize friendlyName=_friendlyName;
@property(readonly, nonatomic) id <SPTNavigationConfiguration> navigationConfiguration; // @synthesize navigationConfiguration=_navigationConfiguration;
@property(readonly, nonatomic) id <SPTNavigationTestManager> testManager; // @synthesize testManager=_testManager;
- (void).cxx_destruct;
- (id)createTabBarContainerWithTabBarController:(struct UIViewController *)arg1;
- (struct UIViewController *)createTabBarControllerWithLogCenter:(id)arg1;
- (id)initWithTestManager:(id)arg1 navigationConfiguration:(id)arg2 friendlyName:(id)arg3 theme:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

