//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SPTDataLoaderDelegate.h"
#import "SPTTermsAndConditionsControllerDelegate.h"

@class NSString, SPTDataLoader, SPTTermsAndConditionsReacceptanceController;

@interface SPTTermsAndConditionsReacceptanceManager : NSObject <SPTDataLoaderDelegate, SPTTermsAndConditionsControllerDelegate>
{
    _Bool _shouldAcceptTermsAndPrivacySeparately;
    long long _statusRequestId;
    id <SPTProductState> _productState;
    SPTDataLoader *_dataLoader;
    SPTTermsAndConditionsReacceptanceController *_termsAndConditionsController;
    id <SPTLinkDispatcher> _linkDispatcher;
    id <SPTAdjustUserTrackerProtocol> _adjustTracker;
    id <SPTAlertController> _alertController;
}

@property(nonatomic) _Bool shouldAcceptTermsAndPrivacySeparately; // @synthesize shouldAcceptTermsAndPrivacySeparately=_shouldAcceptTermsAndPrivacySeparately;
@property(retain, nonatomic) id <SPTAlertController> alertController; // @synthesize alertController=_alertController;
@property(retain, nonatomic) id <SPTAdjustUserTrackerProtocol> adjustTracker; // @synthesize adjustTracker=_adjustTracker;
@property(retain, nonatomic) id <SPTLinkDispatcher> linkDispatcher; // @synthesize linkDispatcher=_linkDispatcher;
@property(retain, nonatomic) SPTTermsAndConditionsReacceptanceController *termsAndConditionsController; // @synthesize termsAndConditionsController=_termsAndConditionsController;
@property(retain, nonatomic) SPTDataLoader *dataLoader; // @synthesize dataLoader=_dataLoader;
@property(retain, nonatomic) id <SPTProductState> productState; // @synthesize productState=_productState;
@property(nonatomic) long long statusRequestId; // @synthesize statusRequestId=_statusRequestId;
- (void).cxx_destruct;
- (void)dataLoader:(id)arg1 didReceiveSuccessfulResponse:(id)arg2;
- (void)dataLoader:(id)arg1 didReceiveErrorResponse:(id)arg2;
- (void)termsAndConditionsControllerDidDeclineTermsAndConditions:(id)arg1;
- (void)termsAndConditionsControllerDidAcceptTermsAndConditions:(id)arg1;
- (id)unacceptedLicenses;
- (void)showTermsAndConditionsControllerWithLicenses:(id)arg1;
- (void)showTermsAndConditionsController;
- (long long)performRequestToEndpoint:(id)arg1 withMethod:(long long)arg2;
- (void)checkNeedsReacceptTermsAndConditions;
- (id)initWithProductState:(id)arg1 dataLoader:(id)arg2 linkDispatcher:(id)arg3 adjustTracker:(id)arg4 alertController:(id)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

