//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData, SPTUDTWrapper, SPTask, SPTaskCompletionSource;

@interface SPTUDTJob : NSObject
{
    SPTaskCompletionSource *_source;
    SPTask *_task;
    SPTUDTWrapper *_transmuxer;
    id <SPTCENCKeySystem> _keySystem;
    NSData *_pssh;
}

@property(retain, nonatomic) NSData *pssh; // @synthesize pssh=_pssh;
@property(retain, nonatomic) id <SPTCENCKeySystem> keySystem; // @synthesize keySystem=_keySystem;
@property(nonatomic) __weak SPTUDTWrapper *transmuxer; // @synthesize transmuxer=_transmuxer;
- (void).cxx_destruct;
- (id)backingTask;
- (void)didFinish;
- (void)failWithError:(id)arg1;
- (void)resolveWithHLSData:(id)arg1;
- (id)init;

@end

