//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class AVPlayerItem, NSData, NSDictionary, NSMutableArray, NSString, SPTNetworkConnectivityController, SPTPlayerOptions, SPTRequestAccounting, SPTVideoLoggerMetrics, SPTVideoTrack;

@interface SPTVideoLogger : NSObject
{
    _Bool _isIncognitoMode;
    _Bool _playerItemLogsCaptured;
    _Bool _endVideoSent;
    double _keyLatency;
    AVPlayerItem *_playerItem;
    SPTVideoLoggerMetrics *_metrics;
    id <SPTLogCenterProtocol> _logCenter;
    SPTRequestAccounting *_requestAccounting;
    id <SPTVideoResourceLoaderInternal> _resourceLoader;
    SPTVideoTrack *_videoTrack;
    SPTPlayerOptions *_playerOptions;
    SPTNetworkConnectivityController *_networkCC;
    NSData *_fileIDData;
    NSData *_playbackIDData;
    NSString *_startReason;
    NSString *_startConnType;
    double _startOffset;
    NSString *_streamingRules;
    NSMutableArray *_allMetrics;
    NSMutableArray *_allAccessLogs;
    NSMutableArray *_allErrorLogs;
    NSString *_keySystem;
    NSDictionary *_pendingMessageId;
}

@property(retain, nonatomic) NSDictionary *pendingMessageId; // @synthesize pendingMessageId=_pendingMessageId;
@property(retain, nonatomic) NSString *keySystem; // @synthesize keySystem=_keySystem;
@property(nonatomic) _Bool endVideoSent; // @synthesize endVideoSent=_endVideoSent;
@property(retain, nonatomic) NSMutableArray *allErrorLogs; // @synthesize allErrorLogs=_allErrorLogs;
@property(retain, nonatomic) NSMutableArray *allAccessLogs; // @synthesize allAccessLogs=_allAccessLogs;
@property(nonatomic) _Bool playerItemLogsCaptured; // @synthesize playerItemLogsCaptured=_playerItemLogsCaptured;
@property(retain, nonatomic) NSMutableArray *allMetrics; // @synthesize allMetrics=_allMetrics;
@property(retain, nonatomic) NSString *streamingRules; // @synthesize streamingRules=_streamingRules;
@property(nonatomic) _Bool isIncognitoMode; // @synthesize isIncognitoMode=_isIncognitoMode;
@property(nonatomic) double startOffset; // @synthesize startOffset=_startOffset;
@property(retain, nonatomic) NSString *startConnType; // @synthesize startConnType=_startConnType;
@property(retain, nonatomic) NSString *startReason; // @synthesize startReason=_startReason;
@property(retain, nonatomic) NSData *playbackIDData; // @synthesize playbackIDData=_playbackIDData;
@property(retain, nonatomic) NSData *fileIDData; // @synthesize fileIDData=_fileIDData;
@property(retain, nonatomic) SPTNetworkConnectivityController *networkCC; // @synthesize networkCC=_networkCC;
@property(retain, nonatomic) SPTPlayerOptions *playerOptions; // @synthesize playerOptions=_playerOptions;
@property(retain, nonatomic) SPTVideoTrack *videoTrack; // @synthesize videoTrack=_videoTrack;
@property(retain, nonatomic) id <SPTVideoResourceLoaderInternal> resourceLoader; // @synthesize resourceLoader=_resourceLoader;
@property(retain, nonatomic) SPTRequestAccounting *requestAccounting; // @synthesize requestAccounting=_requestAccounting;
@property(retain, nonatomic) id <SPTLogCenterProtocol> logCenter; // @synthesize logCenter=_logCenter;
@property(readonly, nonatomic) SPTVideoLoggerMetrics *metrics; // @synthesize metrics=_metrics;
@property(retain, nonatomic) AVPlayerItem *playerItem; // @synthesize playerItem=_playerItem;
@property(readonly, nonatomic) double keyLatency; // @synthesize keyLatency=_keyLatency;
- (void).cxx_destruct;
- (void)logAccessLogEvent:(id)arg1;
- (void)logAllAccessLogEvents;
- (void)logErrorLogEvent:(id)arg1;
- (void)logAllErrorLogEvents;
- (void)captureLogSnapshotsForCurrentPlayerItem;
- (double)debug_manifestLatency;
- (double)debug_uiLatency;
- (double)debug_networkLatency;
- (void)logVideoPlayerError:(id)arg1;
- (_Bool)updateEndVideoMessage:(id)arg1;
- (_Bool)updatePendingEndVideo:(id)arg1;
- (_Bool)logEndVideo:(id)arg1;
- (void)installedKeyWithLatency:(double)arg1 keySystem:(id)arg2;
- (void)startMeasuringMetricsAsOf:(id)arg1 userInitiated:(_Bool)arg2;
- (void)dealloc;
- (id)initWithLogCenter:(id)arg1 requestAccounting:(id)arg2 videoResourceLoader:(id)arg3 videoTrack:(id)arg4 playerOptions:(id)arg5 startReason:(id)arg6 startOffset:(double)arg7 isIncognitoMode:(_Bool)arg8 streamingRules:(id)arg9 networkConnectivityController:(id)arg10;

@end

