//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "ADLStringListResponder-Protocol.h"

@interface ADLStringListResponderCppProxy : NSObject <ADLStringListResponder>
{
    struct Handle<std::__1::shared_ptr<addlive::StringListResponder>, std::__1::shared_ptr<addlive::StringListResponder>> _cppRefHandle;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)onError:(int)arg1 message:(id)arg2;
- (void)onCompletion:(id)arg1;
- (id)initWithCpp:(const shared_ptr_382e76bc *)arg1;

@end

