//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "SCServerConfigListener-Protocol.h"

@class NSString, SCLogger, SCServerConfig, SOJUBlizzardClientConfig;
@protocol AMPConfigProtocol;

@interface AMPServerConfigRepo : NSObject <SCServerConfigListener>
{
    SCServerConfig *_serverConfig;
    SCLogger *_scLogger;
    NSString *_clientConfigJsonString;
    id <AMPConfigProtocol> _clientConfig;
    id <AMPConfigProtocol> _staticConfig;
    SOJUBlizzardClientConfig *_sojuConfig;
}

@property(retain, nonatomic) SOJUBlizzardClientConfig *sojuConfig; // @synthesize sojuConfig=_sojuConfig;
@property(retain, nonatomic) id <AMPConfigProtocol> staticConfig; // @synthesize staticConfig=_staticConfig;
@property(retain, nonatomic) id <AMPConfigProtocol> clientConfig; // @synthesize clientConfig=_clientConfig;
@property(retain, nonatomic) NSString *clientConfigJsonString; // @synthesize clientConfigJsonString=_clientConfigJsonString;
@property(retain, nonatomic) SCLogger *scLogger; // @synthesize scLogger=_scLogger;
- (void).cxx_destruct;
- (void)_logConfigChangeEvent:(id)arg1 newVersion:(id)arg2;
- (void)_updateConfigAndLogConfigChangeEvent:(id)arg1;
- (id)_getValidConfig:(id)arg1 fallbackConfig:(id)arg2;
- (void)serverConfigDidChange:(id)arg1;
- (void)updateClientConfig:(id)arg1;
- (id)getClientConfig;
- (id)initWithServerConfig:(id)arg1 scLogger:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

