//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "BCOVComponent-Protocol.h"
#import "BCOVComponentIdentity-Protocol.h"

@class NSString;
@protocol BCOVComponentIdentity;

@interface BCOVSSComponent : NSObject <BCOVComponent, BCOVComponentIdentity>
{
}

- (void)bcov_setComponentContext:(id)arg1;
@property(readonly, nonatomic) id <BCOVComponentIdentity> bcov_componentIdentity;
@property(readonly, nonatomic) NSString *versionIdentifier;
@property(readonly, nonatomic) Class componentClass;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

