//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GenericSettingsViewController.h"

#import "SCDatePickerDelegate-Protocol.h"
#import "SCLayoutAccessoryTableViewCellDelegate-Protocol.h"
#import "SCTextViewDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSString, SCButton, SCDatePicker, SCTextView, SCUserSession, UILabel, UISwitch, UITableView;

@interface BirthdaySettingsViewController : GenericSettingsViewController <SCTextViewDelegate, SCDatePickerDelegate, SCLayoutAccessoryTableViewCellDelegate, UITableViewDataSource, UITableViewDelegate>
{
    SCTextView *_birthdayTextView;
    SCDatePicker *_birthdayPickerView;
    SCButton *_continueButton;
    UILabel *_upperInfo;
    UITableView *_tableView;
    UISwitch *_partySwitch;
    _Bool _shouldFlipSwitchOnDateChange;
    SCUserSession *_userSession;
}

- (void).cxx_destruct;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)presentManyUpdatesAlert;
- (id)getDefaultBirthday;
- (void)_updateBirthdayForOver13;
- (void)handleOverThirteen;
- (void)sendToAccountsWithToken:(id)arg1;
- (void)handleUnderThirteen;
- (id)getReportUnderThirteenUrl;
- (_Bool)isSameBirthday;
- (_Bool)isBirthdaySet;
- (void)setIsWorking:(_Bool)arg1;
- (void)continueButtonTapped;
- (id)birthdayPickerDate;
- (void)dateDidChange;
- (void)dateWheelIsSpinning;
- (void)updateBirthday;
- (_Bool)textViewShouldBeginEditing:(id)arg1;
- (void)textViewDidChange:(id)arg1;
- (id)getTitle;
- (void)setContinueButtonTitle:(id)arg1;
- (void)initContinueButton;
- (void)initBirthdayPicker;
- (void)layoutAccessoryTableViewCell:(id)arg1 textLabel:(id)arg2 attributionLabel:(id)arg3;
- (struct CGRect)layoutAccessoryTableViewCell:(id)arg1 frameForAccessoryView:(id)arg2;
- (void)switchChanged:(id)arg1;
- (id)partyCell;
- (void)initParty;
- (void)initBirthdayTextView;
- (void)loadView;
- (id)getPageViewName;
- (id)initWithUserSession:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

