//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class MPSCNNConvolution;
@protocol MTLDevice, MTLLibrary;

@interface DeconvolutionLayer : NSObject
{
    id <MTLDevice> _device;
    id <MTLLibrary> _library;
    unsigned long long _inputChannel;
    unsigned long long _outputChannel;
    unsigned long long _kernelWidth;
    unsigned long long _kernelHeight;
    unsigned long long _strideX;
    unsigned long long _strideY;
    MPSCNNConvolution *_conv;
}

@property(retain, nonatomic) MPSCNNConvolution *conv; // @synthesize conv=_conv;
@property(nonatomic) unsigned long long strideY; // @synthesize strideY=_strideY;
@property(nonatomic) unsigned long long strideX; // @synthesize strideX=_strideX;
@property(nonatomic) unsigned long long kernelHeight; // @synthesize kernelHeight=_kernelHeight;
@property(nonatomic) unsigned long long kernelWidth; // @synthesize kernelWidth=_kernelWidth;
@property(nonatomic) unsigned long long outputChannel; // @synthesize outputChannel=_outputChannel;
@property(nonatomic) unsigned long long inputChannel; // @synthesize inputChannel=_inputChannel;
@property(nonatomic) __weak id <MTLLibrary> library; // @synthesize library=_library;
@property(nonatomic) __weak id <MTLDevice> device; // @synthesize device=_device;
- (void).cxx_destruct;
- (void)encodeToCommandBuffer:(id)arg1 sourceImage:(id)arg2 destinationImage:(id)arg3;
- (id)initWithDevice:(id)arg1 library:(id)arg2 inputChannel:(unsigned long long)arg3 outputChannel:(unsigned long long)arg4 kernelWidth:(unsigned long long)arg5 kernelHeight:(unsigned long long)arg6 activation:(id)arg7 strideX:(unsigned long long)arg8 strideY:(unsigned long long)arg9 weights:(float *)arg10 bias:(float *)arg11;

@end

