//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPBMessage.h"

@interface MLBImuStreamRequest : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(nonatomic) _Bool bmi160Int2High; // @dynamic bmi160Int2High;
@property(nonatomic) unsigned int durationSec; // @dynamic durationSec;
@property(nonatomic) _Bool hasBmi160Int2High; // @dynamic hasBmi160Int2High;
@property(nonatomic) _Bool hasDurationSec; // @dynamic hasDurationSec;
@property(nonatomic) _Bool hasReadFifo; // @dynamic hasReadFifo;
@property(nonatomic) _Bool readFifo; // @dynamic readFifo;

@end

