//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSArray.h>

@interface NSArray (BCOVCollectionTransforms)
- (id)bcov_reduceInitial:(id)arg1 combine:(CDUnknownBlockType)arg2 reverse:(_Bool)arg3;
- (id)bcov_reduceInitial:(id)arg1 combine:(CDUnknownBlockType)arg2;
- (id)bcov_map:(CDUnknownBlockType)arg1 nilFilter:(_Bool)arg2;
- (id)bcov_map:(CDUnknownBlockType)arg1;
@end

