//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString;

@interface ResolvedAdDebuggingInfo : NSObject
{
    NSString *_lineItemId;
    NSString *_adId;
}

@property(copy, nonatomic) NSString *adId; // @synthesize adId=_adId;
@property(copy, nonatomic) NSString *lineItemId; // @synthesize lineItemId=_lineItemId;
- (void).cxx_destruct;

@end

