//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCAUserTrackedEvent.h"

#import "MapSerializable-Protocol.h"
#import "NSCopying-Protocol.h"

@class NSNumber;

@interface SCAAppDatabaseLoad : SCAUserTrackedEvent <MapSerializable, NSCopying>
{
    NSNumber *userLoadTimeMs;
    NSNumber *conversationTableMs;
    NSNumber *friendStorySnapTableMs;
    NSNumber *friendsTableMs;
    NSNumber *mediaCacheTableMs;
    NSNumber *myPostedStorySnapTableMs;
}

- (void).cxx_destruct;
- (id)asDictionary;
- (long long)getMyPostedStorySnapTableMs;
- (void)setMyPostedStorySnapTableMs:(long long)arg1;
- (long long)getMediaCacheTableMs;
- (void)setMediaCacheTableMs:(long long)arg1;
- (long long)getFriendsTableMs;
- (void)setFriendsTableMs:(long long)arg1;
- (long long)getFriendStorySnapTableMs;
- (void)setFriendStorySnapTableMs:(long long)arg1;
- (long long)getConversationTableMs;
- (void)setConversationTableMs:(long long)arg1;
- (long long)getUserLoadTimeMs;
- (void)setUserLoadTimeMs:(long long)arg1;
- (double)getSamplingRate;
- (long long)getEventQoS;
- (id)getEventName;
- (id)init;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

