//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCAUserTrackedEvent.h"

#import "MapSerializable-Protocol.h"
#import "NSCopying-Protocol.h"

@class NSNumber, NSString;

@interface SCACameraSnapCreateDelay : SCAUserTrackedEvent <MapSerializable, NSCopying>
{
    NSNumber *latencyMillis;
    NSNumber *contentDurationMillis;
    long long lowLightStatus;
    long long mediaType;
    NSString *analyticsVersion;
    NSString *powerMode;
    NSString *filterLensId;
    NSString *captureSessionId;
    NSString *cameraApi;
    NSString *cameraPosition;
    NSString *cameraOpenSource;
    NSString *cameraLevel;
    NSString *splits;
    NSString *startType;
    NSString *startSubType;
}

- (void).cxx_destruct;
- (id)asDictionary;
- (id)getStartSubType;
- (void)setStartSubType:(id)arg1;
- (id)getStartType;
- (void)setStartType:(id)arg1;
- (id)getSplits;
- (void)setSplits:(id)arg1;
- (id)getCameraLevel;
- (void)setCameraLevel:(id)arg1;
- (id)getCameraOpenSource;
- (void)setCameraOpenSource:(id)arg1;
- (id)getCameraPosition;
- (void)setCameraPosition:(id)arg1;
- (id)getCameraApi;
- (void)setCameraApi:(id)arg1;
- (id)getCaptureSessionId;
- (void)setCaptureSessionId:(id)arg1;
- (id)getFilterLensId;
- (void)setFilterLensId:(id)arg1;
- (id)getPowerMode;
- (void)setPowerMode:(id)arg1;
- (id)getAnalyticsVersion;
- (void)setAnalyticsVersion:(id)arg1;
- (long long)getMediaType;
- (void)setMediaType:(long long)arg1;
- (long long)getLowLightStatus;
- (void)setLowLightStatus:(long long)arg1;
- (long long)getContentDurationMillis;
- (void)setContentDurationMillis:(long long)arg1;
- (long long)getLatencyMillis;
- (void)setLatencyMillis:(long long)arg1;
- (double)getSamplingRate;
- (long long)getEventQoS;
- (id)getEventName;
- (id)init;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

