//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCAUserTrackedEvent.h"

#import "MapSerializable-Protocol.h"
#import "NSCopying-Protocol.h"

@class NSNumber, NSString;

@interface SCAChatPageView : SCAUserTrackedEvent <MapSerializable, NSCopying>
{
    NSNumber *viewTimeSec;
    NSNumber *cellViewPosition;
    long long storyViewType;
    long long friendshipStatus;
    long long correspondentType;
    NSString *subpageName;
    NSString *recipientId;
    NSString *mischiefId;
    NSString *correspondentId;
    NSString *rankingModelId;
    NSString *rankingId;
    NSString *serverRankingId;
    NSString *ghost_correspondent_id;
    NSString *ghost_recipient_id;
}

- (void).cxx_destruct;
- (id)asDictionary;
- (id)getGhost_recipient_id;
- (void)setGhost_recipient_id:(id)arg1;
- (id)getGhost_correspondent_id;
- (void)setGhost_correspondent_id:(id)arg1;
- (id)getServerRankingId;
- (void)setServerRankingId:(id)arg1;
- (id)getRankingId;
- (void)setRankingId:(id)arg1;
- (id)getRankingModelId;
- (void)setRankingModelId:(id)arg1;
- (id)getCorrespondentId;
- (void)setCorrespondentId:(id)arg1;
- (id)getMischiefId;
- (void)setMischiefId:(id)arg1;
- (id)getRecipientId;
- (void)setRecipientId:(id)arg1;
- (id)getSubpageName;
- (void)setSubpageName:(id)arg1;
- (long long)getCorrespondentType;
- (void)setCorrespondentType:(long long)arg1;
- (long long)getFriendshipStatus;
- (void)setFriendshipStatus:(long long)arg1;
- (long long)getStoryViewType;
- (void)setStoryViewType:(long long)arg1;
- (long long)getCellViewPosition;
- (void)setCellViewPosition:(long long)arg1;
- (double)getViewTimeSec;
- (void)setViewTimeSec:(double)arg1;
- (double)getSamplingRate;
- (long long)getEventQoS;
- (id)getEventName;
- (id)init;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

