//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSMutableArray, SCAdsApplication, SCAdsDevice, SCAdsMixerInfo, SCAdsNetwork, SCAdsPreferences, SCAdsUser;

@interface SCAdsAdRequest : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) SCAdsApplication *application; // @dynamic application;
@property(retain, nonatomic) SCAdsDevice *device; // @dynamic device;
@property(nonatomic) _Bool hasApplication; // @dynamic hasApplication;
@property(nonatomic) _Bool hasDevice; // @dynamic hasDevice;
@property(nonatomic) _Bool hasMixerInfo; // @dynamic hasMixerInfo;
@property(nonatomic) _Bool hasNetwork; // @dynamic hasNetwork;
@property(nonatomic) _Bool hasPreferences; // @dynamic hasPreferences;
@property(nonatomic) _Bool hasUser; // @dynamic hasUser;
@property(retain, nonatomic) NSMutableArray *inventoryRequestsArray; // @dynamic inventoryRequestsArray;
@property(readonly, nonatomic) unsigned long long inventoryRequestsArray_Count; // @dynamic inventoryRequestsArray_Count;
@property(nonatomic) _Bool isDebug; // @dynamic isDebug;
@property(retain, nonatomic) SCAdsMixerInfo *mixerInfo; // @dynamic mixerInfo;
@property(retain, nonatomic) SCAdsNetwork *network; // @dynamic network;
@property(retain, nonatomic) SCAdsPreferences *preferences; // @dynamic preferences;
@property(retain, nonatomic) NSMutableArray *storiesArray; // @dynamic storiesArray;
@property(readonly, nonatomic) unsigned long long storiesArray_Count; // @dynamic storiesArray_Count;
@property(retain, nonatomic) SCAdsUser *user; // @dynamic user;

@end

