//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCALensSwipeBase.h"

#import "MapSerializable-Protocol.h"
#import "NSCopying-Protocol.h"

@class NSNumber, NSString;

@interface SCAFilterLensSwipe : SCALensSwipeBase <MapSerializable, NSCopying>
{
    NSNumber *lensOptionSwipeCount;
    NSNumber *camera;
    NSNumber *deviceScore;
    NSNumber *withAttachmentOpen;
    NSNumber *applyDelaySec;
    NSNumber *avgFps;
    long long iapStatus;
    long long lensSource;
    long long attachmentType;
    NSString *filterLensId;
}

- (void).cxx_destruct;
- (id)asDictionary;
- (id)getFilterLensId;
- (void)setFilterLensId:(id)arg1;
- (long long)getAttachmentType;
- (void)setAttachmentType:(long long)arg1;
- (long long)getLensSource;
- (void)setLensSource:(long long)arg1;
- (long long)getIapStatus;
- (void)setIapStatus:(long long)arg1;
- (double)getAvgFps;
- (void)setAvgFps:(double)arg1;
- (double)getApplyDelaySec;
- (void)setApplyDelaySec:(double)arg1;
- (_Bool)getWithAttachmentOpen;
- (void)setWithAttachmentOpen:(_Bool)arg1;
- (long long)getDeviceScore;
- (void)setDeviceScore:(long long)arg1;
- (long long)getCamera;
- (void)setCamera:(long long)arg1;
- (long long)getLensOptionSwipeCount;
- (void)setLensOptionSwipeCount:(long long)arg1;
- (double)getSamplingRate;
- (long long)getEventQoS;
- (id)getEventName;
- (id)init;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

