//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCAUserTrackedEvent.h"

#import "MapSerializable-Protocol.h"
#import "NSCopying-Protocol.h"

@class NSNumber, NSString;

@interface SCAFriendFeedRankingSessionView : SCAUserTrackedEvent <MapSerializable, NSCopying>
{
    NSNumber *cellViewCount;
    long long refreshReason;
    NSString *subpageName;
    NSString *rankingModelId;
    NSString *rankingId;
    NSString *serverRankingId;
}

- (void).cxx_destruct;
- (id)asDictionary;
- (id)getServerRankingId;
- (void)setServerRankingId:(id)arg1;
- (id)getRankingId;
- (void)setRankingId:(id)arg1;
- (id)getRankingModelId;
- (void)setRankingModelId:(id)arg1;
- (id)getSubpageName;
- (void)setSubpageName:(id)arg1;
- (long long)getRefreshReason;
- (void)setRefreshReason:(long long)arg1;
- (long long)getCellViewCount;
- (void)setCellViewCount:(long long)arg1;
- (double)getSamplingRate;
- (long long)getEventQoS;
- (id)getEventName;
- (id)init;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

