//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCAUserTrackedEvent.h"

#import "MapSerializable-Protocol.h"
#import "NSCopying-Protocol.h"

@class NSNumber, NSString;

@interface SCAGroupStoryDelete : SCAUserTrackedEvent <MapSerializable, NSCopying>
{
    NSNumber *snapCount;
    NSNumber *friendSnapCount;
    NSNumber *mySnapCount;
    long long leaveReason;
    long long storyTypeSpecific;
    NSString *groupStoryId;
}

- (void).cxx_destruct;
- (id)asDictionary;
- (id)getGroupStoryId;
- (void)setGroupStoryId:(id)arg1;
- (long long)getStoryTypeSpecific;
- (void)setStoryTypeSpecific:(long long)arg1;
- (long long)getLeaveReason;
- (void)setLeaveReason:(long long)arg1;
- (long long)getMySnapCount;
- (void)setMySnapCount:(long long)arg1;
- (long long)getFriendSnapCount;
- (void)setFriendSnapCount:(long long)arg1;
- (long long)getSnapCount;
- (void)setSnapCount:(long long)arg1;
- (double)getSamplingRate;
- (long long)getEventQoS;
- (id)getEventName;
- (id)init;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

