//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCAGeofilterOndemandEventBase.h"

#import "MapSerializable-Protocol.h"
#import "NSCopying-Protocol.h"

@class NSString;

@interface SCAGeofilterOndemandDeeplink : SCAGeofilterOndemandEventBase <MapSerializable, NSCopying>
{
    NSString *scCampaign;
    NSString *scSource;
    NSString *scMedium;
    NSString *scContent;
}

- (void).cxx_destruct;
- (id)asDictionary;
- (id)getScContent;
- (void)setScContent:(id)arg1;
- (id)getScMedium;
- (void)setScMedium:(id)arg1;
- (id)getScSource;
- (void)setScSource:(id)arg1;
- (id)getScCampaign;
- (void)setScCampaign:(id)arg1;
- (double)getSamplingRate;
- (long long)getEventQoS;
- (id)getEventName;
- (id)init;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

