//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCAUserTrackedEvent.h"

#import "MapSerializable-Protocol.h"
#import "NSCopying-Protocol.h"

@class NSNumber, NSString;

@interface SCAMapMapClose : SCAUserTrackedEvent <MapSerializable, NSCopying>
{
    NSNumber *mapSessionId;
    NSNumber *viewportFriendCount;
    NSNumber *viewTimeSec;
    NSNumber *mapFriendCount;
    NSNumber *viewportFriendMaxCount;
    NSNumber *viewportFriendAccumCount;
    NSNumber *gameScore;
    NSNumber *viewportGameMarkerMaxCount;
    NSNumber *friendActiveGameCount;
    long long source;
    long long action;
    long long exitEvent;
    NSString *mapPoiViewList;
}

- (void).cxx_destruct;
- (id)asDictionary;
- (id)getMapPoiViewList;
- (void)setMapPoiViewList:(id)arg1;
- (long long)getExitEvent;
- (void)setExitEvent:(long long)arg1;
- (long long)getAction;
- (void)setAction:(long long)arg1;
- (long long)getSource;
- (void)setSource:(long long)arg1;
- (long long)getFriendActiveGameCount;
- (void)setFriendActiveGameCount:(long long)arg1;
- (long long)getViewportGameMarkerMaxCount;
- (void)setViewportGameMarkerMaxCount:(long long)arg1;
- (long long)getGameScore;
- (void)setGameScore:(long long)arg1;
- (long long)getViewportFriendAccumCount;
- (void)setViewportFriendAccumCount:(long long)arg1;
- (long long)getViewportFriendMaxCount;
- (void)setViewportFriendMaxCount:(long long)arg1;
- (long long)getMapFriendCount;
- (void)setMapFriendCount:(long long)arg1;
- (double)getViewTimeSec;
- (void)setViewTimeSec:(double)arg1;
- (long long)getViewportFriendCount;
- (void)setViewportFriendCount:(long long)arg1;
- (long long)getMapSessionId;
- (void)setMapSessionId:(long long)arg1;
- (double)getSamplingRate;
- (long long)getEventQoS;
- (id)getEventName;
- (id)init;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

