//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCBaseAPIClient.h"

@class NSDateFormatter, NSURL, SCQueuePerformer;

@interface SCAPIClient : SCBaseAPIClient
{
    NSURL *_defaultBaseURL;
    SCQueuePerformer *_reachabilityQueuePerformer;
    long long _prevReachabilityStatus;
    double _loggingRate;
    NSDateFormatter *_dateFormatter;
}

+ (void)apiClientDidFinishRequest:(id)arg1 response:(id)arg2 parameters:(id)arg3;
+ (void)removeListener:(id)arg1;
+ (void)addListener:(id)arg1;
+ (id)getConnectionType;
+ (id)getCarrierMNC;
+ (id)getCarrierMCC;
+ (id)getCarrierName;
+ (_Bool)isDevSnapConnect;
+ (_Bool)isDevAuthService;
+ (_Bool)isDevSnapchat;
+ (id)defaultSnapConnectUrl;
+ (id)defaultAuthServiceUrl;
+ (id)defaultUrl;
+ (id)updateSharedSnapConnectClientWithUrl:(id)arg1;
+ (id)updateSharedAuthServiceClientWithUrl:(id)arg1;
+ (id)updateSharedClientWithUrl:(id)arg1;
+ (id)sharedSnapConnectClient;
+ (id)sharedAuthServiceClient;
+ (id)sharedClient;
+ (void)initialize;
+ (void)alertView:(id)arg1 didDismissWithButtonIndex:(long long)arg2;
+ (void)showAlertAndWaitForDismissalWithUrl:(id)arg1;
@property(retain, nonatomic) NSDateFormatter *dateFormatter; // @synthesize dateFormatter=_dateFormatter;
@property(readonly, nonatomic) double loggingRate; // @synthesize loggingRate=_loggingRate;
@property long long prevReachabilityStatus; // @synthesize prevReachabilityStatus=_prevReachabilityStatus;
@property(retain, nonatomic) SCQueuePerformer *reachabilityQueuePerformer; // @synthesize reachabilityQueuePerformer=_reachabilityQueuePerformer;
@property(retain, nonatomic) NSURL *defaultBaseURL; // @synthesize defaultBaseURL=_defaultBaseURL;
- (void).cxx_destruct;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)enqueueHTTPRequestOperation:(id)arg1;
- (id)requestWithMethod:(id)arg1 path:(id)arg2 parameters:(id)arg3;
- (id)multipartFormRequestWithMethod:(id)arg1 path:(id)arg2 parameters:(id)arg3 constructingBodyWithBlock:(CDUnknownBlockType)arg4;
- (_Bool)isCustomEndpoint;
- (long long)currentNetworkReachabilityStatusRealTime;
- (long long)getCurrentNetworkReachabilityStatus;
- (_Bool)_shouldLogPayloadGeneration;
- (void)authenticateRequest:(id)arg1 path:(id)arg2 parameters:(id)arg3;
- (id)requestWithMethod:(id)arg1 url:(id)arg2 parameters:(id)arg3 authenticated:(_Bool)arg4;
- (id)initWithBaseURL:(id)arg1;

@end

