//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "SCStateMachineDelegate-Protocol.h"

@class NSDictionary, NSString, SCStateMachine;

@interface SCAppStateMonitor : NSObject <SCStateMachineDelegate>
{
    long long _stateStartTime;
    NSString *_stateTriggeredByNotification;
    NSDictionary *_validTransitions;
    SCStateMachine *_stateMachine;
}

+ (id)sharedInstance;
@property(retain, nonatomic) SCStateMachine *stateMachine; // @synthesize stateMachine=_stateMachine;
- (void).cxx_destruct;
- (void)dealloc;
- (_Bool)_isValidStateTransitionFrom:(id)arg1 to:(id)arg2;
- (void)_handleNotification:(id)arg1;
- (void)handleStateTransitionFrom:(id)arg1 to:(id)arg2;
- (id)init;

@end

