//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCAUserTrackedEvent.h"

#import "MapSerializable-Protocol.h"
#import "NSCopying-Protocol.h"

@class NSNumber, NSString;

@interface SCAStoryInterstitialView : SCAUserTrackedEvent <MapSerializable, NSCopying>
{
    NSNumber *viewTimeSec;
    NSNumber *absoluteStoryIndex;
    NSNumber *relativeStoryIndex;
    long long entryEvent;
    long long exitEvent;
    long long type;
    long long source;
    NSString *posterId;
    NSString *rankingModelId;
    NSString *rankingId;
    NSString *serverRankingId;
    NSString *editionId;
    NSString *ghost_poster_id;
}

- (void).cxx_destruct;
- (id)asDictionary;
- (id)getGhost_poster_id;
- (void)setGhost_poster_id:(id)arg1;
- (id)getEditionId;
- (void)setEditionId:(id)arg1;
- (id)getServerRankingId;
- (void)setServerRankingId:(id)arg1;
- (id)getRankingId;
- (void)setRankingId:(id)arg1;
- (id)getRankingModelId;
- (void)setRankingModelId:(id)arg1;
- (id)getPosterId;
- (void)setPosterId:(id)arg1;
- (long long)getSource;
- (void)setSource:(long long)arg1;
- (long long)getType;
- (void)setType:(long long)arg1;
- (long long)getExitEvent;
- (void)setExitEvent:(long long)arg1;
- (long long)getEntryEvent;
- (void)setEntryEvent:(long long)arg1;
- (long long)getRelativeStoryIndex;
- (void)setRelativeStoryIndex:(long long)arg1;
- (long long)getAbsoluteStoryIndex;
- (void)setAbsoluteStoryIndex:(long long)arg1;
- (double)getViewTimeSec;
- (void)setViewTimeSec:(double)arg1;
- (double)getSamplingRate;
- (long long)getEventQoS;
- (id)getEventName;
- (id)init;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

