//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "SCSearchEventListener-Protocol.h"

@class NSDictionary, NSMutableSet, NSString;
@protocol SCPerforming;

@interface SCAttachmentsLogger : NSObject <SCSearchEventListener>
{
    id <SCPerforming> _performer;
    NSDictionary *_samplingRates;
    NSDictionary *_loggingDestination;
    NSMutableSet *_attachmentsClipboardResultsOnScreen;
    NSMutableSet *_attachmentsPreviouslyAttachedResultsOnScreen;
    NSMutableSet *_viewedSnapsWithAttachments;
}

- (void).cxx_destruct;
- (_Bool)_shouldLogSampleForEvent:(id)arg1;
- (id)_getExtraDataForEvent:(id)arg1 identifier:(id)arg2 extraData:(id)arg3;
- (void)didTriggerEventWithEventName:(id)arg1 announcerIdentifier:(id)arg2 extraData:(id)arg3;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

