//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "SCSnapAdsAdPlacement-Protocol.h"

@class NSMutableDictionary, NSString;

@interface SCAutoAdvanceAdsPlacement : NSObject <SCSnapAdsAdPlacement>
{
    NSMutableDictionary *_targetingParams;
    NSString *_inventoryId;
    long long _resolvingStatus;
    NSString *_adUnitId;
    NSString *_adRequestClientId;
    long long _position;
}

@property(readonly, nonatomic) long long position; // @synthesize position=_position;
@property(readonly, copy, nonatomic) NSString *adRequestClientId; // @synthesize adRequestClientId=_adRequestClientId;
@property(readonly, copy, nonatomic) NSString *adUnitId; // @synthesize adUnitId=_adUnitId;
- (void).cxx_destruct;
- (_Bool)isResolving;
- (void)didStopResolvingPlacement;
- (void)didStartResolvingPlacement;
- (id)targetingParams;
- (id)key;
- (void)_copyEntryIfExists:(id)arg1 from:(id)arg2 to:(id)arg3;
- (void)_extractContextualTargeting:(id)arg1;
- (id)initWithRequestId:(id)arg1 position:(long long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

