//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "NSCopying-Protocol.h"
#import "NamedEvent-Protocol.h"

@class NSNumber;

@interface SCAUserTags : NSObject <NamedEvent, NSCopying>
{
    NSNumber *tagCount;
    NSNumber *tagFromCarouselCount;
    NSNumber *regexedStringCount;
}

- (void).cxx_destruct;
- (id)asDictionary;
- (long long)getRegexedStringCount;
- (void)setRegexedStringCount:(long long)arg1;
- (long long)getTagFromCarouselCount;
- (void)setTagFromCarouselCount:(long long)arg1;
- (long long)getTagCount;
- (void)setTagCount:(long long)arg1;
- (double)getSamplingRate;
- (long long)getEventQoS;
- (id)getEventName;
- (id)init;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

