//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSArray, SCAlertViewConfig, SCAlertViewFlow;

@interface SCBaseAlertView : UIView
{
    UIView *_contentView;
    UIView *_separatorView;
    NSArray *_contentItems;
    SCAlertViewConfig *_configuration;
    NSArray *_actions;
    UIView *_accessoryView;
    UIView *_rightAccessoryView;
    double _accessoryViewOverlapRatio;
    SCAlertViewFlow *_alertViewFlow;
    CDUnknownBlockType _dismissHandler;
    struct UIEdgeInsets _rightAccessoryViewInsets;
}

+ (id)alertViewWithTitle:(id)arg1 description:(id)arg2 lensIcon:(id)arg3 actions:(id)arg4 configuration:(CDUnknownBlockType)arg5 dismissHandler:(CDUnknownBlockType)arg6;
+ (unsigned long long)buttonStateWithSubscribeState:(unsigned long long)arg1;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(readonly, copy, nonatomic) CDUnknownBlockType dismissHandler; // @synthesize dismissHandler=_dismissHandler;
@property(nonatomic) __weak SCAlertViewFlow *alertViewFlow; // @synthesize alertViewFlow=_alertViewFlow;
@property(readonly, nonatomic) SCAlertViewConfig *configuration; // @synthesize configuration=_configuration;
@property(nonatomic) double accessoryViewOverlapRatio; // @synthesize accessoryViewOverlapRatio=_accessoryViewOverlapRatio;
@property(nonatomic) struct UIEdgeInsets rightAccessoryViewInsets; // @synthesize rightAccessoryViewInsets=_rightAccessoryViewInsets;
@property(retain, nonatomic) UIView *rightAccessoryView; // @synthesize rightAccessoryView=_rightAccessoryView;
@property(retain, nonatomic) UIView *accessoryView; // @synthesize accessoryView=_accessoryView;
@property(readonly, copy, nonatomic) NSArray *actions; // @synthesize actions=_actions;
@property(readonly, copy, nonatomic) NSArray *contentItems; // @synthesize contentItems=_contentItems;
- (void).cxx_destruct;
- (double)incrementAlertViewSizeHeightForActions:(id)arg1;
- (void)layoutButtons:(id)arg1 contentItems:(id)arg2 contentView:(id)arg3 textButtonPadding:(double)arg4 standardWidth:(double)arg5;
- (struct CGSize)getContentItemSize:(struct CGSize)arg1 contentItemSize:(struct CGSize)arg2 contentItem:(id)arg3;
- (double)getViewSizeWidth;
- (double)getStandardWidth;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
@property(readonly, copy, nonatomic) NSArray *actionViews;
- (_Bool)becomeFirstResponder;
- (id)initWithContentItems:(id)arg1 actions:(id)arg2 configuration:(CDUnknownBlockType)arg3 dismissHandler:(CDUnknownBlockType)arg4;

@end

