//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "SCConnectionClassManagerListener-Protocol.h"
#import "SCNetworkConnectivityListener-Protocol.h"

@class NSDate, NSMutableDictionary, NSString, SCNetworkActivityListenerAnnouncer, SCQueuePerformer;
@protocol OS_dispatch_source, SCFilterBase;

@interface SCBandwidthEstimator : NSObject <SCNetworkConnectivityListener, SCConnectionClassManagerListener>
{
    double _filterCoefficient;
    double _filterUpdateTimeInterval;
    unsigned long long _minimumBytesThresholdInCurrentInterval;
    SCQueuePerformer *_performer;
    unsigned long long _LargeTaskThresholdForcingUpdate;
    NSObject<SCFilterBase> *_downloadFilter;
    NSObject<SCFilterBase> *_uploadFilter;
    unsigned long long _bytesReceivedInCurrentInterval;
    unsigned long long _bytesSentInCurrentInterval;
    NSObject<OS_dispatch_source> *_filterUpdateTimer;
    long long _lastAnnouncedDownloadBandwidth;
    unsigned long long _bytesReceivedInCurrentSession;
    NSMutableDictionary *_bandwidthRecordMap;
    _Bool _isActive;
    long long _downloadBandwidth;
    long long _uploadBandwidth;
    long long _currentDownloadBandwidthClass;
    NSDate *_lastUpdateTime;
    SCNetworkActivityListenerAnnouncer *_networkActivityAnnouncer;
    unsigned long long _numOfLargeDLTasks;
    unsigned long long _numOfLargeULTasks;
}

+ (id)shared;
@property(nonatomic) unsigned long long numOfLargeULTasks; // @synthesize numOfLargeULTasks=_numOfLargeULTasks;
@property(nonatomic) unsigned long long numOfLargeDLTasks; // @synthesize numOfLargeDLTasks=_numOfLargeDLTasks;
@property(retain, nonatomic) SCNetworkActivityListenerAnnouncer *networkActivityAnnouncer; // @synthesize networkActivityAnnouncer=_networkActivityAnnouncer;
@property(readonly, nonatomic) NSDate *lastUpdateTime; // @synthesize lastUpdateTime=_lastUpdateTime;
@property long long currentDownloadBandwidthClass; // @synthesize currentDownloadBandwidthClass=_currentDownloadBandwidthClass;
@property(nonatomic) _Bool isActive; // @synthesize isActive=_isActive;
@property long long uploadBandwidth; // @synthesize uploadBandwidth=_uploadBandwidth;
@property long long downloadBandwidth; // @synthesize downloadBandwidth=_downloadBandwidth;
- (void).cxx_destruct;
- (void)finishRecordBandwidthWithRequestKey:(id)arg1;
- (void)startRecordBandwidth:(id)arg1 withMediaType:(id)arg2;
- (void)downloadBandwidthAnalyticsDictionaryWithCompletion:(CDUnknownBlockType)arg1;
- (void)uploadBandwidthAnalyticsDictionaryWithCompletion:(CDUnknownBlockType)arg1;
- (double)timeElaspedSinceLastUpdateInSeconds;
- (id)currentBandwidthClassAsString;
- (void)didSendBytes:(unsigned long long)arg1;
- (void)didReceiveBytes:(unsigned long long)arg1;
- (void)postDownloadBandwidthChangedNotificationIfNeeded;
- (void)_updateFilter;
- (id)createSessionTimerWithInterval:(double)arg1 queue:(id)arg2 block:(CDUnknownBlockType)arg3;
- (void)_removeFiltering;
- (void)_setUpFiltering;
- (void)connectionClassDidChange:(id)arg1;
- (void)networkConnectivityStatusDidChange:(long long)arg1;
- (void)_setUpConnectionClassObservation;
- (void)_setUpNetworkAndAppStateObservation;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

