//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GenericSettingsViewController.h"

#import "SCBitmojiDratiniManagerListener-Protocol.h"
#import "SCBitmojiSelfieCollectionSourceDelegate-Protocol.h"
#import "SCHeaderDelegate-Protocol.h"

@class NSString, SCBitmojiSelfieCollectionSource, SCBitmojiSelfieDoneButton, SCUserSession, UICollectionView;

@interface SCBitmojiSelfieViewController : GenericSettingsViewController <SCBitmojiSelfieCollectionSourceDelegate, SCBitmojiDratiniManagerListener, SCHeaderDelegate>
{
    SCUserSession *_userSession;
    unsigned long long _page;
    UICollectionView *_selfieCollectionView;
    SCBitmojiSelfieCollectionSource *_selfieCollectionSource;
    _Bool _hasUnsavedChange;
    SCBitmojiSelfieDoneButton *_doneButton;
}

@property(retain, nonatomic) SCBitmojiSelfieDoneButton *doneButton; // @synthesize doneButton=_doneButton;
- (void).cxx_destruct;
- (void)_refreshSelfieIds;
- (void)_refreshView;
- (void)_didPressDoneButton;
- (void)leftButtonPressed;
- (void)selfiePackDidChange;
- (void)didSelectSelfie:(id)arg1 collectionSource:(id)arg2;
- (id)getTitle;
- (void)dealloc;
- (void)viewDidLoad;
- (void)loadView;
- (id)initWithUserSession:(id)arg1 page:(unsigned long long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

