//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "SCCaptionResourceProviderDelegate-Protocol.h"
#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegate-Protocol.h"
#import "UICollectionViewDelegateFlowLayout-Protocol.h"

@class NSArray, NSIndexPath, NSString, SCBitmojiDratiniManager, SCCaptionCarouselView, SCCaptionStyleResourceProvider, SCQueuePerformer, SCSortableRecipientFilter;

@interface SCCaptionCarouselController : NSObject <UICollectionViewDataSource, UICollectionViewDelegate, SCCaptionResourceProviderDelegate, UICollectionViewDelegateFlowLayout>
{
    NSArray *_friends;
    NSArray *_captionStyles;
    long long _memoriesCarouselItemsCount;
    SCCaptionStyleResourceProvider *_resourceProvider;
    SCBitmojiDratiniManager *_bitmojiDratiniManager;
    unsigned long long _carouselState;
    SCSortableRecipientFilter *_friendsFilter;
    _Bool _shouldEnableUserTaggingButton;
    NSIndexPath *_selectedIndexPath;
    SCQueuePerformer *_performer;
    SCCaptionCarouselView *_carouselView;
    unsigned long long _carouselMode;
}

@property unsigned long long carouselMode; // @synthesize carouselMode=_carouselMode;
@property(retain) SCCaptionCarouselView *carouselView; // @synthesize carouselView=_carouselView;
- (void).cxx_destruct;
- (void)dealloc;
- (id)_constructDefaultFriendList;
- (void)switchToOrUpdateUserTaggingWithName:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)switchToStyleMode;
- (void)_setupUserTagging;
- (void)finishToUpdateAllStyles;
- (id)selectFriendFromGestrue:(id)arg1;
- (void)styleIsReadyToUse:(id)arg1 index:(long long)arg2;
- (void)metadataIsUpdated:(long long)arg1;
- (void)updateCaptionStylesFromMemoriesWithSet:(id)arg1;
- (unsigned long long)_indexOfCarouselItem:(id)arg1 styleArray:(id)arg2;
- (void)setAndScrollToSelectedItemWithIndex:(long long)arg1;
- (void)setAndScrollToSelectedItemWithCaptionStyle:(id)arg1;
- (id)_constructDefaultStylesAndUpdate;
- (_Bool)collectionView:(id)arg1 shouldHighlightItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (id)selectedCaptionStyle;
- (id)selectStyleFromGesture:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 styleResourceDataProvider:(id)arg2 bitmojiDratinManager:(id)arg3 shouldEnableUserTaggingButton:(_Bool)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

