//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface SCCaptureWorker : NSObject
{
}

+ (void)updateLensesFieldOfViewTracking:(id)arg1;
+ (void)configBlackCameraDetectorWithCaptureResource:(id)arg1;
+ (void)turnARSessionOn:(id)arg1;
+ (void)clearARKitData:(id)arg1;
+ (void)turnARSessionOff:(id)arg1;
+ (_Bool)canRunARSession:(id)arg1;
+ (CDStruct_4565c1ff)activeSession:(id)arg1;
+ (void)cancelRecordingWithCaptureResource:(id)arg1;
+ (void)stopRecordingWithCaptureResource:(id)arg1;
+ (void)startRecordingWithCaptureResource:(id)arg1 outputSettings:(id)arg2 maxDuration:(double)arg3 fileURL:(id)arg4 captureSessionID:(id)arg5 completionHandler:(CDUnknownBlockType)arg6;
+ (void)_captureStillImageAsynchronouslyWithCaptureResource:(id)arg1 aspectRatio:(double)arg2 captureSessionID:(id)arg3 shouldCaptureFromVideo:(_Bool)arg4 completionHandler:(CDUnknownBlockType)arg5;
+ (void)captureStillImageWithCaptureResource:(id)arg1 aspectRatio:(double)arg2 captureSessionID:(id)arg3 shouldCaptureFromVideo:(_Bool)arg4 completionHandler:(CDUnknownBlockType)arg5 context:(id)arg6;
+ (void)softwareZoomWithDevice:(id)arg1 resource:(id)arg2;
+ (void)destroyLivenessConsistencyTimer:(id)arg1;
+ (void)setupLivenessConsistencyTimerIfForeground:(id)arg1;
+ (void)startStreaming:(id)arg1;
+ (void)redoVideoPreviewLayer:(id)arg1;
+ (void)makeVideoPreviewLayer:(id)arg1;
+ (void)setupVideoPreviewLayer:(id)arg1;
+ (_Bool)stopRunningWithCaptureResource:(id)arg1 token:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
+ (void)startRunningWithCaptureResource:(id)arg1 token:(id)arg2 completionHandler:(CDUnknownBlockType)arg3;
+ (void)configImageCapturerWithCaptureResource:(id)arg1;
+ (void)configVideoCapturerWithCaptureResource:(id)arg1;
+ (void)configVideoScannerWithCaptureResource:(id)arg1;
+ (void)configVideoDataSourceWithCaptureResource:(id)arg1 devicePosition:(unsigned long long)arg2;
+ (void)configDeviceCapacityAnalyzerWithCaptureResource:(id)arg1;
+ (void)configAVCaptureSessionWithCaptureResource:(id)arg1;
+ (void)configARSessionWithCaptureResource:(id)arg1;
+ (void)configLensesProcessorWithCaptureResource:(id)arg1;
+ (void)setupCapturePreviewLayerController;
+ (void)setupWithCaptureResource:(id)arg1 devicePosition:(unsigned long long)arg2;
+ (id)generateCaptureResource;

@end

