//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "SCCardLinkingDelegate-Protocol.h"
#import "SCSnapCashBlockerResolverV2-Protocol.h"

@class NSNumber, NSString, SCCardLinkingViewController, SCPayment, SCPaymentBlocker;
@protocol SCSnapCashBlockerResolutionResultDelegateV2;

@interface SCCardLinkingBlockerResolver : NSObject <SCSnapCashBlockerResolverV2, SCCardLinkingDelegate>
{
    SCPaymentBlocker *_blocker;
    SCPayment *_payment;
    SCCardLinkingViewController *_viewController;
    NSNumber *_cardLinkResult;
    id <SCSnapCashBlockerResolutionResultDelegateV2> _resultDelegate;
}

@property(nonatomic) __weak id <SCSnapCashBlockerResolutionResultDelegateV2> resultDelegate; // @synthesize resultDelegate=_resultDelegate;
@property(retain, nonatomic) NSNumber *cardLinkResult; // @synthesize cardLinkResult=_cardLinkResult;
@property(retain, nonatomic) SCCardLinkingViewController *viewController; // @synthesize viewController=_viewController;
@property(retain, nonatomic) SCPayment *payment; // @synthesize payment=_payment;
@property(retain, nonatomic) SCPaymentBlocker *blocker; // @synthesize blocker=_blocker;
- (void).cxx_destruct;
- (void)cardLinkingCancelled;
- (void)cardLinkingSuccessful;
- (long long)blockerType;
- (void)resolveBlockerWithDelegate:(id)arg1;
- (id)getViewController;
- (id)initWithBlocker:(id)arg1 payment:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

