//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "NSCopying-Protocol.h"

@class NSString, SCSearchActionModel, UIImage;

@interface SCCheetahSendToHeaderViewModel : NSObject <NSCopying>
{
    NSString *_titleText;
    NSString *_subTitleText;
    NSString *_buttonText;
    NSString *_buttonAccessibilityIdentifier;
    UIImage *_buttonIconImage;
    SCSearchActionModel *_actionModel;
}

@property(readonly, copy, nonatomic) SCSearchActionModel *actionModel; // @synthesize actionModel=_actionModel;
@property(readonly, copy, nonatomic) UIImage *buttonIconImage; // @synthesize buttonIconImage=_buttonIconImage;
@property(readonly, copy, nonatomic) NSString *buttonAccessibilityIdentifier; // @synthesize buttonAccessibilityIdentifier=_buttonAccessibilityIdentifier;
@property(readonly, copy, nonatomic) NSString *buttonText; // @synthesize buttonText=_buttonText;
@property(readonly, copy, nonatomic) NSString *subTitleText; // @synthesize subTitleText=_subTitleText;
@property(readonly, copy, nonatomic) NSString *titleText; // @synthesize titleText=_titleText;
- (void).cxx_destruct;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)description;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithTitleText:(id)arg1 subTitleText:(id)arg2 buttonText:(id)arg3 buttonAccessibilityIdentifier:(id)arg4 buttonIconImage:(id)arg5 actionModel:(id)arg6;

@end

