//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "SCChatInputAccessory-Protocol.h"
#import "SCTimeProfilable-Protocol.h"
#import "SendSnapNavigationControllerDelegate-Protocol.h"
#import "UINavigationControllerDelegate-Protocol.h"

@class NSString, SCUserSession, UIButton, UINavigationController, UIView, UIViewController;
@protocol SCChatInputProvider, SCChatInputRemixAccessoryDelegate;

@interface SCChatInputRemixAccessory : NSObject <SendSnapNavigationControllerDelegate, UINavigationControllerDelegate, SCTimeProfilable, SCChatInputAccessory>
{
    id <SCChatInputProvider> _inputProvider;
    SCUserSession *_userSession;
    UIViewController *_parentViewController;
    UIView *_miniatureView;
    UIButton *_snapButton;
    UINavigationController *_navigationController;
    _Bool _fullscreenImageUsed;
    id <SCChatInputRemixAccessoryDelegate> _delegate;
}

+ (int)context;
@property(nonatomic) __weak id <SCChatInputRemixAccessoryDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool fullscreenImageUsed; // @synthesize fullscreenImageUsed=_fullscreenImageUsed;
- (void).cxx_destruct;
- (id)_navigationController;
- (void)_dismissPreviewIfPresented;
- (void)didComeFromCameraWithoutSendingSnap;
- (void)didPostStory;
- (void)didSendToGallery;
- (void)didSendChatMessage;
- (void)didSendSnaps:(id)arg1;
- (void)_didSendSnapOrChatMessage;
- (void)didCancelFromPreview:(id)arg1;
- (void)_didPressSnapButton:(id)arg1;
- (void)accessoryPressed;
- (id)_previewConfigurationForImage:(id)arg1 rotationEnabled:(_Bool)arg2 savingDisabled:(_Bool)arg3;
- (id)_previewConfigurationForVideoURL:(id)arg1 videoSize:(struct CGSize)arg2 urlAsset:(id)arg3;
- (void)_presentPreviewController:(id)arg1;
- (void)_presentVideoAVUrlAsset:(id)arg1 videoURL:(id)arg2;
- (void)presentPreviewForVideo:(id)arg1;
- (void)presentPreviewforImage:(id)arg1;
- (id)_replyParametersForRemix;
- (void)presentPreviewForStory:(id)arg1;
- (void)resetMiniatureViewImageForNormalControlState;
- (id)miniatureView;
- (id)initWithInputProvider:(id)arg1 userSession:(id)arg2 parentViewController:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

