//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "SCSearchQueryCoordinating-Protocol.h"

@class NSMutableArray, NSString, SCCheetahStoriesDataStore, SCCheetahStoriesGroupStoriesCombiner, SCCheetahStoriesInteractionHistoryModifier, SCExperimentManager, SCQueuePerformer, SCSSMStoriesRequest, SCSearchNavigationCoordinator, SCSearchQuery, SCSessionRequestManager, SCUserSession;

@interface SCCheetahStoriesQueryCoordinator : NSObject <SCSearchQueryCoordinating>
{
    SCUserSession *_userSession;
    SCSessionRequestManager *_requestManager;
    SCExperimentManager *_experimentManager;
    SCCheetahStoriesDataStore *_storiesDataStore;
    SCCheetahStoriesGroupStoriesCombiner *_groupStoriesCombiner;
    SCCheetahStoriesInteractionHistoryModifier *_interactionHistoryModifier;
    NSMutableArray *_queryRetryTimers;
    SCQueuePerformer *_performer;
    _Bool _isLoading;
    SCSearchQuery *_currentQuery;
    SCSearchNavigationCoordinator *_navigationCoordinator;
    NSString *_currentQueryDebugHtml;
    SCSSMStoriesRequest *_lastStoriesRequest;
}

+ (id)announcerIdentifier;
@property(readonly, copy, nonatomic) SCSSMStoriesRequest *lastStoriesRequest; // @synthesize lastStoriesRequest=_lastStoriesRequest;
@property(readonly, copy, nonatomic) NSString *currentQueryDebugHtml; // @synthesize currentQueryDebugHtml=_currentQueryDebugHtml;
@property(nonatomic) __weak SCSearchNavigationCoordinator *navigationCoordinator; // @synthesize navigationCoordinator=_navigationCoordinator;
@property(copy, nonatomic) SCSearchQuery *currentQuery; // @synthesize currentQuery=_currentQuery;
@property(readonly, nonatomic) _Bool isLoading; // @synthesize isLoading=_isLoading;
- (void).cxx_destruct;
- (id)_viewedGroupStoryIds;
- (void)_updateWithQuery:(id)arg1 resultState:(long long)arg2 updatingBlock:(CDUnknownBlockType)arg3;
- (void)_handleStoriesResponse:(id)arg1 query:(id)arg2 updatingBlock:(CDUnknownBlockType)arg3;
- (void)_updateForResponseFromQuery:(id)arg1 updatingBlock:(CDUnknownBlockType)arg2 response:(id)arg3 data:(id)arg4 error:(id)arg5 retryTimer:(id)arg6;
- (void)_sendQueryBlock:(id)arg1 snapToken:(id)arg2 updatingBlock:(CDUnknownBlockType)arg3 retryTimer:(id)arg4 tapHistory:(id)arg5 interactionsHistory:(id)arg6 pageSessionId:(id)arg7;
- (void)_sendQuery:(id)arg1 snapToken:(id)arg2 tapHistory:(id)arg3 interactionsHistory:(id)arg4 pageSessionId:(id)arg5 updatingBlock:(CDUnknownBlockType)arg6;
- (void)_fetchRemoteStoriesWithQuery:(id)arg1 tapHistory:(id)arg2 pageSessionId:(id)arg3 updatingBlock:(CDUnknownBlockType)arg4;
- (void)_fetchRemoteStoriesWithQuery:(id)arg1 tapHistory:(id)arg2 updatingBlock:(CDUnknownBlockType)arg3;
- (void)_fetchRemoteStoriesWithQuery:(id)arg1 updatingBlock:(CDUnknownBlockType)arg2;
- (void)resultsForQuery:(id)arg1 updatingBlock:(CDUnknownBlockType)arg2;
- (_Bool)canPerformQuery:(id)arg1;
- (id)initWithUserSession:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

