//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "NSCoding-Protocol.h"

@class NSMutableArray, NSMutableSet;

@interface SCCheetahBuffer : NSObject <NSCoding>
{
    unsigned long long _modelVersion;
    NSMutableArray *_buffer;
    unsigned long long _firstIndex;
    unsigned long long _numberOfItems;
    NSMutableSet *_objectsInBuffer;
    unsigned long long _size;
}

@property(readonly, nonatomic) unsigned long long size; // @synthesize size=_size;
- (void).cxx_destruct;
- (unsigned long long)_indexForItem:(unsigned long long)arg1;
- (id)allObjects;
- (void)addObject:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithSize:(unsigned long long)arg1;

@end

