//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCSavableItemChatViewModel.h"

#import "SCStackableViewModelProtocol-Protocol.h"

@class NSMutableArray, NSString;

@interface SCChatSDKParcelMessageViewModel : SCSavableItemChatViewModel <SCStackableViewModelProtocol>
{
    double _maximumWidth;
    double _totalPluginsWidth;
    NSMutableArray *_messages;
    NSMutableArray *_renderers;
    NSString *_messageType;
}

@property(copy, nonatomic) NSString *messageType; // @synthesize messageType=_messageType;
@property(retain, nonatomic) NSMutableArray *renderers; // @synthesize renderers=_renderers;
@property(retain, nonatomic) NSMutableArray *messages; // @synthesize messages=_messages;
@property(nonatomic) double totalPluginsWidth; // @synthesize totalPluginsWidth=_totalPluginsWidth;
@property(nonatomic) double maximumWidth; // @synthesize maximumWidth=_maximumWidth;
- (void).cxx_destruct;
- (_Bool)isEqual:(id)arg1;
- (void)addMessage:(id)arg1;
- (_Bool)canStackNewMessage:(id)arg1;
- (_Bool)isStackable;
- (id)savedByUsersAtIndex:(unsigned long long)arg1 usernameToDisplayNameTransformBlock:(CDUnknownBlockType)arg2;
- (_Bool)isMessageAtIndex:(unsigned long long)arg1 savedByUser:(id)arg2;
- (_Bool)isMessageAtIndexSaved:(unsigned long long)arg1;
- (unsigned long long)numberOfMessages;
- (_Bool)containsMessage:(id)arg1;
- (id)messageAtIndex:(unsigned long long)arg1;
- (id)messageIdAtIndex:(unsigned long long)arg1;
- (id)rendererAtIndex:(unsigned long long)arg1;
- (Class)messageHandlerClass;
- (id)message;
- (_Bool)isSaved;
- (id)reusableCellIdentifier;
- (double)bodyContentWidth;
- (double)payloadHeight;
- (id)createChatCellWithParentVC:(id)arg1 delegate:(id)arg2;
- (_Bool)_modifyPropsWithOverride:(long long)arg1 withDefault:(_Bool)arg2;
- (id)initWithMessage:(id)arg1 metadata:(id)arg2 props:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

