//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "NSCoding-Protocol.h"
#import "NSCopying-Protocol.h"

@class NSString, SCCheetahClientDisplayInfo, SCCheetahCompositeStoryId, SCCheetahStoryDebugInfo, SCCheetahStoryLoggingInfo;
@protocol NSCopying;

@interface SCCheetahStory : NSObject <NSCopying, NSCoding>
{
    _Bool _isSubscribed;
    _Bool _isFeatured;
    _Bool _rankShouldBeFixed;
    _Bool _isSensitive;
    _Bool _isFullyViewed;
    float _tileAspectRatio;
    float _score;
    SCCheetahCompositeStoryId *_compositeStoryId;
    unsigned long long _storyDedupeFp;
    long long _storyType;
    NSString *_featuredBannerText;
    SCCheetahStoryDebugInfo *_debugInfo;
    NSObject<NSCopying> *_storyContent;
    SCCheetahStoryLoggingInfo *_storyLoggingInfo;
    unsigned long long _hideAfterWatch;
    SCCheetahClientDisplayInfo *_clientDisplayInfo;
    double _latestUpdateTimestampSecs;
}

@property(readonly, nonatomic) double latestUpdateTimestampSecs; // @synthesize latestUpdateTimestampSecs=_latestUpdateTimestampSecs;
@property(readonly, copy, nonatomic) SCCheetahClientDisplayInfo *clientDisplayInfo; // @synthesize clientDisplayInfo=_clientDisplayInfo;
@property(readonly, nonatomic) unsigned long long hideAfterWatch; // @synthesize hideAfterWatch=_hideAfterWatch;
@property(readonly, nonatomic) _Bool isFullyViewed; // @synthesize isFullyViewed=_isFullyViewed;
@property(readonly, nonatomic) _Bool isSensitive; // @synthesize isSensitive=_isSensitive;
@property(readonly, nonatomic) _Bool rankShouldBeFixed; // @synthesize rankShouldBeFixed=_rankShouldBeFixed;
@property(readonly, nonatomic) float score; // @synthesize score=_score;
@property(readonly, copy, nonatomic) SCCheetahStoryLoggingInfo *storyLoggingInfo; // @synthesize storyLoggingInfo=_storyLoggingInfo;
@property(readonly, copy, nonatomic) NSObject<NSCopying> *storyContent; // @synthesize storyContent=_storyContent;
@property(readonly, copy, nonatomic) SCCheetahStoryDebugInfo *debugInfo; // @synthesize debugInfo=_debugInfo;
@property(readonly, copy, nonatomic) NSString *featuredBannerText; // @synthesize featuredBannerText=_featuredBannerText;
@property(readonly, nonatomic) _Bool isFeatured; // @synthesize isFeatured=_isFeatured;
@property(readonly, nonatomic) _Bool isSubscribed; // @synthesize isSubscribed=_isSubscribed;
@property(readonly, nonatomic) float tileAspectRatio; // @synthesize tileAspectRatio=_tileAspectRatio;
@property(readonly, nonatomic) long long storyType; // @synthesize storyType=_storyType;
@property(readonly, nonatomic) unsigned long long storyDedupeFp; // @synthesize storyDedupeFp=_storyDedupeFp;
@property(readonly, copy, nonatomic) SCCheetahCompositeStoryId *compositeStoryId; // @synthesize compositeStoryId=_compositeStoryId;
- (void).cxx_destruct;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (void)encodeWithCoder:(id)arg1;
- (id)description;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithCompositeStoryId:(id)arg1 storyDedupeFp:(unsigned long long)arg2 storyType:(long long)arg3 tileAspectRatio:(float)arg4 isSubscribed:(_Bool)arg5 isFeatured:(_Bool)arg6 featuredBannerText:(id)arg7 debugInfo:(id)arg8 storyContent:(id)arg9 storyLoggingInfo:(id)arg10 score:(float)arg11 rankShouldBeFixed:(_Bool)arg12 isSensitive:(_Bool)arg13 isFullyViewed:(_Bool)arg14 hideAfterWatch:(unsigned long long)arg15 clientDisplayInfo:(id)arg16 latestUpdateTimestampSecs:(double)arg17;
- (id)initWithCoder:(id)arg1;

@end

