//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCContextCardController.h"

#import "SCContextDetailCardViewCellDelegate-Protocol.h"

@class NSArray, NSString, SCContextCardActionExecutor, SCContextDetailCardViewCell, SCContextViewDisplayMode, UIView;
@protocol SCContextContentLoaderProtocol;

@interface SCContextDetailCardController : SCContextCardController <SCContextDetailCardViewCellDelegate>
{
    SCContextDetailCardViewCell *_detailCardView;
    NSArray *_ratings;
    NSString *_primaryText;
    NSString *_footerText;
    NSArray *_footerFormattingRanges;
    UIView *_thumbnailView;
    SCContextViewDisplayMode *_thumbnailDisplayMode;
    id <SCContextContentLoaderProtocol> _contentLoader;
    SCContextCardActionExecutor *_thumbnailTapAction;
}

@property(retain, nonatomic) SCContextCardActionExecutor *thumbnailTapAction; // @synthesize thumbnailTapAction=_thumbnailTapAction;
- (void).cxx_destruct;
- (void)thumbnailWasTapped:(id)arg1;
- (Class)cellClass;
- (id)cellTypeIdentifier;
- (void)attachCardView:(id)arg1;
- (void)setupView:(_Bool)arg1;
- (void)_loadContent;
- (struct CGSize)sizeForCell;
- (id)initWithCard:(id)arg1 contentLoader:(id)arg2 ratingViewModels:(id)arg3 session:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

