//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSMutableDictionary;

@interface SCContentInviteFeedEventGenerator : NSObject
{
    NSMutableDictionary *_recordEventGenerators;
}

- (void).cxx_destruct;
- (void)clearAllFeedEventGenerators;
- (void)clearFeedEventGeneratorsByIds:(id)arg1;
- (id)interactionEventBatchForRecord:(id)arg1;
- (void)updateWithRecords:(id)arg1;
- (void)updateWithSnap:(id)arg1;
- (id)init;

@end

