//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString, SCQueuePerformer, SCSentinel, SCUserSession, SOJUContextFilterMetadata, UIImage;

@interface SCContextFilterImageGenerator : NSObject
{
    SCSentinel *_sentinel;
    SCQueuePerformer *_performer;
    long long _mediaOrientation;
    SCUserSession *_userSession;
    SOJUContextFilterMetadata *_contextFilterMetadata;
    NSString *_selectedContextFilterId;
    UIImage *_selectedContextFilterImage;
    int _deviceMode;
}

+ (struct CGSize)_getProcessingSizeForInputSize:(const Size__dedc3bbb *)arg1 minDimension:(int)arg2;
+ (int)_getDeviceMode;
+ (_Bool)shouldEnableHighEndModel;
+ (_Bool)shouldEnableContextFilter;
- (void).cxx_destruct;
- (_Bool)_modelsReady;
- (_Bool)_shouldEnablePortraitFilter:(const struct Mat *)arg1;
- (void)_portraitImageWithPurikuraFromImageMat:(struct Mat)arg1 portraitMask:(struct Mat)arg2 portraitType:(long long)arg3 completeBlock:(CDUnknownBlockType)arg4;
- (id)_bokehPortraitImageFromImageMat:(struct Mat)arg1 portraitMask:(struct Mat)arg2 portraitType:(long long)arg3;
- (void)_getPortraitImageFromImageMat:(struct Mat)arg1 portraitMask:(struct Mat)arg2 portraitFilterType:(long long)arg3 completeBlock:(CDUnknownBlockType)arg4;
- (id)_getContextImageFromSkyImage:(id)arg1 skyItem:(id)arg2 imageMat:(const struct Mat *)arg3 skyMaskMat:(const struct Mat *)arg4;
- (void)_detectObjectTypeFromBaseImageMat:(struct Mat)arg1 completeBlock:(CDUnknownBlockType)arg2;
- (struct Mat)_toCVMatWithResize:(id)arg1;
- (void)_generateContextImagesFromImage:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)generateContextImagesFromImage:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)generateContextImagesFromImageFuture:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)clear;
- (id)initWithUserSession:(id)arg1 contextFilterMetadata:(id)arg2 selectedContextFilterId:(id)arg3 selectedContextFilterImage:(id)arg4 mediaOrientation:(long long)arg5;

@end

