//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSCache, NSMutableArray, SCCraftCoreImageUtils, SCCraftLogger, SCCraftResourceManager, SCQueuePerformer, SCUserSession, UIImage;

@interface SCCraftThumbnailLoader : NSObject
{
    NSCache *_cache;
    SCQueuePerformer *_performer;
    SCUserSession *_userSession;
    SCCraftResourceManager *_resourceManager;
    NSMutableArray *_pendingThumbnailsToLoad;
    UIImage *_image;
    SCCraftLogger *_logger;
    struct CGSize _thumbnailSize;
    SCCraftCoreImageUtils *_coreImageUtils;
}

- (void).cxx_destruct;
- (id)scaleDownImage:(id)arg1 size:(struct CGSize)arg2;
- (void)_setThumbnail:(id)arg1 thumbnailSize:(struct CGSize)arg2 image:(id)arg3 success:(CDUnknownBlockType)arg4;
- (void)_loadImageData:(id)arg1 success:(CDUnknownBlockType)arg2;
- (void)_loadPendingThumbnails:(struct CGSize)arg1 success:(CDUnknownBlockType)arg2;
- (void)loadThumbnailForStyleList:(id)arg1 thumbnailSize:(struct CGSize)arg2 success:(CDUnknownBlockType)arg3;
- (void)loadThumbnail:(id)arg1 thumbnailSize:(struct CGSize)arg2 success:(CDUnknownBlockType)arg3;
- (void)updateImage:(id)arg1;
- (id)initWithImageAndUserSession:(id)arg1 resourceManager:(id)arg2 logger:(id)arg3;

@end

