//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "NSCoding-Protocol.h"
#import "SCAdOwnerProtocol-Protocol.h"
#import "SCDiscoverEditionMediaLoaderDataSource-Protocol.h"
#import "SCDiscoverEditionMediaLoaderDelegate-Protocol.h"
#import "SCMediaOwnerProtocol-Protocol.h"

@class NSArray, NSDate, NSDictionary, NSMutableArray, NSMutableDictionary, NSString, SCCheetahStory, SCChunkSection, SCDiscoverChannel, SCDiscoverEditionMediaLoader, SCTileCover;

@interface SCDiscoverEdition : NSObject <NSCoding, SCDiscoverEditionMediaLoaderDataSource, SCDiscoverEditionMediaLoaderDelegate, SCAdOwnerProtocol, SCMediaOwnerProtocol>
{
    _Bool _archived;
    _Bool _hasBeenFullyViewed;
    _Bool _isBeingDisplayed;
    SCCheetahStory *_cheetahStory;
    SCDiscoverChannel *_channel;
    NSString *_dSnapIdToDisplayFirst;
    NSDate *_fullyViewedDate;
    SCTileCover *_tileToDisplay;
    NSString *__id;
    NSString *_editionVersion;
    SCChunkSection *_sectionToResume;
    NSArray *_chunks;
    NSArray *_chunksToDisplay;
    NSString *_adUnitId;
    NSDictionary *_adTargetingParameters;
    NSString *_overrideRootChunkDSnapId;
    SCDiscoverEditionMediaLoader *_mediaLoader;
    NSMutableDictionary *_sectionIDToChunkIndexMap;
    NSMutableDictionary *_sectionIDToChunkToDisplayIndexMap;
    NSMutableArray *_chunksWithTileArray;
}

@property(retain, nonatomic) NSMutableArray *chunksWithTileArray; // @synthesize chunksWithTileArray=_chunksWithTileArray;
@property(retain, nonatomic) NSMutableDictionary *sectionIDToChunkToDisplayIndexMap; // @synthesize sectionIDToChunkToDisplayIndexMap=_sectionIDToChunkToDisplayIndexMap;
@property(retain, nonatomic) NSMutableDictionary *sectionIDToChunkIndexMap; // @synthesize sectionIDToChunkIndexMap=_sectionIDToChunkIndexMap;
@property(retain, nonatomic) SCDiscoverEditionMediaLoader *mediaLoader; // @synthesize mediaLoader=_mediaLoader;
@property(copy, nonatomic) NSString *overrideRootChunkDSnapId; // @synthesize overrideRootChunkDSnapId=_overrideRootChunkDSnapId;
@property(copy, nonatomic) NSDictionary *adTargetingParameters; // @synthesize adTargetingParameters=_adTargetingParameters;
@property(copy, nonatomic) NSString *adUnitId; // @synthesize adUnitId=_adUnitId;
@property(copy, nonatomic) NSArray *chunksToDisplay; // @synthesize chunksToDisplay=_chunksToDisplay;
@property(copy, nonatomic) NSArray *chunks; // @synthesize chunks=_chunks;
@property(retain, nonatomic) SCChunkSection *sectionToResume; // @synthesize sectionToResume=_sectionToResume;
@property(nonatomic) _Bool isBeingDisplayed; // @synthesize isBeingDisplayed=_isBeingDisplayed;
@property(copy, nonatomic) NSString *editionVersion; // @synthesize editionVersion=_editionVersion;
@property(copy, nonatomic) NSString *_id; // @synthesize _id=__id;
@property(retain, nonatomic) SCTileCover *tileToDisplay; // @synthesize tileToDisplay=_tileToDisplay;
@property(retain, nonatomic) NSDate *fullyViewedDate; // @synthesize fullyViewedDate=_fullyViewedDate;
@property(nonatomic) _Bool hasBeenFullyViewed; // @synthesize hasBeenFullyViewed=_hasBeenFullyViewed;
@property(copy, nonatomic) NSString *dSnapIdToDisplayFirst; // @synthesize dSnapIdToDisplayFirst=_dSnapIdToDisplayFirst;
@property(retain, nonatomic) SCDiscoverChannel *channel; // @synthesize channel=_channel;
@property(nonatomic, getter=isArchived) _Bool archived; // @synthesize archived=_archived;
@property(retain, nonatomic) SCCheetahStory *cheetahStory; // @synthesize cheetahStory=_cheetahStory;
- (void).cxx_destruct;
- (void)editionMediaLoader:(id)arg1 didSkipLoadingChunk:(id)arg2;
- (id)chunksForCreatingOperaViewModels;
- (void)_updateTileToDisplayBasedOnViewedState;
- (id)rootChunk;
- (id)rootChunkDSnapId;
- (void)editionMediaLoader:(id)arg1 didFinishLoadingChunk:(id)arg2 success:(_Bool)arg3 error:(id)arg4;
- (long long)indexOfRootChunkForMediaLoader:(id)arg1;
- (id)chunksForEditionMediaLoader:(id)arg1;
- (id)mediaFileNames;
- (id)cacheMediaIds;
- (id)lastNonSubscriptionChunkToDisplay;
- (id)nextChunkToDisplay;
- (id)chunkForSection:(id)arg1;
- (_Bool)shouldBeViewedFromBeginning;
- (id)chunksWithTile;
- (void)clearChunk:(id)arg1;
- (void)didFailToFindMediaInSection:(id)arg1;
- (void)didFinishAutoAdvanceViewingSession;
- (void)didFinishViewing;
- (void)didStartViewing;
- (void)prepareToStartViewing;
- (void)clearAllAdChunkTransforms;
- (void)processAdPlacements;
- (id)cacheAdIds;
- (_Bool)hasContent;
- (unsigned long long)indexOfChunk:(id)arg1;
- (void)_rebuildSectionIdToChunkToDisplayIndexMap;
- (void)_rebuildSectionIdToChunkIndexMap;
- (void)_rebuildChunksWithTileArray;
@property(readonly, copy) NSString *description;
- (void)didDecodeObject;
- (void)ensureNonNilObjects;
- (void)_generateAdRequestInfoForceGenerate:(_Bool)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)updateWithEditionVersion:(id)arg1 chunks:(id)arg2;
- (id)initWithEditionId:(id)arg1 editionVersion:(id)arg2 chunks:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

