//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSDate;

@interface SCDiscoverPlaybackEventSession : NSObject
{
    _Bool _itemLoaded;
    NSDate *_startTime;
    long long _itemLoadState;
}

@property(nonatomic) _Bool itemLoaded; // @synthesize itemLoaded=_itemLoaded;
@property(nonatomic) long long itemLoadState; // @synthesize itemLoadState=_itemLoadState;
@property(retain, nonatomic) NSDate *startTime; // @synthesize startTime=_startTime;
- (void).cxx_destruct;
- (id)init;

@end

