//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "SCMediaOwnerProtocol-Protocol.h"
#import "SCOperaPlaylistAdTrackProtocol-Protocol.h"
#import "SCOperaPlaylistDataSource-Protocol.h"
#import "SCStreamingProxiedURLProviding-Protocol.h"

@class NSMutableDictionary, NSString, SCDiscoverOperaMediaManager, SCDynamicAdPlacement, SCOperaViewController, SCUserSession;
@protocol SCChunk, SCOperaPlaylistItemController, SCStreamingProxiedURLProviding;

@interface SCDynamicAdDataSource : NSObject <SCStreamingProxiedURLProviding, SCOperaPlaylistDataSource, SCMediaOwnerProtocol, SCOperaPlaylistAdTrackProtocol>
{
    SCUserSession *_userSession;
    SCDynamicAdPlacement *_currentAdPlacement;
    SCDiscoverOperaMediaManager *_discoverMediaManager;
    NSMutableDictionary *_skippedAdAfterItemIdToAdItemIdMap;
    id <SCChunk> _pendingInsertAdDataModel;
    NSMutableDictionary *_insertedAditemIdToDataModelMap;
    id <SCStreamingProxiedURLProviding> _streamingProxiedURLProvider;
    NSMutableDictionary *_insertedAdGroupIdToDataModelMap;
    NSMutableDictionary *_insertedAdGroupIdToGroupMap;
    NSMutableDictionary *_skippedAdAfterGroupIdToAdGroupIdMap;
    SCOperaViewController *_operaViewController;
    id <SCOperaPlaylistItemController> _playlistItemController;
    NSMutableDictionary *_adRequestClientIdToAdResponseMap;
    NSMutableDictionary *_groupIdToInsertedAdItemIdsByOrder;
}

+ (id)adDataModelLoadStatusToString:(long long)arg1;
+ (long long)_loadStatusForDataModel:(id)arg1;
@property(retain, nonatomic) NSMutableDictionary *groupIdToInsertedAdItemIdsByOrder; // @synthesize groupIdToInsertedAdItemIdsByOrder=_groupIdToInsertedAdItemIdsByOrder;
@property(retain, nonatomic) NSMutableDictionary *adRequestClientIdToAdResponseMap; // @synthesize adRequestClientIdToAdResponseMap=_adRequestClientIdToAdResponseMap;
@property(readonly, nonatomic) SCUserSession *userSession; // @synthesize userSession=_userSession;
@property(nonatomic) __weak id <SCOperaPlaylistItemController> playlistItemController; // @synthesize playlistItemController=_playlistItemController;
@property(nonatomic) __weak SCOperaViewController *operaViewController; // @synthesize operaViewController=_operaViewController;
- (void).cxx_destruct;
- (id)proxiedStreamingURLForMediaURL:(id)arg1 encryptionInfo:(id)arg2 trackingInfo:(id)arg3 requestContexts:(id)arg4;
- (void)log:(id)arg1;
- (id)mediaFileNames;
- (id)cacheMediaIds;
- (id)adSessionId;
- (id)adSkipEventForDataModel:(id)arg1;
- (_Bool)isNofillAdGroup:(id)arg1;
- (id)_adSkipEventWithDataModel:(id)arg1;
- (void)logAdSkipWithAdGroup:(id)arg1;
- (id)adViewContextForSkippedGroup:(id)arg1;
- (id)adRequestClientIdForGroup:(id)arg1;
- (id)skippedAdGroupAroundGroup:(id)arg1 pagedLeft:(_Bool)arg2;
- (void)logAdSkipWithAdItem:(id)arg1 aroundItem:(id)arg2 pageLeft:(_Bool)arg3;
- (_Bool)isNofillAdItem:(id)arg1;
- (id)adViewContextForGroup:(id)arg1;
- (id)adViewContextForSkippedItem:(id)arg1 aroundItem:(id)arg2 pageLeft:(_Bool)arg3;
- (id)skippedItemAroundItem:(id)arg1 pageLeft:(_Bool)arg2;
- (id)adViewContextForItem:(id)arg1 operaViewController:(id)arg2;
- (id)adRequestClientIdForItem:(id)arg1 playlistItemController:(id)arg2;
- (long long)adSnapIndexForItem:(id)arg1;
- (_Bool)isDismissingSessionWithItem:(id)arg1 isViewingLongform:(_Bool)arg2;
- (_Bool)didFinishViewingAdItem:(id)arg1 isViewingLongform:(_Bool)arg2;
- (_Bool)shouldInsertPlaylistItemGroup;
- (_Bool)shouldInsertPlaylistItem;
- (_Bool)insertPendingAdAfterItem:(id)arg1;
- (void)resetPendingAd;
- (void)resetInsertionData;
- (_Bool)isSkippedAdItem:(id)arg1;
- (_Bool)isInsertedAdGroup:(id)arg1;
- (_Bool)isInsertedAdItem:(id)arg1;
- (long long)currentDataModelLoadStatus;
- (long long)mediaLoadConnectivity;
- (long long)mediaLoadFallbackPriority;
- (long long)mediaLoadRequestPriority;
- (id)mediaLoadContexts;
- (void)fetchMediaForPendingInsertAd;
- (void)_handleFetchSuccess:(_Bool)arg1 error:(id)arg2 adResponseV2:(id)arg3 adKey:(id)arg4;
- (void)_onAdTransformError:(id)arg1;
- (void)_onAdTransformComplete:(id)arg1;
- (double)adRequestTimeoutInMilliseconds;
- (unsigned long long)adProductType;
- (id)adUnitId;
- (id)targetingParameters;
- (id)adRequestId;
- (void)requestAdWithCompletionBlock:(CDUnknownBlockType)arg1;
- (_Bool)isAdContentLoopingForDataModel:(id)arg1;
- (id)extraPagePropertiesForDataModel:(id)arg1;
- (void)removeMediaForItem:(id)arg1;
- (void)prepareMediaForItem:(id)arg1 waitForDownloading:(_Bool)arg2 startWaitingForDownloadCallback:(CDUnknownBlockType)arg3 completion:(CDUnknownBlockType)arg4;
- (void)pagesPropertiesForDataModel:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)loadMediaForPlaylistItemGroup:(id)arg1;
- (void)unresolvePlaylistItemGroup:(id)arg1;
- (void)resolvePlaylistItemGroup:(id)arg1;
- (_Bool)needToPrepareMediaBeforeDisplay;
- (id)playlistItemGroupForDataModel:(id)arg1;
- (_Bool)canResolvePlaylistItemGroupDataModel:(id)arg1;
- (id)dataModelForGroup:(id)arg1;
- (void)teardownDataModelForItem:(id)arg1;
- (id)dataModelForItem:(id)arg1;
- (void)teardown;
- (id)initWithUserSession:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

