//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class SCFaceCraftAlignImageWrapper;

@interface SCFaceCraftFaceTransformData : NSObject
{
    SCFaceCraftAlignImageWrapper *_imageAligner;
    vector_777fd472 _landmarks;
}

@property(retain, nonatomic) SCFaceCraftAlignImageWrapper *imageAligner; // @synthesize imageAligner=_imageAligner;
@property(nonatomic) vector_777fd472 landmarks; // @synthesize landmarks=_landmarks;
- (id).cxx_construct;
- (void).cxx_destruct;
- (id)initWithLandmarks:(vector_777fd472)arg1;

@end

