//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCEncryptedWriteThroughCache.h"

@class NSMutableDictionary, NSMutableSet;

@interface SCFideliusFriendDeviceInfoCache : SCEncryptedWriteThroughCache
{
    NSMutableDictionary *_userIdsToBetas;
    NSMutableSet *_userIdsFullyFetchedFromTable;
}

@property(retain, nonatomic) NSMutableSet *userIdsFullyFetchedFromTable; // @synthesize userIdsFullyFetchedFromTable=_userIdsFullyFetchedFromTable;
@property(retain, nonatomic) NSMutableDictionary *userIdsToBetas; // @synthesize userIdsToBetas=_userIdsToBetas;
- (void).cxx_destruct;
- (id)_betasForUserId:(id)arg1;
- (id)_friendDevicesDictForUserId:(id)arg1;
- (id)_friendDevicesForUserId:(id)arg1;
- (_Bool)_deleteObjectWithId:(id)arg1 forUserId:(id)arg2;
- (_Bool)_replaceObject:(id)arg1 forUserId:(id)arg2;
- (_Bool)_insertObject:(id)arg1 forUserId:(id)arg2;
- (id)_objectWithId:(id)arg1 forUserId:(id)arg2;
- (id)allFriends;
- (_Bool)deleteAllFriends;
- (_Bool)deleteAllFriendDevicesForUserId:(id)arg1;
- (id)friendDevicesDictForUserId:(id)arg1;
- (id)friendDevicesForUserId:(id)arg1;
- (_Bool)deleteObjectWithId:(id)arg1 forUserId:(id)arg2;
- (_Bool)deleteObjectWithId:(id)arg1;
- (_Bool)replaceObject:(id)arg1 forUserId:(id)arg2;
- (_Bool)replaceObject:(id)arg1;
- (_Bool)insertObject:(id)arg1 forUserId:(id)arg2;
- (_Bool)insertObject:(id)arg1;
- (id)objectWithId:(id)arg1 forUserId:(id)arg2;
- (id)objectWithId:(id)arg1;
- (id)idForObject:(id)arg1;
- (id)initWithTable:(id)arg1 performer:(id)arg2;

@end

