//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "NSCopying-Protocol.h"

@class NSArray, NSDate, NSString, SCFriendsFeedPerson;

@interface SCFriendsFeedEntity : NSObject <NSCopying>
{
    unsigned long long _subtype;
    SCFriendsFeedPerson *_person_person;
    NSDate *_person_addFriendTimestamp;
    NSDate *_person_reverseAddFriendTimestamp;
    NSArray *_person_friendmojis;
    NSDate *_person_birthdate;
    _Bool _person_isReported;
    _Bool _person_isStoryMuted;
    NSString *_group_groupName;
    NSArray *_group_participants;
    _Bool _group_isStoryMuted;
    NSArray *_multiRecipient_displayNames;
    NSString *_invitedContact_displayName;
}

+ (id)personWithPerson:(id)arg1 addFriendTimestamp:(id)arg2 reverseAddFriendTimestamp:(id)arg3 friendmojis:(id)arg4 birthdate:(id)arg5 isReported:(_Bool)arg6 isStoryMuted:(_Bool)arg7;
+ (id)multiRecipientWithDisplayNames:(id)arg1;
+ (id)invitedContactWithDisplayName:(id)arg1;
+ (id)groupWithGroupName:(id)arg1 participants:(id)arg2 isStoryMuted:(_Bool)arg3;
- (void).cxx_destruct;
- (void)matchPerson:(CDUnknownBlockType)arg1 group:(CDUnknownBlockType)arg2 multiRecipient:(CDUnknownBlockType)arg3 invitedContact:(CDUnknownBlockType)arg4;
- (_Bool)isEqual:(id)arg1;
- (id)internalInit;
- (unsigned long long)hash;
- (id)description;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

