//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSOperationQueue, SCQueuePerformer, SCUserSession;

@interface SCGalleryFaceManager : NSObject
{
    SCUserSession *_userSession;
    SCQueuePerformer *_performer;
    NSOperationQueue *_processingQueue;
}

@property(retain, nonatomic) NSOperationQueue *processingQueue; // @synthesize processingQueue=_processingQueue;
@property(retain, nonatomic) SCQueuePerformer *performer; // @synthesize performer=_performer;
@property(nonatomic) __weak SCUserSession *userSession; // @synthesize userSession=_userSession;
- (void).cxx_destruct;
- (id)uploadFacesFoundWithCompletionBlock:(CDUnknownBlockType)arg1;
- (id)facesAnalyzeGallerySnapsWithIDs:(id)arg1 forceReprocess:(_Bool)arg2 progressBlock:(CDUnknownBlockType)arg3 completionBlock:(CDUnknownBlockType)arg4;
- (id)faceAnalyzeRemainingGallerySnapsForcingReprocessing:(_Bool)arg1 progressBlock:(CDUnknownBlockType)arg2 completionBlock:(CDUnknownBlockType)arg3;
- (id)initWithUserSession:(id)arg1;
- (void)clearUserFeedback;
- (unsigned long long)feedbackForClusterId:(id)arg1;
- (void)userProvidedFeedback:(unsigned long long)arg1 forClusterId:(id)arg2 totalClusters:(long long)arg3;
- (unsigned long long)feedbackForFacesInGallerySnap:(id)arg1;
- (void)userProvidedFeedback:(unsigned long long)arg1 forFacesInGallerySnap:(id)arg2;
- (id)allCurrentFeedback;
- (id)feedbackStorage;

@end

