//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "SCGalleryEntryThumbnailGeneratorDelegate-Protocol.h"
#import "SCSendPreviewMediaView-Protocol.h"

@class FLAnimatedImageView, NSString, SCGalleryEntryThumbnailGenerator, SCUserSession, UIImageView;
@protocol SCGalleryEntry;

@interface SCGalleryStoryMediaView : UIView <SCGalleryEntryThumbnailGeneratorDelegate, SCSendPreviewMediaView>
{
    id <SCGalleryEntry> _storyEntry;
    SCUserSession *_userSession;
    SCGalleryEntryThumbnailGenerator *_thumbnailGenerator;
    FLAnimatedImageView *_imageView;
    UIImageView *_maskView;
}

- (void).cxx_destruct;
- (void)thumbnailGenerator:(id)arg1 didLoadThumbnail:(_Bool)arg2;
- (void)thumbnailGenerator:(id)arg1 didLoadPosterFrame:(id)arg2 snap:(id)arg3;
- (void)thumbnailGenerator:(id)arg1 didLoadMiniThumbnail:(id)arg2 snap:(id)arg3 loadingLatency:(double)arg4;
- (void)thumbnailGenerator:(id)arg1 didUpdateStoryThumbnailWithImage:(id)arg2 highlightedImage:(id)arg3 snap:(id)arg4 fromCache:(_Bool)arg5 isFramed:(_Bool)arg6;
- (void)thumbnailGenerator:(id)arg1 didUpdateStoryThumbnailWithImage:(id)arg2 snap:(id)arg3 fromCache:(_Bool)arg4 isFramed:(_Bool)arg5;
- (void)thumbnailGenerator:(id)arg1 didUpdateSnapThumbnailWithImageGenerating:(id)arg2 snap:(id)arg3 duration:(double)arg4 fromCache:(_Bool)arg5 isFramed:(_Bool)arg6;
- (void)pause;
- (void)play;
- (id)SCAMediaTypes;
- (void)layoutSubviews;
- (void)setBackgroundColor:(id)arg1;
- (id)initWithStoryEntry:(id)arg1 userSession:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

