//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCAsynchronousOperation.h"

@class NSArray, NSDate, NSError, NSString, SCGalleryVisualSearchIndexer, SCQueuePerformer, SCUserSession;
@protocol SCCanceling;

@interface SCGallerySnapFaceAnalysisOperation : SCAsynchronousOperation
{
    SCGalleryVisualSearchIndexer *_visualSearchIndexer;
    NSDate *_startDate;
    NSDate *_downloadEndDate;
    NSDate *_analyzeStartDate;
    NSDate *_analyzeEndDate;
    unsigned long long _gallerySnapMediaType;
    NSArray *_results;
    NSError *_error;
    NSString *_gallerySnapId;
    SCUserSession *_userSession;
    SCQueuePerformer *_performer;
    id <SCCanceling> _downloadRequest;
}

@property(retain, nonatomic) id <SCCanceling> downloadRequest; // @synthesize downloadRequest=_downloadRequest;
@property(retain, nonatomic) SCQueuePerformer *performer; // @synthesize performer=_performer;
@property(retain, nonatomic) SCUserSession *userSession; // @synthesize userSession=_userSession;
@property(retain, nonatomic) NSString *gallerySnapId; // @synthesize gallerySnapId=_gallerySnapId;
@property(retain, nonatomic) NSError *error; // @synthesize error=_error;
@property(retain, nonatomic) NSArray *results; // @synthesize results=_results;
- (void).cxx_destruct;
- (id)timeTaken;
- (void)analyzeGallerySnap:(id)arg1 withCloudFileContainer:(id)arg2;
- (void)fetchMediaForGallerySnap:(id)arg1;
- (void)start;
- (void)cancel;
- (id)initWithGallerySnapId:(id)arg1 userSession:(id)arg2;

@end

