//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSArray, SCUserSession;
@protocol SCCachingMediaRequest, SCCanceling, SCGalleryEntry, SCGalleryEntryThumbnailGeneratorDelegate, SCObserving, SCProgressReceiving;

@interface SCGalleryEntryThumbnailGenerator : NSObject
{
    SCUserSession *_userSession;
    id <SCGalleryEntry> _entry;
    struct CGSize _targetSize;
    CDStruct_bac8f6e9 _mediaScenePath;
    id <SCGalleryEntry> _latestEntry;
    NSArray *_latestSnapsToShowThumbnail;
    long long _indexOfSnapForStoryThumbnail;
    _Bool _generatingUpdates;
    id <SCObserving> _entryObserveContext;
    id _timerObserveContext;
    id <SCCachingMediaRequest> _cachingMediaRequest;
    id <SCCanceling> _miniThumbnailRequest;
    id <SCCachingMediaRequest> _posterFrameMediaRequest;
    _Bool _didStartGeneratingPosterFrame;
    CDUnknownBlockType _miniThumbnailBlock;
    double _latestThumbnailStartDisplayingTime;
    unsigned long long _generationContext;
    id <SCGalleryEntryThumbnailGeneratorDelegate> _delegate;
    id <SCProgressReceiving> _progressReceiver;
}

+ (id)dispatchQueue;
+ (double)delayOfUpdatingStoryThumbnailForCellAtIndexPath:(id)arg1;
+ (id)invertedStoryOverlayForTargetSize:(struct CGSize)arg1;
+ (void)stopUpdatingStoryThumbnails;
+ (void)startUpdatingStoryThumbnails;
@property(nonatomic) __weak id <SCProgressReceiving> progressReceiver; // @synthesize progressReceiver=_progressReceiver;
@property(nonatomic) __weak id <SCGalleryEntryThumbnailGeneratorDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_receiveProgressUpdateFromCachingMediaRequest:(id)arg1;
- (_Bool)_shouldLogThumbnailLatency;
- (void)_logThumbnailLoadingEndWithDidShowUp:(_Bool)arg1 snap:(id)arg2;
- (void)_generateThumbnailForStoryEntry;
- (void)_generateThumbnailForSnapEntry;
- (void)_storyThumbnailUpdateTimerDidFire;
- (void)_cancelMiniThumbnailBlock;
- (void)_updateLoadingIndicator:(_Bool)arg1;
- (void)_loadMiniThumbnailIfPossible;
- (void)_updateThumbnailWithLatestEntry:(id)arg1 latestSnaps:(id)arg2;
- (void)_generatePosterFrameForStoryEntry:(id)arg1;
- (void)stopGeneratingUpdates;
- (void)startGeneratingUpdates;
- (void)dealloc;
- (id)initWithUserSession:(id)arg1 entry:(id)arg2 targetSize:(struct CGSize)arg3 mediaScenePath:(CDStruct_bac8f6e9)arg4 generationContext:(unsigned long long)arg5;

@end

