//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "UIGestureRecognizerDelegate-Protocol.h"

@class NSIndexPath, NSMutableDictionary, NSMutableSet, NSString, UICollectionView, UIImage, UILongPressGestureRecognizer, UITapGestureRecognizer;
@protocol SCGalleryCollectionViewSelectionHelperDataSource, SCGalleryCollectionViewSelectionHelperDelegate;

@interface SCGalleryCollectionViewSelectionHelper : NSObject <UIGestureRecognizerDelegate>
{
    UICollectionView *_galleryCollectionView;
    NSMutableDictionary *_selectionIndexToSelectionModeMap;
    struct CGPoint _initialTapPoint;
    NSIndexPath *_touchItemIndexPath;
    unsigned long long _touchItemSelectionMode;
    NSIndexPath *_previousSelectIndexPath;
    UILongPressGestureRecognizer *_longPressGestureRecognizer;
    UILongPressGestureRecognizer *_actionMenuLongPressGestureRecognizer;
    UITapGestureRecognizer *_debugTapGestureRecognizer;
    _Bool _allowMultipleSelection;
    UIImage *_selectOverlayImage;
    NSMutableDictionary *_entrySnapsMap;
    id <SCGalleryCollectionViewSelectionHelperDataSource> _dataSource;
    id <SCGalleryCollectionViewSelectionHelperDelegate> _delegate;
    unsigned long long _selectMode;
}

@property(nonatomic) unsigned long long selectMode; // @synthesize selectMode=_selectMode;
@property(nonatomic) __weak id <SCGalleryCollectionViewSelectionHelperDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak id <SCGalleryCollectionViewSelectionHelperDataSource> dataSource; // @synthesize dataSource=_dataSource;
- (void).cxx_destruct;
- (void)_handleSingleSelectionAtIndexPath:(id)arg1 selectionMode:(unsigned long long)arg2;
- (void)_handleMultipleSelectionAtIndexPath:(id)arg1 selectionMode:(unsigned long long)arg2;
- (void)_handleTapAtIndexPath:(id)arg1 selectionMode:(unsigned long long)arg2;
- (id)_selectedItemsWithFilterBlock:(CDUnknownBlockType)arg1;
- (void)_handleDebugTapGesture:(id)arg1;
- (void)_handleActionMenuLongPressGesture:(id)arg1;
- (id)_touchItemCell;
- (void)_handleLongPressGesture:(id)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (_Bool)gestureRecognizer:(id)arg1 shouldReceiveTouch:(id)arg2;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (void)toggleSelectionModeForSnap:(id)arg1 atIndexPath:(id)arg2;
- (void)setSelectionModeForCell:(id)arg1 snapCell:(id)arg2 forSnap:(id)arg3;
- (void)changeSelectionMode:(unsigned long long)arg1 snap:(id)arg2 atIndexPath:(id)arg3;
- (void)cancelOngoingGestureRecognizers;
- (unsigned long long)_itemSelectionModeAtIndexPath:(id)arg1;
- (void)toggleSelectionModeAtIndexPath:(id)arg1;
- (void)setSelectionModeForCell:(id)arg1 atIndexPath:(id)arg2;
- (unsigned long long)changeSelectionMode:(unsigned long long)arg1 atIndexPath:(id)arg2;
- (id)_selectedSnapIdsAtIndexPath:(id)arg1;
@property(readonly, nonatomic) NSMutableSet *selectedSnaps;
- (id)selectedGalleryEntries;
- (id)selectedItems;
@property(readonly, nonatomic, getter=isSelecting) _Bool selecting;
- (void)dealloc;
- (id)initWithGalleryCollectionView:(id)arg1 allowMultipleSelection:(_Bool)arg2 selectOverlayImage:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

