//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface SCGalleryExportLogger : NSObject
{
}

+ (unsigned long long)_getNumberOfStoriesFromItems:(id)arg1;
+ (unsigned long long)_getNumberOfSnapsFromItems:(id)arg1;
+ (unsigned long long)_convertToExportResultWithSuccess:(_Bool)arg1 cancelled:(_Bool)arg2;
+ (void)didCompleteExportWithSessionId:(id)arg1 success:(_Bool)arg2 cancelled:(_Bool)arg3 saveToCameraRoll:(_Bool)arg4;
+ (id)attemptToExportItems:(id)arg1 actionSource:(long long)arg2;

@end

