//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "SCGroupManagerAPI-Protocol.h"

@class NSString;

@interface SCGroupManagerAPI : NSObject <SCGroupManagerAPI>
{
}

+ (id)shared;
- (_Bool)_isErrorResponse:(id)arg1;
- (void)updateGroupBlockedParticipantExceptionsWithGroupId:(id)arg1 newBlockedParticipantExceptions:(id)arg2 successBlock:(CDUnknownBlockType)arg3 failureBlock:(CDUnknownBlockType)arg4 callbackQueue:(id)arg5;
- (void)updateGroupNotificationWithGroupId:(id)arg1 notificationOn:(_Bool)arg2 successBlock:(CDUnknownBlockType)arg3 failureBlock:(CDUnknownBlockType)arg4 callbackQueue:(id)arg5;
- (void)addToGroupWithGroupId:(id)arg1 participantIds:(id)arg2 successBlock:(CDUnknownBlockType)arg3 failureBlock:(CDUnknownBlockType)arg4 callbackQueue:(id)arg5;
- (void)updateGroupNameWithGroupId:(id)arg1 groupName:(id)arg2 successBlock:(CDUnknownBlockType)arg3 failureBlock:(CDUnknownBlockType)arg4 callbackQueue:(id)arg5;
- (void)updateGroupMuteStateTo:(_Bool)arg1 forGroupId:(id)arg2;
- (void)leaveGroupWithGroupId:(id)arg1 successBlock:(CDUnknownBlockType)arg2 failureBlock:(CDUnknownBlockType)arg3 callbackQueue:(id)arg4;
- (void)fetchGroupWithMischiefRequest:(id)arg1 successBlock:(CDUnknownBlockType)arg2 failureBlock:(CDUnknownBlockType)arg3 callbackQueue:(id)arg4;
- (void)createGroupsWithMischiefRequest:(id)arg1 successBlock:(CDUnknownBlockType)arg2 failureBlock:(CDUnknownBlockType)arg3 callbackQueue:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

