//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class SCGtqRequestContext, SCULGtqServeRequest, SOJUUnlockablesGtqServeResponse;

@protocol SCGtqUnlockablesDataSourceListener <NSObject>
- (void)didFetchUnlockables:(SOJUUnlockablesGtqServeResponse *)arg1 withContext:(SCGtqRequestContext *)arg2 forRequest:(SCULGtqServeRequest *)arg3;
@end

