//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIButton.h>

@class SCHeaderPromptViewModel, SCShapeView, UILabel;
@protocol SCHeaderPromptViewDelegate;

@interface SCHeaderPromptView : UIButton
{
    SCShapeView *_backgroundView;
    SCHeaderPromptViewModel *_viewModel;
    UILabel *_titleLabel;
    UILabel *_bodyLabel;
    UILabel *_emojiLabel;
    UIButton *_dismissIcon;
    id <SCHeaderPromptViewDelegate> _delegate;
}

+ (double)_heightWithViewModel:(id)arg1;
+ (double)_heightConstraint;
+ (double)_textWidthConstraint;
+ (double)_widthConstraint;
@property(nonatomic) __weak id <SCHeaderPromptViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)_didTap;
- (void)_didDismiss;
- (void)_setupSubviews;
- (id)initWithViewModel:(id)arg1;

@end

