//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCHereBaseCall.h"

@interface SCHereConnectedCall : SCHereBaseCall
{
    _Bool _isAudio;
}

- (_Bool)isAudio;
- (void)sentWithSuccess:(_Bool)arg1 response:(id)arg2;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithUsername:(id)arg1 recipient:(id)arg2 outgoing:(_Bool)arg3 isAudio:(_Bool)arg4 connectedTimesatmp:(id)arg5;

@end

