//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCHovaTabBarItemView.h"

@class NSString;

@interface SCHovaTabBarCameraItemView : SCHovaTabBarItemView
{
    double _imageWidthDifference;
}

@property(nonatomic) double imageWidthDifference; // @synthesize imageWidthDifference=_imageWidthDifference;
- (double)cameraViewWidth;
- (double)imageViewWidth;
- (void)setVerticallyVisible:(_Bool)arg1;
- (void)setSelectedView:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 itemType:(long long)arg2;

// Remaining properties
@property(retain, nonatomic) NSString *backgroundImageName; // @dynamic backgroundImageName;
@property(retain, nonatomic) NSString *darkModeImageName; // @dynamic darkModeImageName;

@end

