//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class AVAssetWriter, AVAssetWriterInput, AVAssetWriterInputPixelBufferAdaptor, NSArray, NSURL, SCImageProcessQueue, SCQueuePerformer, UIImage;

@interface SCImageProcessAnimatableImageExportSession : NSObject
{
    SCImageProcessQueue *_imageProcessQueue;
    UIImage *_image;
    NSArray *_GPUCommands;
    NSArray *_CPUCommands;
    long long _fps;
    long long _bitrate;
    double _duration;
    NSURL *_outputURL;
    struct CGSize _outputSize;
    SCQueuePerformer *_performer;
    struct __CVBuffer *_imagePixelBuffer;
    AVAssetWriter *_videoWriter;
    AVAssetWriterInput *_videoWriterInput;
    AVAssetWriterInputPixelBufferAdaptor *_adaptor;
    CDUnknownBlockType _completion;
    CDUnknownBlockType _progress;
}

- (void).cxx_destruct;
- (struct __CVBuffer *)_createInputPixelBuffer;
- (void)_finish;
- (void)_failWithMessage:(id)arg1;
- (void)_cleanup;
- (_Bool)_processFrameAtTime:(double)arg1 semaphore:(id)arg2;
- (_Bool)_prepare;
- (void)dealloc;
- (void)runWithCompletion:(CDUnknownBlockType)arg1 progress:(CDUnknownBlockType)arg2;
- (id)initWithImageProcessQueue:(id)arg1 backgroundImage:(id)arg2 GPUCommands:(id)arg3 CPUCommands:(id)arg4 fps:(long long)arg5 bitrate:(long long)arg6 duration:(double)arg7 outputURL:(id)arg8 outputSize:(struct CGSize)arg9;

@end

