//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "SCImageProcessRequest-Protocol.h"

@class NSArray, NSData, NSString, SCImageProcessCommand, SCImageProcessPlaybackRenderer, UIColor;

@interface SCImageProcessColorFilterRequest : NSObject <SCImageProcessRequest>
{
    NSData *_data;
    NSData *_histogramData;
    unsigned long long _pixelWidth;
    unsigned long long _pixelHeight;
    SCImageProcessCommand *_leftCommand;
    SCImageProcessCommand *_rightCommand;
    NSArray *_preCommands;
    NSArray *_midCommands;
    NSArray *_postCommands;
    SCImageProcessPlaybackRenderer *_renderer;
    CDUnknownBlockType _colorFilterSessionCompletionHandler;
    CDUnknownBlockType _completionHandler;
    long long _orientation;
    _Bool _isOffsetLandscape;
    double _offset;
    unsigned int _texture;
    struct CGAffineTransform _viewportTransform;
    double _croppingAspectRatio;
    NSString *_colorFilterSessionId;
    unsigned int _intermediateTextures[2];
    double _displayTimestamp;
    UIColor *_backgroundColor;
    _Bool _hasProcessedImage;
    unsigned long long _status;
}

@property(readonly, nonatomic) unsigned long long status; // @synthesize status=_status;
- (void).cxx_destruct;
- (void)_runCommand:(id)arg1 context:(id)arg2 runContext:(id)arg3;
- (void)_processCommands:(id)arg1 textures:(unsigned int *)arg2 context:(id)arg3 runContext:(id)arg4 bindInputTexture:(_Bool)arg5 paintBackgroundColor:(_Bool)arg6;
- (void)_paintBackgroundColorWithContext:(id)arg1;
- (void)_setupOutputRendererWithContext:(id)arg1;
- (void)_setupIntermediateTexturesIfNeededWithContext:(id)arg1 intermediatePasses:(long long)arg2;
- (void)cancel;
- (void)runProgramsWithContext:(id)arg1 GPUAvailable:(_Bool)arg2;
@property(readonly, nonatomic) _Bool GPURequired;
- (id)initWithData:(id)arg1 histogramData:(id)arg2 pixelWidth:(unsigned long long)arg3 pixelHeight:(unsigned long long)arg4 leftCommand:(id)arg5 rightCommand:(id)arg6 preCommands:(id)arg7 midCommands:(id)arg8 postCommands:(id)arg9 colorFilterSessionCompletionHandler:(CDUnknownBlockType)arg10 renderer:(id)arg11 offset:(double)arg12 orientation:(long long)arg13 isOffsetLandscape:(_Bool)arg14 viewportTranform:(struct CGAffineTransform)arg15 croppingAspectRatio:(double)arg16 displayTimestamp:(double)arg17 backgroundColor:(id)arg18 completionHandler:(CDUnknownBlockType)arg19 colorFilterSessionId:(id)arg20;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

