//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, NSDate, NSError, NSString, SCLagunaContent, SCLagunaDevice;
@protocol NSCoding;

@protocol SCLagunaDeviceEventListener <NSObject>

@optional
- (void)device:(SCLagunaDevice *)arg1 receivedLastCloudUploadTime:(NSDate *)arg2;
- (void)device:(SCLagunaDevice *)arg1 receivedWifiAPList:(NSArray *)arg2;
- (void)device:(SCLagunaDevice *)arg1 receivedClientId:(NSString *)arg2 requestAuthzCode:(_Bool)arg3;
- (void)device:(SCLagunaDevice *)arg1 uploadToCloudEvent:(unsigned long long)arg2;
- (void)device:(SCLagunaDevice *)arg1 didMarkCorruptContent:(SCLagunaContent *)arg2;
- (void)deviceDidRateLimitWifi:(SCLagunaDevice *)arg1;
- (void)deviceDidStartRecording:(SCLagunaDevice *)arg1;
- (void)device:(SCLagunaDevice *)arg1 didReceiveCrashReport:(NSArray *)arg2;
- (void)device:(SCLagunaDevice *)arg1 didCompletedScheduledUpdateWithUserInfo:(id <NSCoding>)arg2 error:(NSError *)arg3;
- (void)deviceDidFetchFirmwareDigest:(SCLagunaDevice *)arg1 digest:(NSString *)arg2;
- (void)device:(SCLagunaDevice *)arg1 onFirmwareUpdate:(unsigned long long)arg2 progress:(float)arg3;
- (void)deviceDidUpdateTaskQueue:(SCLagunaDevice *)arg1;
- (void)device:(SCLagunaDevice *)arg1 didUpdateInfo:(unsigned long long)arg2;
- (void)device:(SCLagunaDevice *)arg1 didReceiveAlertNotification:(unsigned long long)arg2;
- (void)device:(SCLagunaDevice *)arg1 didUnpairWithReason:(unsigned long long)arg2;
- (void)deviceDidUpdateState:(SCLagunaDevice *)arg1;
- (void)deviceDidRequestArchiving:(SCLagunaDevice *)arg1;
@end

