//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "SCUserSessionScoped-Protocol.h"

@class NSString, SCLensDataFetcherV2, SCLensPreloadingBehavior;
@protocol SCPerforming;

@interface SCLensDataPrefetcherV2 : NSObject <SCUserSessionScoped>
{
    SCLensDataFetcherV2 *_lensDataFetcher;
    id <SCPerforming> _performer;
    SCLensPreloadingBehavior *_lensPreloadingBehavior;
}

@property(retain, nonatomic) SCLensPreloadingBehavior *lensPreloadingBehavior; // @synthesize lensPreloadingBehavior=_lensPreloadingBehavior;
@property(retain, nonatomic) id <SCPerforming> performer; // @synthesize performer=_performer;
@property(retain, nonatomic) SCLensDataFetcherV2 *lensDataFetcher; // @synthesize lensDataFetcher=_lensDataFetcher;
- (void).cxx_destruct;
- (void)prefetch3DBitmojiMetadataAssets:(id)arg1 lens:(id)arg2;
- (void)prefetchAvatar3DAsset:(id)arg1 lens:(id)arg2;
- (void)prefetchBitmojiListItems:(id)arg1 bitmojiStickers:(id)arg2 lens:(id)arg3;
- (void)prefetchManifestItemsForLens:(id)arg1;
- (void)invalidate;
- (void)prefetchAssets:(id)arg1;
- (void)prefetchAssetsForLens:(id)arg1;
- (void)prefetchLenses:(id)arg1;
- (id)initWithLensDataFetcher:(id)arg1 performer:(id)arg2 userSession:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

