//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "LSAUriServiceProvider-Protocol.h"

@class NSString, SCFuture, SCMapGameStateDataStore, SCPromise, SCSessionRequestManager;
@protocol SCPerforming;

@interface SCLensUriServiceProvider : NSObject <LSAUriServiceProvider>
{
    SCSessionRequestManager *_requestManager;
    SCMapGameStateDataStore *_mapGameStateDataStore;
    id <SCPerforming> _performer;
    SCPromise *_snappablesDataPromise;
}

- (void).cxx_destruct;
- (void)notifyRequest:(id)arg1 description:(id)arg2 code:(long long)arg3 data:(id)arg4 completion:(CDUnknownBlockType)arg5;
- (void)notifyBadRequest:(id)arg1 description:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (id)hostnameToFsnHeadersMap;
- (id)hostnameToFsnBasePathMap;
- (id)methodStringToEnumMap;
- (void)handleMapRequest:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)handleEchoRequest:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)handleSnappableRequest:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)handleAppRequest:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)handleFsnRequest:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)reset;
@property(readonly, nonatomic) SCFuture *snappablesDataFuture;
- (void)performRequest:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)initWithRequestManager:(id)arg1 mapGameStateDataStore:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

