//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "SCManagedLensProcessorStateListener-Protocol.h"

@class NSString, SCLensInitEvent, SCManagedLensProcessorState;

@interface SCLensInitLogger : NSObject <SCManagedLensProcessorStateListener>
{
    SCLensInitEvent *_lensInitEvent;
    SCManagedLensProcessorState *_managedLensProcessorState;
}

@property(retain, nonatomic) SCManagedLensProcessorState *managedLensProcessorState; // @synthesize managedLensProcessorState=_managedLensProcessorState;
@property(retain, nonatomic) SCLensInitEvent *lensInitEvent; // @synthesize lensInitEvent=_lensInitEvent;
- (void).cxx_destruct;
- (void)managedLensProcessor:(id)arg1 didChangeState:(id)arg2;
- (void)logFailureEvent;
- (void)logSuccessEvent;
- (void)setLensSessionId:(id)arg1;
- (void)setCurrentCategoryId:(id)arg1;
- (void)stopLogger;
- (void)startLogger;
@property(readonly, nonatomic, getter=isLoggerRunning) _Bool running;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

