//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface SCLowpassFilter : NSObject
{
    double _filterConstant;
    double _x;
    double _y;
    double _z;
}

@property(readonly, nonatomic) double z; // @synthesize z=_z;
@property(readonly, nonatomic) double y; // @synthesize y=_y;
@property(readonly, nonatomic) double x; // @synthesize x=_x;
- (void)addAcceleration:(id)arg1;
- (id)initWithSampleRate:(double)arg1 cutoffFrequency:(double)arg2;

@end

