//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NavigationController.h"

#import "AVCameraViewControllerDelegate-Protocol.h"
#import "SendSnapNavigationControllerDelegate-Protocol.h"

@class AVCameraViewController, NSString;
@protocol SCMapCameraViewControllerDelegate;

@interface SCMapCameraViewController : NavigationController <AVCameraViewControllerDelegate, SendSnapNavigationControllerDelegate>
{
    id <SCMapCameraViewControllerDelegate> _mapDelegate;
    AVCameraViewController *_rootViewController;
}

@property(readonly, nonatomic) AVCameraViewController *rootViewController; // @synthesize rootViewController=_rootViewController;
@property(nonatomic) __weak id <SCMapCameraViewControllerDelegate> mapDelegate; // @synthesize mapDelegate=_mapDelegate;
- (void).cxx_destruct;
- (void)didPostStory;
- (void)didSendSnaps:(id)arg1;
- (void)didCancelFromPreview:(id)arg1;
- (void)rightCameraBackButtonPressed;
- (void)leftCameraBackButtonPressed;
- (void)setLensId:(id)arg1;
- (void)setFriend:(id)arg1;
- (id)initWithUserSession:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

