//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UIGestureRecognizerDelegate-Protocol.h"

@class CAGradientLayer, NSString, UIScrollView;
@protocol SCMapSwipeToDismissViewDelegate;

@interface SCMapSwipeToDismissView : UIView <UIGestureRecognizerDelegate>
{
    CAGradientLayer *_topFadeOutGradientLayer;
    id <SCMapSwipeToDismissViewDelegate> _delegate;
    UIScrollView *_scrollView;
}

@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(nonatomic) __weak id <SCMapSwipeToDismissViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_springToHidden:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)animateOutWithCompletion:(CDUnknownBlockType)arg1;
- (void)animateInWithCompletion:(CDUnknownBlockType)arg1;
- (_Bool)shouldDismissCardsWithVelocity:(double)arg1 translation:(double)arg2;
- (void)_handlePanGesture:(id)arg1;
- (void)layoutSubviews;
- (_Bool)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

