//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "SCGalleryCollectionViewSelectionHelperDataSource-Protocol.h"
#import "SCGalleryCollectionViewSelectionHelperDelegate-Protocol.h"
#import "SCMediaDrawerTabController-Protocol.h"
#import "SCMergedGalleryDataSourceListener-Protocol.h"
#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegate-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"

@class NSArray, NSMutableDictionary, NSString, SCGalleryCollectionViewSelectionHelper, SCUserSession, UICollectionView, UIPanGestureRecognizer, UIScrollView, UIView;
@protocol SCMediaDrawerTabControllerDelegate;

@interface SCMediaDrawerGalleryTabController : NSObject <UICollectionViewDataSource, UICollectionViewDelegate, UIGestureRecognizerDelegate, SCGalleryCollectionViewSelectionHelperDataSource, SCGalleryCollectionViewSelectionHelperDelegate, SCMergedGalleryDataSourceListener, SCMediaDrawerTabController>
{
    SCUserSession *_userSession;
    NSArray *_publicSnapEntries;
    NSMutableDictionary *_entryIdToCGSizeValueInPoints;
    UICollectionView *_collectionView;
    SCGalleryCollectionViewSelectionHelper *_selectHelper;
    UIPanGestureRecognizer *_panGesture;
    _Bool _isClosingDrawer;
    UIView *_view;
    id <SCMediaDrawerTabControllerDelegate> _delegate;
    double _topMargin;
    double _bottomMargin;
}

@property(nonatomic) double bottomMargin; // @synthesize bottomMargin=_bottomMargin;
@property(nonatomic) double topMargin; // @synthesize topMargin=_topMargin;
@property(nonatomic) __weak id <SCMediaDrawerTabControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_animate:(CDUnknownBlockType)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (void)_handlerDownPan:(id)arg1;
- (void)dataSource:(id)arg1 didChangeEntriesWithNewContentAvailable:(id)arg2;
- (void)dataSource:(id)arg1 didChangeEntries:(id)arg2 failedEntries:(id)arg3;
- (void)didFocusOnTab;
- (void)tabCellWillDisplay;
- (void)scrollToPercent:(double)arg1;
- (void)scrollToDrawerItem:(id)arg1;
- (void)scrollToTopWithTopMargin:(double)arg1;
- (void)updateScrollViewWithTopMargin:(double)arg1 deltaContentOffset:(double)arg2 animated:(_Bool)arg3;
- (void)animateDeselectAll;
- (void)animateDeselectDrawerItem:(id)arg1 isDeselectingLastItem:(_Bool)arg2;
- (void)animateSelectingDrawerItem:(id)arg1;
- (_Bool)galleryCollectionViewIsFullyVisible:(id)arg1;
- (void)galleryCollectionViewSelectionHelper:(id)arg1 handleLongPress:(id)arg2 itemAtIndexPath:(id)arg3 selectionMode:(unsigned long long)arg4;
- (void)galleryCollectionViewSelectionHelper:(id)arg1 didTapItemAtIndexPath:(id)arg2 selectionMode:(unsigned long long)arg3;
- (void)galleryCollectionViewSelectionHelper:(id)arg1 didChangeSelectionMode:(unsigned long long)arg2 atIndexPath:(id)arg3;
- (_Bool)galleryCollectionViewSelectionHelper:(id)arg1 shouldChangeSelectionMode:(unsigned long long)arg2 atIndexPath:(id)arg3;
- (_Bool)galleryCollectionViewSelectionHelper:(id)arg1 isItemInteractionEnabledAtIndexPath:(id)arg2;
- (id)galleryCollectionViewSelectionHelper:(id)arg1 snapsAtIndexPath:(id)arg2;
- (id)galleryCollectionViewSelectionHelper:(id)arg1 galleryItemAtIndexPath:(id)arg2;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (struct CGSize)_sizeInPointsForItemAtIndexPathWithVerticalLayout:(id)arg1;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (void)collectionView:(id)arg1 didEndDisplayingCell:(id)arg2 forItemAtIndexPath:(id)arg3;
- (void)collectionView:(id)arg1 willDisplayCell:(id)arg2 forItemAtIndexPath:(id)arg3;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (unsigned long long)galleryEntryCount;
- (id)itemsInScrollViewRect:(struct CGRect)arg1;
@property(readonly, nonatomic) UIScrollView *scrollView;
@property(readonly, nonatomic) UIView *view; // @synthesize view=_view;
@property(readonly, nonatomic) long long itemType;
- (id)initWithUserSession:(id)arg1 delegate:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

