//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSAttributedString, NSString, UIColor, UIFont;

@protocol SCMessageChatCellViewConfig <NSObject>
- (NSAttributedString *)textForStatusMessageHeaderLabel;
- (_Bool)shouldShowStatusMessageHeaderLabel;
- (UIFont *)headerLabelFont;
- (UIFont *)textLabelFont;
- (_Bool)bottomRightCornerIsRounded;
- (_Bool)topRightCornerIsRounded;
- (_Bool)bottomLeftCornerIsRounded;
- (NSAttributedString *)textForHeaderStatusView;
- (NSString *)textForTimeLabel;
- (NSString *)textForSenderHeaderLabel;
- (NSString *)textForDateHeaderLabel;
- (unsigned long long)textCheckingTypes;
- (_Bool)shouldShowRetryStatusView;
- (_Bool)shouldShowRetryIcon;
- (_Bool)shouldDisplayInBubbleChat;
- (_Bool)shouldShowURLMediaCards;
- (_Bool)shouldShowTimestamp;
- (_Bool)shouldShowSenderHeader;
- (_Bool)shouldShowDateHeader;
- (double)headerLabelHeight;
- (double)payloadHorizontalMargin;
- (double)headerHorizontalMargin;
- (double)bottomMargin;
- (double)dateHeaderHeight;
- (double)headerNoDateHeight;
- (double)headerHeight;
- (double)widthForSenderLine;
- (double)verticalOffsetForBodyView;
- (double)verticalOffsetForSenderHeaderLabel;
- (double)payloadHeight;
- (double)payloadVerticalMargin;
- (double)bodyContentWidth;
- (double)bubbleCellWidth;
- (double)payloadContentWidth;
- (double)payloadWidth;
- (double)bodyWidth;
- (_Bool)isGrayScaleMediaCard;
- (UIColor *)colorForActionText;
- (UIColor *)sectionColor;
- (UIFont *)fontForActionText;
@end

