//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "NSURLSessionDelegate-Protocol.h"

@class NSMutableDictionary, NSString, SCQueuePerformer;
@protocol SCMediaDownloadLogger, SCNetworker;

@interface SCMediaDownload : NSObject <NSURLSessionDelegate>
{
    id <SCMediaDownloadLogger> _logger;
    NSMutableDictionary *_pendingRequestGroups;
    NSMutableDictionary *_inflightRequestGroups;
    // Error parsing type: {atomic<SCMediaScenePath>="__a_"A{?}}, name: _mediaScenePath
    SCQueuePerformer *_performer;
    id <SCNetworker> _networker;
}

@property(readonly, nonatomic) id <SCMediaDownloadLogger> logger; // @synthesize logger=_logger;
@property(readonly, nonatomic) id <SCNetworker> networker; // @synthesize networker=_networker;
@property(readonly, nonatomic) SCQueuePerformer *performer; // @synthesize performer=_performer;
- (void).cxx_destruct;
- (void)_scheduleNextRequestGroup;
- (void)_enqueueRequestGroup:(id)arg1;
- (id)_selectNextRequestGroup;
- (void)_addRequestGroup:(id)arg1;
- (void)setMediaScenePath:(CDStruct_bac8f6e9)arg1;
- (id)downloadMediaForEntity:(id)arg1 mediaScenePath:(CDStruct_bac8f6e9)arg2 queue:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (id)initWithNetworker:(id)arg1 logger:(id)arg2;
- (id)downloadHDMediaForSnap:(id)arg1 mediaScenePath:(CDStruct_bac8f6e9)arg2 fileResolver:(id)arg3 dataObjectContext:(id)arg4 queue:(id)arg5 completionHandler:(CDUnknownBlockType)arg6;
- (id)downloadRenderedLowresMediaForSnap:(id)arg1 mediaScenePath:(CDStruct_bac8f6e9)arg2 fileResolver:(id)arg3 dataObjectContext:(id)arg4 queue:(id)arg5 completionHandler:(CDUnknownBlockType)arg6;
- (id)downloadMediaForSnap:(id)arg1 mediaScenePath:(CDStruct_bac8f6e9)arg2 fileResolver:(id)arg3 dataObjectContext:(id)arg4 queue:(id)arg5 completionHandler:(CDUnknownBlockType)arg6;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

