//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "EphemeralMediaDelegate-Protocol.h"
#import "SCMediaSendTask-Protocol.h"

@class NSDate, NSMutableArray, NSString, SCMediaSendTaskConfiguration, SCMediaSendTaskEphemeralMedia, SCQueuePerformer, Snap, Story;
@protocol SCMediaSendTaskDelegate;

@interface SCMediaIndividualSendTask : NSObject <EphemeralMediaDelegate, SCMediaSendTask>
{
    SCQueuePerformer *_performer;
    SCMediaSendTaskEphemeralMedia *_ephemeralMedia;
    NSString *_ephemeralMediaClientId;
    Snap *_snap;
    Story *_story;
    SCMediaSendTaskConfiguration *_configuration;
    NSMutableArray *_unsentSnapRecipients;
    NSMutableArray *_unsentSnapInviteRecipients;
    NSMutableArray *_completionHandlers;
    _Bool _storyPostedLocally;
    NSDate *_creationTimestamp;
    NSString *_taskId;
    NSString *_feedId;
    id <SCMediaSendTaskDelegate> _delegate;
    long long _taskState;
}

@property(readonly, nonatomic) long long taskState; // @synthesize taskState=_taskState;
@property(nonatomic) __weak id <SCMediaSendTaskDelegate> delegate; // @synthesize delegate=_delegate;
@property(readonly, copy, nonatomic) NSString *feedId; // @synthesize feedId=_feedId;
@property(readonly, copy, nonatomic) NSString *taskId; // @synthesize taskId=_taskId;
- (void).cxx_destruct;
- (void)_ephemeralMediaSendDidSucceedForMediaHelper:(id)arg1 snapIdsAndTimestamps:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)_ephemeralMediaSendDidFailForMediaHelper:(id)arg1;
- (void)ephemeralMediaSendDidSucceedForMedia:(id)arg1 snapIdsAndTimestamps:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (void)ephemeralMediaSendDidFailForMedia:(id)arg1;
- (void)ephemeralMediaUploadDidFailForMedia:(id)arg1;
- (void)ephemeralMediaUploadDidSucceedForMedia:(id)arg1;
- (void)ephemeralMediaUploadDidStartForMedia:(id)arg1;
- (void)_updateFailedSnapState;
- (id)_singleRecipientUsername;
- (_Bool)_isExpired;
- (void)_didCompleteSend:(_Bool)arg1;
- (void)removeCorrespondingMessage;
- (void)prepareToBeRemoved;
- (void)clearInvalidRecipients;
- (id)invalidRecipientsNameString;
- (_Bool)_hasValidMedia;
- (_Bool)isValid;
- (void)updateFeedId;
- (id)groups;
- (id)singleGroupId;
- (_Bool)isRecipientSingleGroupOrUser;
- (_Bool)isSingleRecipient;
- (void)addOrUpdateSendToMessageInConversationWithSendStatus:(long long)arg1;
- (void)finishDecodingWithPerformer:(id)arg1;
- (id)_invitePhoneNumers;
- (void)_addMessageToConversationsWithStatus:(long long)arg1 snapIdsAndTimestamps:(id)arg2;
- (void)_sendSnapAndPostStory;
- (id)_generateFeedId;
- (id)_userRecipientUsernameArray;
@property(readonly, copy) NSString *description;
- (id)multiSnapBundleId;
- (void)didFailToSend;
- (void)sendWithCompletionHandler:(CDUnknownBlockType)arg1 context:(id)arg2;
- (void)_updateRecipients;
- (void)_initSnapWithIsDoublePost:(_Bool)arg1;
- (void)_initStoryWithIsDoublePost:(_Bool)arg1;
- (void)_initSnapAndStory;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithEphemeralMedia:(id)arg1 configuration:(id)arg2 performer:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

