//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCMiniProfileCollectionViewCell.h"

#import "SCSearchEventAnnouncing-Protocol.h"
#import "SCSearchEventListener-Protocol.h"

@class NSString, SCMiniProfileStorySubscribeButton, SCSearchEventListenerAnnouncer, SCSearchNetworkImageView, UILabel;
@protocol SCMiniProfileStoryIdentityCollectionViewCellDelegate;

@interface SCMiniProfileStoryIdentityCollectionViewCell : SCMiniProfileCollectionViewCell <SCSearchEventListener, SCSearchEventAnnouncing>
{
    SCSearchNetworkImageView *_imageView;
    UILabel *_titleLabel;
    UILabel *_subtitleLabel;
    UILabel *_detailTextLabel;
    SCMiniProfileStorySubscribeButton *_addButton;
    id <SCMiniProfileStoryIdentityCollectionViewCellDelegate> _delegate;
    SCSearchEventListenerAnnouncer *_eventAnnouncer;
}

+ (double)heightWithDetailText:(id)arg1;
+ (id)detailTextFont;
+ (id)announcerIdentifier;
- (void).cxx_destruct;
- (void)didTapImageView:(id)arg1;
- (void)layoutSubviews;
- (void)setDelegate:(id)arg1;
- (void)setSubscribeButtonViewModel:(id)arg1 delegate:(id)arg2;
- (void)setImage:(id)arg1 title:(id)arg2 subtitle:(id)arg3 detailText:(id)arg4 imageDownloader:(id)arg5;
- (id)initWithFrame:(struct CGRect)arg1;
- (void)didTriggerEventWithEventName:(id)arg1 announcerIdentifier:(id)arg2 extraData:(id)arg3;
- (void)removeListener:(id)arg1;
- (void)addListener:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

