//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "SCNavigationBarItemTransitionContext-Protocol.h"

@class NSString;

@interface SCNavigationTransitionContext : NSObject <SCNavigationBarItemTransitionContext>
{
    unsigned long long _transitionType;
    unsigned long long _transitionDirection;
    unsigned long long _transitionState;
}

+ (id)contextWithTransitionType:(unsigned long long)arg1 transitionDirection:(unsigned long long)arg2 transitionState:(unsigned long long)arg3;
- (unsigned long long)transitionState;
- (unsigned long long)transitionDirection;
- (unsigned long long)transitionType;
- (id)initWithTransitionType:(unsigned long long)arg1 transitionDirection:(unsigned long long)arg2 transitionState:(unsigned long long)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

