//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

@class NSObject, SCDeepLinkURL, SCLoadingIndicatorView, SCOAuth2ApprovalDataModel, UIImage, UIView;
@protocol OS_dispatch_group, OS_dispatch_queue;

@interface SCOAuth2RootViewController : UIViewController
{
    _Bool _hasError;
    SCLoadingIndicatorView *_loadingIndicator;
    SCDeepLinkURL *_authDeepLinkUrl;
    UIView *_backgroundView;
    UIImage *_largeBitmoji;
    UIImage *_smallBitmoji;
    SCOAuth2ApprovalDataModel *_oauth2ApprovalDataModel;
    NSObject<OS_dispatch_group> *_dispatchGroup;
    NSObject<OS_dispatch_queue> *_dispatchQueue;
}

@property(retain, nonatomic) NSObject<OS_dispatch_queue> *dispatchQueue; // @synthesize dispatchQueue=_dispatchQueue;
@property(retain, nonatomic) NSObject<OS_dispatch_group> *dispatchGroup; // @synthesize dispatchGroup=_dispatchGroup;
@property(nonatomic) _Bool hasError; // @synthesize hasError=_hasError;
@property(retain, nonatomic) SCOAuth2ApprovalDataModel *oauth2ApprovalDataModel; // @synthesize oauth2ApprovalDataModel=_oauth2ApprovalDataModel;
@property(retain, nonatomic) UIImage *smallBitmoji; // @synthesize smallBitmoji=_smallBitmoji;
@property(retain, nonatomic) UIImage *largeBitmoji; // @synthesize largeBitmoji=_largeBitmoji;
@property(retain, nonatomic) UIView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(retain, nonatomic) SCDeepLinkURL *authDeepLinkUrl; // @synthesize authDeepLinkUrl=_authDeepLinkUrl;
@property(retain, nonatomic) SCLoadingIndicatorView *loadingIndicator; // @synthesize loadingIndicator=_loadingIndicator;
- (void).cxx_destruct;
- (void)invokeError:(id)arg1;
- (void)getSmallBitmoji;
- (void)getLargeBitmoji;
- (void)sendAuthRequest;
- (void)verifyAuthRequestAndLoadingBitmoji;
- (void)loadView;
- (id)initWithDeepLinkUrl:(id)arg1;

@end

