//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "MGLMapViewDelegate-Protocol.h"

@class MGLMapView, NSString;

@interface SCOnDemandGeofilterMapPreviewView : UIView <MGLMapViewDelegate>
{
    MGLMapView *_mapView;
}

- (void).cxx_destruct;
- (double)mapView:(id)arg1 alphaForShapeAnnotation:(id)arg2;
- (id)mapView:(id)arg1 fillColorForPolygonAnnotation:(id)arg2;
- (id)mapView:(id)arg1 imageForAnnotation:(id)arg2;
- (void)updateWithGeofence:(id)arg1;
- (void)setupWithMapView:(id)arg1;
- (_Bool)hasMapView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

