//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSString, SCOperaPlaylistItemGroup;

@interface SCOperaPlaylistItem : NSObject
{
    NSString *_type;
    NSString *__id;
    SCOperaPlaylistItemGroup *_group;
}

@property(nonatomic) __weak SCOperaPlaylistItemGroup *group; // @synthesize group=_group;
@property(readonly, copy, nonatomic) NSString *_id; // @synthesize _id=__id;
@property(readonly, copy, nonatomic) NSString *type; // @synthesize type=_type;
- (void).cxx_destruct;
- (id)description;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (id)initWithType:(id)arg1 ID:(id)arg2;

@end

