//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCOperaPlaylistEventTrackerPlugin.h"

#import "SCOperaPlaylistItemExtraPropertiesProvider-Protocol.h"
#import "SCStoryMediaStateListener-Protocol.h"

@class NSMutableSet, NSString, SCOperaViewController, SCStopwatch, SCUserSession;
@protocol SCOperaPlaylistItemController;

@interface SCOperaPlaylistOptOutInterstitialPlugin : SCOperaPlaylistEventTrackerPlugin <SCOperaPlaylistItemExtraPropertiesProvider, SCStoryMediaStateListener>
{
    id <SCOperaPlaylistItemController> _playlistItemController;
    SCOperaViewController *_operaVC;
    SCUserSession *_userSession;
    long long _viewLocation;
    SCStopwatch *_snapViewStopwatch;
    NSMutableSet *_groupIdsWithRemovedOptOutLayerProperties;
    unsigned long long _entryInteractionType;
    unsigned long long _entryGroupIndex;
}

- (void).cxx_destruct;
- (id)_posterIdForContext:(id)arg1;
- (void)_logOptOutInterstitialViewWithEntryInteractionType:(unsigned long long)arg1 exitInteractionType:(unsigned long long)arg2 context:(id)arg3;
- (void)story:(id)arg1 didChangeThumbnailMediaState:(long long)arg2;
- (void)story:(id)arg1 didChangeMediaState:(long long)arg2;
- (CDUnknownBlockType)_thumbnailImageFetchBlockForStory:(id)arg1;
- (id)_extraOptOutInterstitialPropertiesForChunk:(id)arg1 item:(id)arg2;
- (id)_extraOptOutInterstitialPropertiesForStory:(id)arg1 item:(id)arg2;
- (id)_extraOptOutInterstitialPropertiesForPromotedStory:(id)arg1 item:(id)arg2;
- (void)extraPropertiesForDataModel:(id)arg1 item:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (id)extraPropertiesProvider;
- (void)operaViewDidSendEvent:(id)arg1 context:(id)arg2 params:(id)arg3;
- (id)registeredEventsForOperaSession;
- (_Bool)isHighPriorityEventListener;
- (void)setOperaViewController:(id)arg1;
- (void)setPlaylistItemController:(id)arg1;
- (id)initWithUserSession:(id)arg1 viewLocation:(long long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

