//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSMutableArray, NSURL;
@protocol OS_dispatch_source;

@interface SCPingSession : NSObject
{
    NSMutableArray *_pingResultsList;
    NSObject<OS_dispatch_source> *_pingSessionTimer;
    int _numberOfPingResponseReceived;
    _Bool _sessionEnded;
    _Bool _isSessionTimedout;
    double _sessionStartTime;
    CDUnknownBlockType _completionBlock;
    NSURL *_pingURL;
}

@property(readonly, nonatomic) NSURL *pingURL; // @synthesize pingURL=_pingURL;
- (void).cxx_destruct;
- (id)getPingResults;
- (id)getPingResultsJSONString;
- (id)_pingSessionPerformer;
- (void)_updatePingResult:(id)arg1 WithTotalLatency:(long long)arg2 responseSize:(long long)arg3;
- (void)_pingUsingDownloadSession;
- (void)_completeAndTeardownSession;
- (void)_periodicPing;
- (void)endSessionWithCompletionBlock:(CDUnknownBlockType)arg1;
- (id)_createSessionTimerWithInterval:(double)arg1;
- (id)initWithPingURL:(id)arg1 PingInterval:(double)arg2;

@end

