//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSDate, NSNumber, NSString;

@interface SCPreviewFilterItem : NSObject
{
    _Bool _sortOrderDependsOnSwipeDirection;
    NSString *_filterName;
    NSDate *_creationTime;
    long long _filterType;
    NSNumber *_filterScore;
}

+ (id)getGeofilterIdFromName:(id)arg1;
+ (id)unfilteredItem;
+ (id)matchingFilterItemForName:(id)arg1 filterType:(long long)arg2;
+ (id)matchingFilterItemForName:(id)arg1;
+ (id)itemForAutoStacking:(long long)arg1;
+ (id)itemWithFilterName:(id)arg1 filterType:(long long)arg2 sortOrderDependsOnSwipeDirection:(_Bool)arg3;
@property(nonatomic) _Bool sortOrderDependsOnSwipeDirection; // @synthesize sortOrderDependsOnSwipeDirection=_sortOrderDependsOnSwipeDirection;
@property(retain, nonatomic) NSNumber *filterScore; // @synthesize filterScore=_filterScore;
@property(nonatomic) long long filterType; // @synthesize filterType=_filterType;
@property(readonly, nonatomic) NSDate *creationTime; // @synthesize creationTime=_creationTime;
@property(retain, nonatomic) NSString *filterName; // @synthesize filterName=_filterName;
- (void).cxx_destruct;
- (id)description;
- (unsigned long long)hash;
- (_Bool)isEqual:(id)arg1;
- (_Bool)isUnfilteredFilter;
- (id)init;

@end

