//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class SCSettingsStartPage, UINavigationController;
@protocol NavigationDelegate, SCLagunaPairingDelegate, SCSettingsWorkflowDelegate, SCStartChatDelegate;

@protocol SCProfileSubWorkflowsDelegate <NSObject>
- (void)endSettingsWorkflow;
- (void)beginSettingsWorkflowWithDelegate:(id <SCSettingsWorkflowDelegate>)arg1 navigationController:(UINavigationController *)arg2 navigationDelegate:(id <NavigationDelegate>)arg3 pairingDelegate:(id <SCLagunaPairingDelegate>)arg4 startChatDelegate:(id <SCStartChatDelegate>)arg5 startPage:(SCSettingsStartPage *)arg6 shouldShowSettingsAnimated:(_Bool)arg7;
@end

