//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "SCSearchEventAnnouncing-Protocol.h"
#import "SCSearchSectionDataProviding-Protocol.h"

@class NSArray, NSSet, NSString, SCProfileV3SearchQueryModel, SCSearchAddFriendsDataProvider, SCSearchEventListenerAnnouncer, SCSearchSession;
@protocol NSCopying, SCPerforming, SCSearchSectionDataProvidingDelegate;

@interface SCProfileV3AddFriendsSearchSectionDataProvider : NSObject <SCSearchSectionDataProviding, SCSearchEventAnnouncing>
{
    SCSearchSession *_searchSession;
    SCSearchAddFriendsDataProvider *_addFriendsDataProvider;
    SCSearchEventListenerAnnouncer *_eventAnnouncer;
    NSArray *_searchResultsDataModel;
    NSSet *_remoteSearchResults;
    SCProfileV3SearchQueryModel *_queryModel;
    long long _dataLoadingStatus;
    id <SCSearchSectionDataProvidingDelegate> _dataProviderDelegate;
    id <SCPerforming> _updateQueuePerformer;
}

+ (id)announcerIdentifier;
@property(retain, nonatomic) id <SCPerforming> updateQueuePerformer; // @synthesize updateQueuePerformer=_updateQueuePerformer;
@property(nonatomic) __weak id <SCSearchSectionDataProvidingDelegate> dataProviderDelegate; // @synthesize dataProviderDelegate=_dataProviderDelegate;
- (void).cxx_destruct;
- (void)_handleRemoteResponse:(id)arg1;
- (id)configurationBlocksByReuseIdentifier;
- (id)contentCellClassesByReuseIdentifier;
- (void)containerCellViewModelsForIndexPaths:(id)arg1 completionBlock:(CDUnknownBlockType)arg2;
- (unsigned long long)numberOfItemsInSection:(unsigned long long)arg1;
- (long long)dataLoadingStatus;
@property(copy, nonatomic) NSObject<NSCopying> *sectionDataModel;
- (id)initWithSearchSession:(id)arg1;
- (void)removeListener:(id)arg1;
- (void)addListener:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

