//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class NSObject;
@protocol NSCopying, SCProfileHeaderDataProviderDelegate;

@protocol SCProfileHeaderDataProvider
@property(copy, nonatomic) NSObject<NSCopying> *dataModel;
@property(nonatomic) __weak id <SCProfileHeaderDataProviderDelegate> delegate;
- (void)updateViewModelWithCompletionBlock:(void (^)(SCProfileHeaderViewModel *))arg1;
@end

