//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "NSCopying-Protocol.h"

@class NSArray, NSString, SCProfileActionModel;

@interface SCProfileHeaderViewModel : NSObject <NSCopying>
{
    _Bool _shouldSubtitleAnimateBackOnTap;
    NSString *_title;
    NSArray *_subtitleViewModels;
    NSString *_indicatorIconAssetName;
    NSString *_menuIconAssetName;
    SCProfileActionModel *_menuButtonTapActionModel;
    SCProfileActionModel *_dismissButtonTapActionModel;
}

@property(readonly, copy, nonatomic) SCProfileActionModel *dismissButtonTapActionModel; // @synthesize dismissButtonTapActionModel=_dismissButtonTapActionModel;
@property(readonly, copy, nonatomic) SCProfileActionModel *menuButtonTapActionModel; // @synthesize menuButtonTapActionModel=_menuButtonTapActionModel;
@property(readonly, copy, nonatomic) NSString *menuIconAssetName; // @synthesize menuIconAssetName=_menuIconAssetName;
@property(readonly, copy, nonatomic) NSString *indicatorIconAssetName; // @synthesize indicatorIconAssetName=_indicatorIconAssetName;
@property(readonly, nonatomic) _Bool shouldSubtitleAnimateBackOnTap; // @synthesize shouldSubtitleAnimateBackOnTap=_shouldSubtitleAnimateBackOnTap;
@property(readonly, copy, nonatomic) NSArray *subtitleViewModels; // @synthesize subtitleViewModels=_subtitleViewModels;
@property(readonly, copy, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;
- (_Bool)isEqual:(id)arg1;
- (unsigned long long)hash;
- (id)description;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithTitle:(id)arg1 subtitleViewModels:(id)arg2 shouldSubtitleAnimateBackOnTap:(_Bool)arg3 indicatorIconAssetName:(id)arg4 menuIconAssetName:(id)arg5 menuButtonTapActionModel:(id)arg6 dismissButtonTapActionModel:(id)arg7;

@end

