//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "SCProductDetailsCardInformationTableViewCellDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class NSString, SCProductDetailsCardInformationTableViewCell, SCScanProductInfo, SOJUCommerceProductVariant, UIGestureRecognizer, UIScrollView, UITableView, UITableViewCell;
@protocol SCProductDetailsCardViewDelegate;

@interface SCProductDetailsCardView : UIView <UITableViewDelegate, UITableViewDataSource, SCProductDetailsCardInformationTableViewCellDelegate>
{
    _Bool _isOpera;
    _Bool _isProductDetailsSectionCollapsed;
    _Bool _isBouncingCard;
    _Bool _isDescriptionCellConfigured;
    id <SCProductDetailsCardViewDelegate> _delegate;
    UITableView *_tableView;
    SCScanProductInfo *_productInfo;
    SOJUCommerceProductVariant *_selectedOption;
    UIScrollView *_tableViewContainer;
    SCProductDetailsCardInformationTableViewCell *_productInfoTableViewCell;
    UITableViewCell *_infiniteWhiteBackgroundTableViewCell;
    UIView *_infiniteWhiteBackgroundView;
    double _productInfoTableViewCellHeight;
}

+ (double)initialCardHeightForProduct:(id)arg1 isOpera:(_Bool)arg2;
@property(nonatomic) _Bool isDescriptionCellConfigured; // @synthesize isDescriptionCellConfigured=_isDescriptionCellConfigured;
@property(nonatomic) _Bool isBouncingCard; // @synthesize isBouncingCard=_isBouncingCard;
@property(nonatomic) _Bool isProductDetailsSectionCollapsed; // @synthesize isProductDetailsSectionCollapsed=_isProductDetailsSectionCollapsed;
@property double productInfoTableViewCellHeight; // @synthesize productInfoTableViewCellHeight=_productInfoTableViewCellHeight;
@property(retain, nonatomic) UIView *infiniteWhiteBackgroundView; // @synthesize infiniteWhiteBackgroundView=_infiniteWhiteBackgroundView;
@property(retain, nonatomic) UITableViewCell *infiniteWhiteBackgroundTableViewCell; // @synthesize infiniteWhiteBackgroundTableViewCell=_infiniteWhiteBackgroundTableViewCell;
@property(retain, nonatomic) SCProductDetailsCardInformationTableViewCell *productInfoTableViewCell; // @synthesize productInfoTableViewCell=_productInfoTableViewCell;
@property(retain, nonatomic) UIScrollView *tableViewContainer; // @synthesize tableViewContainer=_tableViewContainer;
@property(nonatomic) __weak SOJUCommerceProductVariant *selectedOption; // @synthesize selectedOption=_selectedOption;
@property(nonatomic) _Bool isOpera; // @synthesize isOpera=_isOpera;
@property(nonatomic) __weak SCScanProductInfo *productInfo; // @synthesize productInfo=_productInfo;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) __weak id <SCProductDetailsCardViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)productDetailsCardInformationTableViewCell:(id)arg1 didUpdateWebviewHeight:(double)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)_toggleProductDetails;
- (id)_variantCellForTable:(id)arg1 indexPath:(id)arg2;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
@property(readonly, nonatomic) UIGestureRecognizer *tablePanGestureRecognizer;
- (void)layoutSubviews;
- (void)bounceCard:(CDUnknownBlockType)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

