//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface SCPrefetchWithoutJSExperimentHelper : NSObject
{
}

+ (_Bool)_enableBlockImagePreloadingForPreloadingOptIn:(id)arg1;
+ (_Bool)_enablePrefetchingWithoutJSForPreloadingOptIn:(id)arg1;
+ (_Bool)_enableBlockImagePreloadingWithPreloadingOptOut:(id)arg1;
+ (_Bool)_enablePrefetchingWithoutJSForPreloadingOptOut:(id)arg1;
+ (_Bool)_getEnableValueFromTweakAndExperiment:(unsigned long long)arg1 abTestingValue:(_Bool)arg2;
+ (id)getPropertiesForPrefetchWithoutJSExperiment:(id)arg1 item:(id)arg2 blockWebviewPreloadingByAdServer:(_Bool)arg3;

@end

