//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCDynamicGeoFilterResource.h"

@class SOJUGeofilterMarkup, SOJUUnlockablesRatingStickerProperties;
@protocol SCPerforming;

@interface SCRatingStickerResource : SCDynamicGeoFilterResource
{
    SOJUUnlockablesRatingStickerProperties *ratingStickerProperties;
    id <SCPerforming> _performer;
    SOJUGeofilterMarkup *_geofilterMarkup;
}

@property(retain, nonatomic) SOJUGeofilterMarkup *geofilterMarkup; // @synthesize geofilterMarkup=_geofilterMarkup;
- (void).cxx_destruct;
- (void)getRatingAssetsWithCompletion:(CDUnknownBlockType)arg1;
- (void)getUIImagesWithCanvasSize:(struct CGSize)arg1 completion:(CDUnknownBlockType)arg2 contextData:(id)arg3 dynamicContextProperties:(id)arg4;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)setupWithGeofilterMarkup:(id)arg1;
- (id)initWithGeofilterMarkup:(id)arg1;
- (id)initWithDictionary:(id)arg1;

@end

