//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCSavableItemChatViewModel.h"

#import "SCCompositeMessageViewModel-Protocol.h"
#import "SCSavableItemChatCellViewConfig-Protocol.h"

@class NSString, SCBaseMediaThumbnailViewModel, SCMessageChatViewModel, SCStoryChromeViewModel;

@interface SCReplyMessageViewModel : SCSavableItemChatViewModel <SCCompositeMessageViewModel, SCSavableItemChatCellViewConfig>
{
    SCMessageChatViewModel *_replyMessagePayloadViewModel;
    SCBaseMediaThumbnailViewModel *_replyMediaThumbnailViewModel;
    SCStoryChromeViewModel *_storyChromeViewModel;
}

@property(readonly, nonatomic) SCStoryChromeViewModel *storyChromeViewModel; // @synthesize storyChromeViewModel=_storyChromeViewModel;
@property(readonly, nonatomic) SCBaseMediaThumbnailViewModel *replyMediaThumbnailViewModel; // @synthesize replyMediaThumbnailViewModel=_replyMediaThumbnailViewModel;
@property(retain, nonatomic) SCMessageChatViewModel *replyMessagePayloadViewModel; // @synthesize replyMessagePayloadViewModel=_replyMessagePayloadViewModel;
- (void).cxx_destruct;
- (_Bool)isEqual:(id)arg1;
- (void)updateMessageState:(id)arg1;
- (double)thumbnailWidth;
- (double)thumbnailHeight;
- (void)refreshViewModel;
- (double)bodyContentWidth;
- (double)payloadVerticalMargin;
- (double)payloadWidth;
- (double)payloadHeight;
- (_Bool)_compareFirstSourceId:(id)arg1 toSecondSourceId:(id)arg2 andFirstKey:(id)arg3 toSecondKey:(id)arg4;
- (_Bool)shouldUpdateViewModelWithMessage:(id)arg1;
- (void)updatePayloadViewModel:(id)arg1;
- (id)payloadViewModel;
- (id)createChatCellWithParentVC:(id)arg1 delegate:(id)arg2;
- (id)reusableCellIdentifier;
- (void)_initializeViewModelsWithMessage:(id)arg1;
- (id)initWithMessage:(id)arg1 metadata:(id)arg2 props:(id)arg3 payloadViewModel:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

