//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCBaseMediaMessageOperaDataSource.h"

#import "SCChatConversationStoreListener-Protocol.h"

@class NSMutableArray, NSMutableDictionary, NSString, SCChatMediaContent, SCChatMessageV3, SCOperaViewModel;
@protocol SCOperaGifProvider><SCOperaImageProvider;

@interface SCReplyChatMediaOperaDataSource : SCBaseMediaMessageOperaDataSource <SCChatConversationStoreListener>
{
    NSMutableArray *_viewModels;
    NSMutableArray *_auxilliaryViewModels;
    NSMutableDictionary *_viewModelDictionary;
    SCChatMessageV3 *_message;
    NSString *_consistentId;
    SCChatMediaContent *_chatMediaContent;
    _Bool _shouldEnableZoom;
    _Bool _containsMultipleMedias;
    _Bool _needToAnimationBaseThumbnailViewWhenClosing;
    NSString *_conversationId;
    SCOperaViewModel *_rootViewModel;
    id <SCOperaGifProvider><SCOperaImageProvider> _imageProvider;
    long long _messageType;
}

- (long long)messageType;
- (id)imageProvider;
- (void)setRootViewModel:(id)arg1;
- (id)rootViewModel;
- (_Bool)needToAnimationBaseThumbnailViewWhenClosing;
- (_Bool)containsMultipleMedias;
- (_Bool)shouldEnableZoom;
- (id)conversationId;
- (void).cxx_destruct;
- (void)diskLoadFinished;
- (void)conversationDidUpdate:(id)arg1 withMetadataDictionary:(id)arg2;
- (void)_unarchiveMediaContentIfNecessary:(id)arg1;
- (void)_createOperaViewModelsFromChatMediaContent:(id)arg1 message:(id)arg2;
- (_Bool)presentingMessage;
- (void)updateViewModelForMedia:(id)arg1;
- (id)viewModelForPageId:(id)arg1;
- (id)messageIdForPage:(id)arg1;
- (void)setRootIndex:(unsigned long long)arg1;
- (id)initWithMessage:(id)arg1 metadata:(id)arg2;
- (id)initWithChatMediaContent:(id)arg1 message:(id)arg2 metadata:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

