//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class SCSessionRequestManager, SCUnlockableDataStore, SCUserSession;

@interface SCScannableUserUnlocker : NSObject
{
    SCSessionRequestManager *_requestManager;
    SCUnlockableDataStore *_unlockableDataStore;
    SCUserSession *_userSession;
}

- (void).cxx_destruct;
- (void)unlockStickerPackWithUnlockableId:(id)arg1 successBlock:(CDUnknownBlockType)arg2 failureBlock:(CDUnknownBlockType)arg3;
- (void)unlockWithDeepLinkURL:(id)arg1 object:(id)arg2 filterId:(id)arg3 companionLens:(id)arg4 unlockProperties:(id)arg5 completion:(CDUnknownBlockType)arg6;
- (void)unlockWithDeepLinkURL:(id)arg1 lens:(id)arg2 filterId:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (id)initWithUserSession:(id)arg1;

@end

