//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCSearchCollectionViewCell.h"

#import "SCSearchActionable-Protocol.h"

@class NSString, SCLazy, SCSearchActionModel, UIImageView, UILabel;
@protocol SCSearchActionHandling;

@interface SCSearchBusinessHourCollectionViewCell : SCSearchCollectionViewCell <SCSearchActionable>
{
    UIImageView *_iconImageView;
    UILabel *_displayLabel;
    SCLazy *_expandButtonLazyCreator;
    SCLazy *_daysLabel;
    SCLazy *_hoursLabel;
    SCSearchActionModel *_singleTapActionModel;
    id <SCSearchActionHandling> _actionHandler;
    id _viewModel;
}

+ (struct CGSize)sizeWithViewModel:(id)arg1 constrainedToSize:(struct CGSize)arg2;
- (id)viewModel;
@property(retain, nonatomic) id <SCSearchActionHandling> actionHandler; // @synthesize actionHandler=_actionHandler;
- (void).cxx_destruct;
- (void)_setupBusinessHourExpansionWithViewModel:(id)arg1;
- (void)_compareAndUpdateViewModelIfNeeded:(id)arg1;
- (void)setHighlighted:(_Bool)arg1;
- (_Bool)hasOverridedLongPressAction;
- (void)handleTapAction;
- (_Bool)hasOverridedTapAction;
- (void)setViewModel:(id)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

