//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCScopeCoordinator.h"

@class SCActiveUserSessionScope, SCSettingsScope, SCSettingsWorkflow, SCSystemScope;

@interface SCSettingsScopeCoordinator : SCScopeCoordinator
{
    SCSettingsWorkflow *_settingsWorkflow;
    SCSystemScope *_systemScope;
    SCActiveUserSessionScope *_activeUserSessionScope;
    SCSettingsScope *_settingsScope;
}

@property(nonatomic) __weak SCSettingsScope *settingsScope; // @synthesize settingsScope=_settingsScope;
@property(nonatomic) __weak SCActiveUserSessionScope *activeUserSessionScope; // @synthesize activeUserSessionScope=_activeUserSessionScope;
@property(nonatomic) __weak SCSystemScope *systemScope; // @synthesize systemScope=_systemScope;
- (void).cxx_destruct;
- (void)begin;

@end

