//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "SCSearchDiscoverCellViewModel-Protocol.h"

@class NSString, SCSearchActionModel;

@interface SCSearchDiscoverCellViewModel : NSObject <SCSearchDiscoverCellViewModel>
{
    _Bool _hasLeftStory;
    _Bool _isCoverLoaded;
    _Bool _isLogoLoaded;
    NSString *_tileId;
    SCSearchActionModel *_tapActionModel;
    SCSearchActionModel *_longPressActionModel;
}

+ (unsigned long long *)fasterCodingKeys;
+ (unsigned long long)fasterCodingVersion;
@property(readonly, copy, nonatomic) SCSearchActionModel *longPressActionModel; // @synthesize longPressActionModel=_longPressActionModel;
@property(readonly, copy, nonatomic) SCSearchActionModel *tapActionModel; // @synthesize tapActionModel=_tapActionModel;
@property(readonly, nonatomic) _Bool isLogoLoaded; // @synthesize isLogoLoaded=_isLogoLoaded;
@property(readonly, nonatomic) _Bool isCoverLoaded; // @synthesize isCoverLoaded=_isCoverLoaded;
@property(readonly, nonatomic) _Bool hasLeftStory; // @synthesize hasLeftStory=_hasLeftStory;
@property(readonly, copy, nonatomic) NSString *tileId; // @synthesize tileId=_tileId;
- (void).cxx_destruct;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
- (_Bool)isEqual:(id)arg1;
- (void)setBool:(_Bool)arg1 forUInt64Key:(unsigned long long)arg2;
- (void)setObject:(id)arg1 forUInt64Key:(unsigned long long)arg2;
- (void)decodeWithFasterDecoder:(id)arg1;
- (void)encodeWithFasterCoder:(id)arg1;
- (_Bool)preferFasterCoding;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithTileId:(id)arg1 hasLeftStory:(_Bool)arg2 isCoverLoaded:(_Bool)arg3 isLogoLoaded:(_Bool)arg4 tapActionModel:(id)arg5 longPressActionModel:(id)arg6;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

