//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "SCSafeBrowsingWarningViewDelegate-Protocol.h"
#import "SCSearchGCardFullScreenTransitionControllerDelegate-Protocol.h"
#import "SCSearchWebViewNavigationTrackerDelegate-Protocol.h"
#import "UIGestureRecognizerDelegate-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"

@class NSString, SCSafeBrowsingWarningView, SCSearchGCardFullScreenTransitionController, SCSearchResultGCardCell, SCSearchWebViewNavigationTracker;

@interface SCSearchGCardFullScreenViewController : UIViewController <UIScrollViewDelegate, SCSearchGCardFullScreenTransitionControllerDelegate, SCSearchWebViewNavigationTrackerDelegate, SCSafeBrowsingWarningViewDelegate, UIGestureRecognizerDelegate>
{
    SCSearchGCardFullScreenTransitionController *_transitionController;
    _Bool _navigatedWithinWebView;
    SCSearchWebViewNavigationTracker *_webViewNavigationTracker;
    SCSafeBrowsingWarningView *_safeBrowsingWarningView;
    SCSearchResultGCardCell *_sourceView;
}

@property(retain, nonatomic) SCSearchResultGCardCell *sourceView; // @synthesize sourceView=_sourceView;
- (void).cxx_destruct;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (void)webViewNavigationTracker:(id)arg1 didNavigateToDeepLink:(id)arg2 isInternalDeeplink:(_Bool)arg3;
- (void)webViewNavigationTracker:(id)arg1 didCheckSafeBrowsingForURL:(id)arg2 urlType:(long long)arg3;
- (void)webViewNavigationTracker:(id)arg1 didLoadEstimatedProgress:(double)arg2;
- (void)webViewNavigationTrackerDidUpdate:(id)arg1;
- (void)learnMoreFromSafeBrowsing;
- (void)goBackFromSafeBrowsing;
- (void)dismissWebViewController;
- (void)scrollViewDidScroll:(id)arg1;
- (void)presentFromView:(id)arg1 presentingController:(id)arg2;
- (void)viewDidLoad;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 withView:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

