//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "SCSearchTranslationDrivenInteractiveTransitioning-Protocol.h"
#import "UIViewControllerAnimatedTransitioning-Protocol.h"

@class NSString, SCSearchNavigationTransitionContext;

@interface SCSearchMetaStoryTransitionController : NSObject <UIViewControllerAnimatedTransitioning, SCSearchTranslationDrivenInteractiveTransitioning>
{
    SCSearchNavigationTransitionContext *_transitionContext;
    _Bool _isPresenting;
    double _metaStoryViewOriginalOffsetY;
}

- (void).cxx_destruct;
- (void)_handleAnimationCompletion;
- (void)_prepareTransition;
- (void)finishInteractiveTransition;
- (void)cancelInteractiveTransition;
- (void)updateInteractiveTransitionWithTransitionY:(double)arg1;
- (void)startInteractiveTransition:(id)arg1;
- (void)animateTransition:(id)arg1;
- (double)transitionDuration:(id)arg1;
- (id)initWithIsPresenting:(_Bool)arg1;

// Remaining properties
@property(readonly, nonatomic) long long completionCurve;
@property(readonly, nonatomic) double completionSpeed;
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;
@property(readonly, nonatomic) _Bool wantsInteractiveStart;

@end

