//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSString, SCShapeView, UILabel;
@protocol SCSearchSeeMoreViewDelegate;

@interface SCSearchSeeMoreView : UIView
{
    SCShapeView *_backgroundView;
    UILabel *_viewMoreLabel;
    _Bool _highlighted;
    long long _style;
    unsigned long long _roundedCorner;
    id <SCSearchSeeMoreViewDelegate> _delegate;
}

+ (struct CGSize)preferredSizeWithConstrainedSize:(struct CGSize)arg1;
@property(nonatomic) __weak id <SCSearchSeeMoreViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool highlighted; // @synthesize highlighted=_highlighted;
@property(nonatomic) unsigned long long roundedCorner; // @synthesize roundedCorner=_roundedCorner;
@property(nonatomic) long long style; // @synthesize style=_style;
- (void).cxx_destruct;
- (void)_updateWithStyle;
- (void)_onTap;
@property(copy, nonatomic) NSString *text;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

