//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "SCCachingMediaSimpleEntity-Protocol.h"

@class NSData, NSDate, NSDictionary, NSString, SCClientEncryption, SCStoryMediaCache;
@protocol MediaDataSource, OS_dispatch_group;

@interface SCSingleIconCacheEntity : NSObject <SCCachingMediaSimpleEntity>
{
    NSString *_thumbnailKey;
    NSString *_UUID;
    NSDictionary *_encryptionDictionary;
    SCClientEncryption *_encryptor;
    NSDate *_expiration;
    NSData *_data;
    SCStoryMediaCache *_storyMediaCache;
    id <MediaDataSource> _cacheDataSource;
    _Bool _success;
    NSObject<OS_dispatch_group> *_group;
}

- (void).cxx_destruct;
- (id)cachingMediaManager:(id)arg1 sourceImagesResultHandler:(CDUnknownBlockType)arg2;
- (void)resultForData:(id)arg1 success:(_Bool)arg2;
- (unsigned long long)imageFormat;
- (id)UUID;
- (id)initWithThumbnailKey:(id)arg1 encryptionDictionary:(id)arg2 encryptor:(id)arg3 expiration:(id)arg4 cacheDataSource:(id)arg5 thumbnailState:(long long)arg6;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

