//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCSingleIconViewBase.h"

@class SCLoadingIndicatorView, UIView;

@interface SCSingleIconView : SCSingleIconViewBase
{
    SCLoadingIndicatorView *_loadingSpinner;
    UIView *_borderView;
}

@property(retain, nonatomic) UIView *borderView; // @synthesize borderView=_borderView;
@property(retain, nonatomic) SCLoadingIndicatorView *loadingSpinner; // @synthesize loadingSpinner=_loadingSpinner;
- (void).cxx_destruct;
- (void)setSpinnerProgress:(double)arg1 animated:(_Bool)arg2;
- (void)showSpinner;
- (void)hideSpinner;
- (void)layoutSubviews;
- (void)prepareForReuse;
- (void)setImageAlpha:(double)arg1;
- (void)configureBorderedThumbnailWithBorderWidth:(double)arg1 inset:(double)arg2 alpha:(double)arg3;
- (id)initWithType:(unsigned long long)arg1 frame:(struct CGRect)arg2;

@end

