//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPBMessage.h"

@class SCSLIGenericEvent, SCSLIStoryFeedItemAction, SCSLIStoryFeedItemLongImpression, SCSLIStoryFeedItemViewSession;

@interface SCSLIEvent : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(readonly, nonatomic) int eventOneOfCase; // @dynamic eventOneOfCase;
@property(retain, nonatomic) SCSLIGenericEvent *generic; // @dynamic generic;
@property(retain, nonatomic) SCSLIStoryFeedItemAction *storyFeedItemAction; // @dynamic storyFeedItemAction;
@property(retain, nonatomic) SCSLIStoryFeedItemLongImpression *storyFeedItemLongImpression; // @dynamic storyFeedItemLongImpression;
@property(retain, nonatomic) SCSLIStoryFeedItemViewSession *storyFeedItemViewSession; // @dynamic storyFeedItemViewSession;
@property(nonatomic) long long timestampMsecs; // @dynamic timestampMsecs;

@end

