//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "SCSnapCashPaymentV3-Protocol.h"

@class NSArray, NSNumber, NSString;

@interface SCSnapCashPaymentV3 : NSObject <SCSnapCashPaymentV3>
{
    _Bool _isSwipeToSend;
    _Bool _didSwipePaymentRainPresent;
    _Bool _sentByUser;
    NSString *_conversationId;
    NSString *_transactionId;
    NSArray *_blockers;
    NSString *_cvv;
    NSString *_senderUsername;
    NSString *_senderId;
    NSString *_recipientUsername;
    NSString *_recipientId;
    long long _paymentStatus;
    long long _sendStatus;
    long long _sendAction;
    NSArray *_cashTagRanges;
    NSNumber *_amount;
    NSString *_currencyCode;
    NSString *_signature;
}

+ (unsigned long long *)fasterCodingKeys;
+ (unsigned long long)fasterCodingVersion;
+ (id)cashTagsJsonFromRanges:(id)arg1;
+ (id)_stateDescriptionForUsername:(id)arg1;
+ (_Bool)didFriendRelease:(id)arg1;
+ (_Bool)didUserReleaseCash:(id)arg1;
+ (_Bool)didReleaseCash:(id)arg1;
@property(readonly, nonatomic) _Bool sentByUser; // @synthesize sentByUser=_sentByUser;
@property(readonly, nonatomic) _Bool didSwipePaymentRainPresent; // @synthesize didSwipePaymentRainPresent=_didSwipePaymentRainPresent;
@property(readonly, nonatomic) _Bool isSwipeToSend; // @synthesize isSwipeToSend=_isSwipeToSend;
@property(readonly, copy, nonatomic) NSString *signature; // @synthesize signature=_signature;
@property(readonly, copy, nonatomic) NSString *currencyCode; // @synthesize currencyCode=_currencyCode;
@property(readonly, copy, nonatomic) NSNumber *amount; // @synthesize amount=_amount;
@property(readonly, copy, nonatomic) NSArray *cashTagRanges; // @synthesize cashTagRanges=_cashTagRanges;
@property(readonly, nonatomic) long long sendAction; // @synthesize sendAction=_sendAction;
@property(readonly, nonatomic) long long sendStatus; // @synthesize sendStatus=_sendStatus;
@property(readonly, nonatomic) long long paymentStatus; // @synthesize paymentStatus=_paymentStatus;
@property(readonly, copy, nonatomic) NSString *recipientId; // @synthesize recipientId=_recipientId;
@property(readonly, copy, nonatomic) NSString *recipientUsername; // @synthesize recipientUsername=_recipientUsername;
@property(readonly, copy, nonatomic) NSString *senderId; // @synthesize senderId=_senderId;
@property(readonly, copy, nonatomic) NSString *senderUsername; // @synthesize senderUsername=_senderUsername;
@property(readonly, copy, nonatomic) NSString *cvv; // @synthesize cvv=_cvv;
@property(readonly, copy, nonatomic) NSArray *blockers; // @synthesize blockers=_blockers;
@property(readonly, copy, nonatomic) NSString *transactionId; // @synthesize transactionId=_transactionId;
@property(readonly, copy, nonatomic) NSString *conversationId; // @synthesize conversationId=_conversationId;
- (void).cxx_destruct;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
- (_Bool)isEqual:(id)arg1;
- (void)setSInt32:(int)arg1 forUInt64Key:(unsigned long long)arg2;
- (void)setBool:(_Bool)arg1 forUInt64Key:(unsigned long long)arg2;
- (void)setObject:(id)arg1 forUInt64Key:(unsigned long long)arg2;
- (void)decodeWithFasterDecoder:(id)arg1;
- (void)encodeWithFasterCoder:(id)arg1;
- (_Bool)preferFasterCoding;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithConversationId:(id)arg1 transactionId:(id)arg2 blockers:(id)arg3 cvv:(id)arg4 senderUsername:(id)arg5 senderId:(id)arg6 recipientUsername:(id)arg7 recipientId:(id)arg8 paymentStatus:(long long)arg9 sendStatus:(long long)arg10 sendAction:(long long)arg11 cashTagRanges:(id)arg12 amount:(id)arg13 currencyCode:(id)arg14 signature:(id)arg15 isSwipeToSend:(_Bool)arg16 didSwipePaymentRainPresent:(_Bool)arg17 sentByUser:(_Bool)arg18;
- (id)getRecipientStatementDescription;
- (id)getSenderStatementDescription;
- (_Bool)isDeclined;
- (_Bool)isSent;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

