//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "NSCoding-Protocol.h"
#import "NSCopying-Protocol.h"

@class NSArray, NSDictionary, NSNumber, NSString, SCSnapAdsIdentifier, SOJUAdClientRankingModel, SOJUAdTfRankingModel;

@interface SCSnapAdsAdResponse : NSObject <NSCopying, NSCoding>
{
    _Bool _blockWebviewPreloading;
    _Bool _shouldLoopStoryAd;
    CDUnknownBlockType _mediaFetchSuccess;
    CDUnknownBlockType _mediaFetchFailure;
    SCSnapAdsIdentifier *_identifier;
    NSString *_adKey;
    NSString *_adId;
    NSString *_adLineItemId;
    long long _adType;
    NSString *_placementId;
    double _timeStampMillis;
    NSArray *_mediaUrls;
    unsigned long long _adProductType;
    NSString *_adSlugOverride;
    NSString *_brandName;
    NSString *_headline;
    NSDictionary *_responseJsonDict;
    NSArray *_adSnapTypes;
    NSArray *_adSnapKeys;
    NSArray *_mediaDurationsMillis;
    SOJUAdClientRankingModel *_clientRankingModel;
    SOJUAdTfRankingModel *_tfRankingModel;
    NSString *_tileImageUrl;
    NSNumber *_tileImageHorizontalCropPctOffset;
    NSNumber *_tileImageCollapsedCropPctOffset;
    NSString *_tileLogoUrl;
    NSString *_tileHeadline;
    long long _adStreamPosition;
}

@property(nonatomic) long long adStreamPosition; // @synthesize adStreamPosition=_adStreamPosition;
@property(readonly, nonatomic) _Bool shouldLoopStoryAd; // @synthesize shouldLoopStoryAd=_shouldLoopStoryAd;
@property(readonly, copy, nonatomic) NSString *tileHeadline; // @synthesize tileHeadline=_tileHeadline;
@property(readonly, copy, nonatomic) NSString *tileLogoUrl; // @synthesize tileLogoUrl=_tileLogoUrl;
@property(readonly, nonatomic) NSNumber *tileImageCollapsedCropPctOffset; // @synthesize tileImageCollapsedCropPctOffset=_tileImageCollapsedCropPctOffset;
@property(readonly, nonatomic) NSNumber *tileImageHorizontalCropPctOffset; // @synthesize tileImageHorizontalCropPctOffset=_tileImageHorizontalCropPctOffset;
@property(readonly, copy, nonatomic) NSString *tileImageUrl; // @synthesize tileImageUrl=_tileImageUrl;
@property(readonly, nonatomic) _Bool blockWebviewPreloading; // @synthesize blockWebviewPreloading=_blockWebviewPreloading;
@property(readonly, copy, nonatomic) SOJUAdTfRankingModel *tfRankingModel; // @synthesize tfRankingModel=_tfRankingModel;
@property(readonly, copy, nonatomic) SOJUAdClientRankingModel *clientRankingModel; // @synthesize clientRankingModel=_clientRankingModel;
@property(readonly, copy, nonatomic) NSArray *mediaDurationsMillis; // @synthesize mediaDurationsMillis=_mediaDurationsMillis;
@property(readonly, copy, nonatomic) NSArray *adSnapKeys; // @synthesize adSnapKeys=_adSnapKeys;
@property(readonly, copy, nonatomic) NSArray *adSnapTypes; // @synthesize adSnapTypes=_adSnapTypes;
@property(readonly, copy, nonatomic) NSDictionary *responseJsonDict; // @synthesize responseJsonDict=_responseJsonDict;
@property(readonly, copy, nonatomic) NSString *headline; // @synthesize headline=_headline;
@property(readonly, copy, nonatomic) NSString *brandName; // @synthesize brandName=_brandName;
@property(readonly, copy, nonatomic) NSString *adSlugOverride; // @synthesize adSlugOverride=_adSlugOverride;
@property(readonly, nonatomic) unsigned long long adProductType; // @synthesize adProductType=_adProductType;
@property(readonly, copy, nonatomic) NSArray *mediaUrls; // @synthesize mediaUrls=_mediaUrls;
@property(readonly, nonatomic) double timeStampMillis; // @synthesize timeStampMillis=_timeStampMillis;
@property(readonly, copy, nonatomic) NSString *placementId; // @synthesize placementId=_placementId;
@property(readonly, nonatomic) long long adType; // @synthesize adType=_adType;
@property(readonly, copy, nonatomic) NSString *adLineItemId; // @synthesize adLineItemId=_adLineItemId;
@property(readonly, copy, nonatomic) NSString *adId; // @synthesize adId=_adId;
@property(readonly, copy, nonatomic) NSString *adKey; // @synthesize adKey=_adKey;
@property(readonly, nonatomic) SCSnapAdsIdentifier *identifier; // @synthesize identifier=_identifier;
@property(copy, nonatomic) CDUnknownBlockType mediaFetchFailure; // @synthesize mediaFetchFailure=_mediaFetchFailure;
@property(copy, nonatomic) CDUnknownBlockType mediaFetchSuccess; // @synthesize mediaFetchSuccess=_mediaFetchSuccess;
- (void).cxx_destruct;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (_Bool)getShouldLoopStoryAd;
- (id)getTileHeadline;
- (id)getTileLogoUrl;
- (id)getTileImageCollapsedCropPctOffset;
- (id)getTileImageHorizontalCropPctOffset;
- (id)getTileImageUrl;
- (_Bool)shouldBlockWebviewPreloading;
- (id)getEndpoint;
- (_Bool)isSuccess;
- (id)getAdRequestClientId;
- (long long)getAdStreamPosition;
- (id)getAdPlacementId;
- (_Bool)isExpiredWithTTL:(double)arg1 withNow:(double)arg2;
- (id)endpointAtIndex:(long long)arg1;
- (id)getAdKeyFromEndpoint:(id)arg1;
- (id)getAdKeyAtIndex:(long long)arg1;
- (id)getDataAtIndex:(long long)arg1;
- (_Bool)isStoryAd;
- (id)getTfRankingModel;
- (id)getClientRankingModel;
- (id)getAdSnapKeys;
- (id)getAdSnapTypes;
- (id)getResponseJsonDict;
- (id)getHeadline;
- (id)getBrandName;
- (id)getAdSlugOverride;
- (unsigned long long)getAdProductType;
- (_Bool)isNoFill;
- (id)getMediaDurationsMillis;
- (long long)getMediaDurationMillis;
- (double)getTimeStampMillis;
- (id)getPlacementId;
- (long long)getAdType;
- (id)getAdLineItemId;
- (id)getAdId;
- (id)getAdKey;
- (id)getMediaUrls;
- (id)getIdentifier;
- (id)initWithSnapAdsIdentifier:(id)arg1 adKey:(id)arg2 adId:(id)arg3 adLineItemId:(id)arg4 mediaUrls:(id)arg5 adType:(long long)arg6 placementId:(id)arg7 mediaDurationsMillis:(id)arg8 adProductType:(unsigned long long)arg9 adSlugOverride:(id)arg10 brandName:(id)arg11 headline:(id)arg12 responseJsonDict:(id)arg13 adSnapTypes:(id)arg14 adSnapKeys:(id)arg15 clientRankingModel:(id)arg16 tfRankingModel:(id)arg17 blockWebviewPreloading:(_Bool)arg18 tileImageUrl:(id)arg19 tileImageHorizontalCropPctOffset:(id)arg20 tileImageCollapsedCropPctOffset:(id)arg21 tileLogoUrl:(id)arg22 tileHeadline:(id)arg23 shouldLoopStoryAd:(_Bool)arg24;

@end

