//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class SCLoadingIndicatorView, SCStoryIconView, UILabel;

@interface SCSnapAdsPortalEntityView : UIView
{
    UIView *_viewContainer;
    UILabel *_primaryLabel;
    UILabel *_secondaryLabel;
    UIView *_statusCircle;
    SCStoryIconView *_thumbnailView;
    UILabel *_metricSummaryLabel;
    UIView *_separator;
    SCLoadingIndicatorView *_loadingIndicator;
    UILabel *_notAvailableLabel;
    _Bool _isHeaderView;
}

- (void).cxx_destruct;
- (id)thumbnailView;
- (id)notAvailableLabel;
- (id)loadingIndicator;
- (id)dismissThumbnailBaseView;
- (void)updateAdThumbnailViewForAdEntity:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)showEntityListNotAvailable:(_Bool)arg1;
- (void)showLoadingIndicator:(_Bool)arg1;
- (void)bindWithEntity:(id)arg1 isHeaderView:(_Bool)arg2;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

