//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class SCSnapCashBlocker, SCSnapCashPaymentV3, SCUserSession;
@protocol SCChatMessageActionHandler;

@interface SCSnapCashBlockerResolver : NSObject
{
    SCUserSession *_userSession;
    SCSnapCashBlocker *_blocker;
    SCSnapCashPaymentV3 *_payment;
    id <SCChatMessageActionHandler> _actionHandler;
}

@property(nonatomic) __weak id <SCChatMessageActionHandler> actionHandler; // @synthesize actionHandler=_actionHandler;
@property(retain, nonatomic) SCSnapCashPaymentV3 *payment; // @synthesize payment=_payment;
@property(retain, nonatomic) SCSnapCashBlocker *blocker; // @synthesize blocker=_blocker;
- (void).cxx_destruct;
- (long long)blockerType;
- (void)resolveBlockerWithDelegate:(id)arg1;
- (id)getViewController;
- (id)initWithBlocker:(id)arg1 payment:(id)arg2 actionHandler:(id)arg3 userSession:(id)arg4;

@end

