//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "SCSnapAdsPortalMetricTabBarDelegate-Protocol.h"

@class NSArray, NSString, SCSnapAdsPortalHierarchyPageController, SCSnapAdsPortalMetricTabBar;

@interface SCSnapAdsPortalMetricTabBarController : NSObject <SCSnapAdsPortalMetricTabBarDelegate>
{
    NSArray *_metricTabs;
    unsigned long long _focusedMetricType;
    SCSnapAdsPortalHierarchyPageController *_parentViewController;
    SCSnapAdsPortalMetricTabBar *_tabBar;
}

@property(readonly, nonatomic) SCSnapAdsPortalMetricTabBar *tabBar; // @synthesize tabBar=_tabBar;
- (void).cxx_destruct;
- (void)didSelectMetricTabAtIndex:(long long)arg1;
- (void)_updateWithFocusedTypeIndex:(double)arg1;
- (void)_initTabBar;
- (void)_scrollToMetric:(unsigned long long)arg1 animated:(_Bool)arg2;
- (void)didSelectMetric:(unsigned long long)arg1;
- (unsigned long long)focusedMetric;
- (void)viewDidAppear;
- (void)loadMetricTypes:(id)arg1 summaries:(id)arg2;
- (void)loadView;
- (void)cleanup;
- (id)initWithParentViewController:(id)arg1 focusedMetricType:(unsigned long long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

