//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface SCSnapLoadingConfiguration : NSObject
{
}

+ (unsigned long long)batchSizeToAutoLoadSnapStack;
+ (unsigned long long)initialBatchSizeToLoadSnapStack;
+ (unsigned long long)maxNumberOfSnapStacksToAutoLoad;
+ (unsigned long long)numberOfSnapStacksToAutoLoad;
+ (unsigned long long)initialNumberOfSnapStacksToLoad;

@end

