//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@interface SCStickerPickerStyle : NSObject
{
}

+ (id)blurEffectForSubIconsWithRadius:(double)arg1;
+ (id)stickerImageLoadingViewColor:(unsigned long long)arg1;
+ (id)linkingPageSubTextColor:(unsigned long long)arg1;
+ (id)linkingPageTextColor:(unsigned long long)arg1;
+ (id)scrollbarGrabberColor:(unsigned long long)arg1;
+ (id)scrollbarStickColor:(unsigned long long)arg1;
+ (double)subToolbarHeightForSourceType:(unsigned long long)arg1;
+ (double)toolbarHeightForSourceType:(unsigned long long)arg1 bottomInset:(double)arg2;
+ (id)blurEffectV2ForSourceType:(unsigned long long)arg1;
+ (id)blurEffectV1ForSourceType:(unsigned long long)arg1;
+ (id)blurEffectForSourceType:(unsigned long long)arg1;
+ (id)sectionHeaderTextColorForSourceType:(unsigned long long)arg1;
+ (id)toolbarFillViewColorV1ForSourceType:(unsigned long long)arg1;
+ (id)toolbarFillViewColorForSourceType:(unsigned long long)arg1;
+ (id)heavyBlurOverlayColorV2ForSourceType:(unsigned long long)arg1;
+ (id)heavyBlurOverlayColorV1ForSourceType:(unsigned long long)arg1;
+ (id)heavyBlurOverlayColorForSourceType:(unsigned long long)arg1;
+ (id)blurOverlayColorV1ForSourceType:(unsigned long long)arg1;
+ (id)blurOverlayColorForSourceType:(unsigned long long)arg1;

@end

