//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class FriendStories, SCStoryPresenter_DEPRECATED, Story;

@protocol SCStoryPresenterDelegate <NSObject>
- (void)storyPresenter:(SCStoryPresenter_DEPRECATED *)arg1 didFinishViewingFriendStories:(FriendStories *)arg2 firstStoryDisplayed:(Story *)arg3 isReplayMode:(_Bool)arg4 becameFullyViewed:(_Bool)arg5;
- (void)storyPresenter:(SCStoryPresenter_DEPRECATED *)arg1 didBeginPlayingFriendStories:(FriendStories *)arg2;
- (void)storyPresenterWillBeginPlayingStory:(SCStoryPresenter_DEPRECATED *)arg1 friendStories:(FriendStories *)arg2 viewLocation:(long long)arg3;
- (void)storyPresenterDidFinishDismissingStory:(SCStoryPresenter_DEPRECATED *)arg1;
- (void)storyPresenterDidCancelDismissingStory:(SCStoryPresenter_DEPRECATED *)arg1;
- (void)storyPresenterWillBeginAnimatingToDismissStory:(SCStoryPresenter_DEPRECATED *)arg1;
- (void)storyPresenterDidFinishPresentingStory:(SCStoryPresenter_DEPRECATED *)arg1;
- (void)storyPresenterWillBeginPresentingStory:(SCStoryPresenter_DEPRECATED *)arg1;
- (void)storyPresenter:(SCStoryPresenter_DEPRECATED *)arg1 beginDismissFriendStories:(FriendStories *)arg2 previousFriendStories:(FriendStories *)arg3;
- (void)storyPresenter:(SCStoryPresenter_DEPRECATED *)arg1 didDismissFriendStories:(FriendStories *)arg2 becameFullyViewed:(_Bool)arg3 succeededToPresent:(_Bool)arg4 viewingType:(long long)arg5;
@end

