//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "NSCopying-Protocol.h"

@class SOJUStoriesResponse;

@interface SCStoriesFriendStoriesUpdateRequest : NSObject <NSCopying>
{
    unsigned long long _subtype;
    _Bool _fetchBQStories_forceNonDelta;
    SOJUStoriesResponse *_handleSOJUStoriesResponse_response;
}

+ (id)handleSOJUStoriesResponseWithResponse:(id)arg1;
+ (id)fetchBQStoriesWithForceNonDelta:(_Bool)arg1;
- (void).cxx_destruct;
- (void)matchFetchBQStories:(CDUnknownBlockType)arg1 handleSOJUStoriesResponse:(CDUnknownBlockType)arg2;
- (_Bool)isEqual:(id)arg1;
- (id)internalInit;
- (unsigned long long)hash;
- (id)description;
- (id)copyWithZone:(struct _NSZone *)arg1;

@end

