//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "SCStreamingProxiedURLProviding-Protocol.h"

@class NSString, SCWebProxy;
@protocol SCWebProxyRequestHandling;

@interface SCStreamingProxiedURLProvider : NSObject <SCStreamingProxiedURLProviding>
{
    SCWebProxy *_webProxy;
}

- (void).cxx_destruct;
- (id)proxiedStreamingURLForMediaURL:(id)arg1 encryptionInfo:(id)arg2 trackingInfo:(id)arg3 requestContexts:(id)arg4;
@property(readonly, nonatomic) __weak id <SCWebProxyRequestHandling> requestHandler;
- (id)initWithRequestHandler:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

