//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSArray, NSIndexSet, SCFuture;

@interface SCStickerCategory : NSObject
{
    NSArray *_stickers;
    NSArray *_sectionTitles;
    NSArray *_sectionThumbnailUrls;
    NSArray *_sectionUnlockableIds;
    NSIndexSet *_horizontalScrollSections;
    _Bool _isCustomStickerPage;
    _Bool _isUnlockedStickerPage;
    _Bool _hasGiphySection;
    _Bool _enabledAutoCustomSticker;
    _Bool _shouldDisplayScrollbar;
    _Bool _shouldDisplaySectionHeader;
    _Bool _isEmojiCategory;
    SCFuture *_normalIconImage;
    SCFuture *_selectedIconImage;
    long long _preferredPortraitColumnCount;
    long long _preferredLandscapeColumnCount;
    long long _preferredPortraitColumnCountV2;
    long long _preferredLandscapeColumnCountV2;
}

@property(readonly, nonatomic) _Bool isEmojiCategory; // @synthesize isEmojiCategory=_isEmojiCategory;
@property(readonly, nonatomic) _Bool shouldDisplaySectionHeader; // @synthesize shouldDisplaySectionHeader=_shouldDisplaySectionHeader;
@property(readonly, nonatomic) _Bool shouldDisplayScrollbar; // @synthesize shouldDisplayScrollbar=_shouldDisplayScrollbar;
@property(readonly, nonatomic) long long preferredLandscapeColumnCountV2; // @synthesize preferredLandscapeColumnCountV2=_preferredLandscapeColumnCountV2;
@property(readonly, nonatomic) long long preferredPortraitColumnCountV2; // @synthesize preferredPortraitColumnCountV2=_preferredPortraitColumnCountV2;
@property(readonly, nonatomic) long long preferredLandscapeColumnCount; // @synthesize preferredLandscapeColumnCount=_preferredLandscapeColumnCount;
@property(readonly, nonatomic) long long preferredPortraitColumnCount; // @synthesize preferredPortraitColumnCount=_preferredPortraitColumnCount;
@property(readonly, nonatomic) SCFuture *selectedIconImage; // @synthesize selectedIconImage=_selectedIconImage;
@property(readonly, nonatomic) SCFuture *normalIconImage; // @synthesize normalIconImage=_normalIconImage;
- (void).cxx_destruct;
- (id)_categoryIconName:(id)arg1 target:(long long)arg2 highlighted:(_Bool)arg3 version:(long long)arg4;
- (void)removeAnimatedStickers;
- (id)thumbnailUrlForSection:(long long)arg1;
- (_Bool)removeSection:(long long)arg1;
- (_Bool)removeGiphySection:(long long)arg1;
- (void)addStickersToSection:(long long)arg1 stickers:(id)arg2;
- (void)reloadSectionStickers:(long long)arg1 stickers:(id)arg2;
- (unsigned long long)sectionIndexForName:(id)arg1;
- (_Bool)isGiphySection:(long long)arg1;
- (_Bool)isUnlockedStickerPage;
- (_Bool)isCustomStickerPage;
- (_Bool)isEmptyState:(long long)arg1;
- (_Bool)shouldHorizontalScrollAtSection:(long long)arg1;
- (id)firstStickerForSection:(long long)arg1;
- (id)unlockableIdForSection:(long long)arg1;
- (id)stickerPackIdForSection:(long long)arg1;
- (id)titleForSection:(long long)arg1;
- (id)_stickerSectionFromChatStickerPackage:(id)arg1;
- (void)addStickerToSection:(long long)arg1 sticker:(id)arg2;
- (void)deleteStickerFromSection:(long long)arg1 sticker:(id)arg2;
- (id)stickersForSection:(long long)arg1;
@property(readonly, nonatomic) long long sectionCount;
- (void)_initStickerSections:(id)arg1 willMergeSection:(_Bool)arg2;
- (id)initWithBitmojiStickerPackages:(id)arg1 target:(long long)arg2 indexForCategoryIcon:(unsigned long long)arg3 willMergeSection:(_Bool)arg4 chatStickerManager:(id)arg5;
- (id)initInSeparateSectionsWithSOJUStickers:(id)arg1 normalIconImage:(id)arg2 selectedIconImage:(id)arg3 shouldDisplaySectionHeader:(_Bool)arg4 preferredPortraitColumnCount:(unsigned long long)arg5 preferredLandscapeColumnCount:(unsigned long long)arg6;
- (id)initInSeparateSectionsWithSOJUStickers:(id)arg1 normalIconImage:(id)arg2 selectedIconImage:(id)arg3 includeGiphySection:(_Bool)arg4;
- (id)initWithSOJUStickers:(id)arg1 normalIconImage:(id)arg2 selectedIconImage:(id)arg3;
- (id)initWithStickers:(id)arg1 captionRecommendations:(id)arg2 visualRecommendations:(id)arg3 relatedRecommendations:(id)arg4 featured:(id)arg5 normalIconImage:(id)arg6 selectedIconImage:(id)arg7 containGiphyRecommendations:(_Bool)arg8;
- (id)initWithUnlockedStickerPackages:(id)arg1 normalIconImage:(id)arg2 selectedIconImage:(id)arg3;
- (id)initWithRecentStickers:(id)arg1 normalIconImage:(id)arg2 selectedIconImage:(id)arg3;
- (id)initWithGeofilterStickers:(id)arg1 normalIconImage:(id)arg2 selectedIconImage:(id)arg3 userSession:(id)arg4;
- (id)initWithHomeTabStickers:(id)arg1 normalIconImage:(id)arg2 selectedIconImage:(id)arg3;
- (id)initWithAutoCustomStickers:(id)arg1 savedCustomStickers:(id)arg2 normalIconImage:(id)arg3 selectedIconImage:(id)arg4;
- (id)initWithFaceCutStickers:(id)arg1 normalIconImage:(id)arg2 selectedIconImage:(id)arg3;
- (id)initWithCustomStickers:(id)arg1 normalIconImage:(id)arg2 selectedIconImage:(id)arg3;
- (id)initWithStickers:(id)arg1 normalIconImage:(id)arg2 selectedIconImage:(id)arg3;
- (id)initWithChatStickerPackages:(id)arg1 target:(long long)arg2 indexForCategoryIcon:(unsigned long long)arg3 willMergeSection:(_Bool)arg4 chatStickerManager:(id)arg5;
- (id)initWithChatStickerPackages:(id)arg1 target:(long long)arg2 chatStickerManager:(id)arg3;
- (id)initWithEmojiCateogries:(id)arg1;

@end

