//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "SCTileDataSourceListener-Protocol.h"
#import "SCTimeProfilable-Protocol.h"

@class NSString;

@interface SCSubscriptionManager : NSObject <SCTimeProfilable, SCTileDataSourceListener>
{
}

+ (int)context;
+ (id)shared;
- (void)unsubscribeFromContent:(id)arg1 successCompletion:(CDUnknownBlockType)arg2 shouldDedupe:(_Bool)arg3 shouldSendNetworkRequest:(_Bool)arg4;
- (void)subscribeToContent:(id)arg1 successCompletion:(CDUnknownBlockType)arg2 shouldDedupe:(_Bool)arg3 shouldSendNetworkRequest:(_Bool)arg4;
- (void)tileDataSourceDidChangeTileCover:(id)arg1;
- (void)tileDataSourceDidBecomeFullyViewed:(id)arg1;
- (id)_parameterJsonForContent:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

