//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GPBMessage.h"

@class NSMutableDictionary, SCSUPEngagementStats;

@interface SCSUPPublicUserEngagement : GPBMessage
{
}

+ (id)descriptor;

// Remaining properties
@property(retain, nonatomic) SCSUPEngagementStats *aggregatedFollowStats; // @dynamic aggregatedFollowStats;
@property(retain, nonatomic) SCSUPEngagementStats *aggregatedNoFollowStats; // @dynamic aggregatedNoFollowStats;
@property(nonatomic) _Bool hasAggregatedFollowStats; // @dynamic hasAggregatedFollowStats;
@property(nonatomic) _Bool hasAggregatedNoFollowStats; // @dynamic hasAggregatedNoFollowStats;
@property(retain, nonatomic) NSMutableDictionary *topPublicUserStats; // @dynamic topPublicUserStats;
@property(readonly, nonatomic) unsigned long long topPublicUserStats_Count; // @dynamic topPublicUserStats_Count;

@end

