//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class SCMainThreadIdleTaskExecutor, SCQueuePerformer, SCTaskManagerTrigger;

@interface SCTaskManager : NSObject
{
    SCQueuePerformer *_highPriorityConcurrentPerformer;
    SCQueuePerformer *_defaultPriorityConcurrentPerformer;
    SCQueuePerformer *_lowPriorityConcurrentPerformer;
    SCQueuePerformer *_priorityBackgroundConcurrentPerformer;
    SCMainThreadIdleTaskExecutor *_idleTaskExecutor;
    SCTaskManagerTrigger *_trigger;
}

+ (id)sharedManager;
@property(readonly, nonatomic) SCTaskManagerTrigger *trigger; // @synthesize trigger=_trigger;
- (void).cxx_destruct;
- (void)markAppEnterBackground;
- (void)markAppStartUpComplete;
- (id)_manageTask:(id)arg1;
- (id)addTaskToRunWhenAppIdle:(const char *)arg1 performer:(id)arg2 block:(CDUnknownBlockType)arg3;
- (id)addTaskToRunWhenAppIdle:(const char *)arg1 callbackQueue:(unsigned long long)arg2 block:(CDUnknownBlockType)arg3;
- (id)init;

@end

