//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCCameraBackgroundViewController.h"

#import "MFMailComposeViewControllerDelegate-Protocol.h"
#import "SCHeaderDelegate-Protocol.h"
#import "SCTermsOfUseAcceptanceDelegate-Protocol.h"
#import "TTTAttributedLabelDelegate-Protocol.h"

@class NSString, NSTimer, SCTermsOfUseView, SCUserSession;
@protocol SCTermsOfUseUserInteractionDelegate;

@interface SCTermsOfUseViewController : SCCameraBackgroundViewController <SCHeaderDelegate, SCTermsOfUseAcceptanceDelegate, MFMailComposeViewControllerDelegate, TTTAttributedLabelDelegate>
{
    SCUserSession *_userSession;
    SCTermsOfUseView *_termsOfUseView;
    NSTimer *_flashTimer;
    long long _flashCount;
    id <SCTermsOfUseUserInteractionDelegate> _delegate;
}

@property(nonatomic) __weak id <SCTermsOfUseUserInteractionDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)presentWebViewWithUrl:(id)arg1;
- (void)attributedLabel:(id)arg1 didSelectLinkWithURL:(id)arg2;
- (void)acceptButtonPressed;
- (void)rightButtonPressed;
- (double)preferredRightButtonWidth;
- (void)stopFlashScrollTimer;
- (void)startFlashScrollTimer;
- (void)flashScrollIndicators;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)loadView;
- (id)initWithUserSession:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

