//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class SCTV3IncomingCallPrompt, SCTV3MediaView;

@protocol SCTV3IncomingCallPromptDelegate <NSObject>
- (void)incomingCallPrompt:(SCTV3IncomingCallPrompt *)arg1 didSelectResponse:(unsigned long long)arg2;
- (SCTV3MediaView *)localMediaViewInIncomingCallPrompt:(SCTV3IncomingCallPrompt *)arg1;
@end

