//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "SCAppNotificationProcessor-Protocol.h"
#import "SCCallManagerListener-Protocol.h"
#import "SCTV3HeadlessCallServicesDelegate-Protocol.h"

@class NSString, SCCallManager;

@interface SCTV3HeadlessSessionController : NSObject <SCAppNotificationProcessor, SCTV3HeadlessCallServicesDelegate, SCCallManagerListener>
{
    SCCallManager *_callManager;
}

+ (id)sharedInstance;
@property(retain, nonatomic) SCCallManager *callManager; // @synthesize callManager=_callManager;
- (void).cxx_destruct;
- (id)_stringFromPushType:(long long)arg1;
- (_Bool)_shouldHaveValidCredentials:(id)arg1;
- (_Bool)_validNotificationCredentials:(id)arg1;
- (_Bool)_isTalkV3ReplacementNotification:(id)arg1;
- (_Bool)_isTalkV3Notification:(id)arg1;
- (id)_sessionForConvoId:(id)arg1;
- (long long)_handleReplacementNotification:(id)arg1 convoId:(id)arg2;
- (long long)_handleNotification:(id)arg1 convoId:(id)arg2;
- (void)callDidEndForHeadlessCallServices:(id)arg1;
- (void)headlessCallServices:(id)arg1 didUpdateCallMedia:(unsigned long long)arg2;
- (void)didEndCallWithConversationID:(id)arg1;
- (void)didAnswerCallWithConversationID:(id)arg1;
- (void)processNotification:(id)arg1;
- (void)onNotificationDeferred:(id)arg1;
- (long long)shouldFilterNotification:(id)arg1;
- (void)handleInAppNotificationDismissed:(id)arg1;
- (id)notificationProcessor;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

