//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "SCLoginRegisterUserActionDelegate-Protocol.h"
#import "SCLoginWorkflowDelegate-Protocol.h"
#import "SCUnauthenticatedOAuth2Delegate-Protocol.h"

@class NSString;
@protocol SCUnauthenticatedPageRouter;

@interface SCUnauthenticatedWorkflow : NSObject <SCLoginRegisterUserActionDelegate, SCLoginWorkflowDelegate, SCUnauthenticatedOAuth2Delegate>
{
    id <SCUnauthenticatedPageRouter> _unauthenticatedPageRouter;
    _Bool _didStartLogin;
}

- (void).cxx_destruct;
- (void)userOpenedOAuth2DeepLink;
- (void)didDismissLogin;
- (void)didTapLoginButton;
- (void)beginWorkflow;
- (id)initWithUnauthenticatedPageRouter:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

