//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIViewController.h>

#import "MGLMapViewDelegate-Protocol.h"
#import "SCHeaderDataSource-Protocol.h"
#import "SCHeaderDelegate-Protocol.h"

@class NSString, SCHeader, SCMapView, SCUserSession, UIButton, UIImageView;
@protocol SCVenueFeedbackMapSelectionDelegate;

@interface SCVenueFeedbackMapViewController : UIViewController <SCHeaderDataSource, SCHeaderDelegate, MGLMapViewDelegate>
{
    SCHeader *_header;
    SCMapView *_mapView;
    UIImageView *_mapPin;
    struct CLLocationCoordinate2D _coordinate;
    UIButton *_doneButton;
    SCUserSession *_session;
    id <SCVenueFeedbackMapSelectionDelegate> _delegate;
}

@property(nonatomic) __weak id <SCVenueFeedbackMapSelectionDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_tappedDone;
- (id)_screenshotToBase64String;
- (void)_dismiss;
- (id)imageForRightButtonInState:(unsigned long long)arg1;
- (id)imageForLeftButtonInState:(unsigned long long)arg1;
- (id)titleForHeader:(id)arg1;
- (id)textColorForHeader:(id)arg1;
- (id)backgroundColorForHeader;
- (void)leftButtonPressed;
- (void)viewDidLoad;
- (id)initWithUserSession:(id)arg1 latitude:(double)arg2 longitude:(double)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

