//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SCMediaTranscodingLatencyReportItem.h"

@class NSMutableDictionary;

@interface SCVideoTranscodingLatencyReportItem : SCMediaTranscodingLatencyReportItem
{
    _Bool _isWithGPUCPUCommands;
    _Bool _isReversed;
    double _beginSegmentTime;
    unsigned long long _subitemCount;
    NSMutableDictionary *_subitems;
}

@property(retain, nonatomic) NSMutableDictionary *subitems; // @synthesize subitems=_subitems;
@property(nonatomic) unsigned long long subitemCount; // @synthesize subitemCount=_subitemCount;
@property(nonatomic) _Bool isReversed; // @synthesize isReversed=_isReversed;
@property(nonatomic) _Bool isWithGPUCPUCommands; // @synthesize isWithGPUCPUCommands=_isWithGPUCPUCommands;
@property(nonatomic) double beginSegmentTime; // @synthesize beginSegmentTime=_beginSegmentTime;
- (void).cxx_destruct;
- (id)metrics;
- (_Bool)isReadyToUpload;
- (id)initWithItemID:(id)arg1 isAudioEnabled:(_Bool)arg2;

@end

