//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSArray, NSNumber;

@interface SOJUAdSourcesConfigBuilder : NSObject
{
    NSArray *_adSources;
    NSNumber *_useV2;
    NSArray *_shutOffRules;
    NSNumber *_useAppInstallV2;
}

+ (id)withJUAdSourcesConfig:(id)arg1;
- (void).cxx_destruct;
- (id)setUseAppInstallV2:(id)arg1;
- (id)setShutOffRules:(id)arg1;
- (id)setUseV2:(id)arg1;
- (id)setAdSources:(id)arg1;
- (id)build;
- (id)setUseAppInstallV2Value:(_Bool)arg1;
- (id)setUseV2Value:(_Bool)arg1;

@end

