//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "SOJUBroadcastGroupApiCreatePublicationRequest-Protocol.h"

@class NSArray, NSString, SOJUBroadcastGroupModelLocation;

@interface SOJUBroadcastGroupApiCreatePublicationRequest : NSObject <SOJUBroadcastGroupApiCreatePublicationRequest>
{
    NSString *_idValue;
    NSString *_displayName;
    NSString *_privacy;
    NSArray *_posterUserIds;
    NSArray *_selectedAudienceUserIds;
    SOJUBroadcastGroupModelLocation *_geoFenceCenter;
}

+ (unsigned long long *)fasterCodingKeys;
+ (unsigned long long)fasterCodingVersion;
+ (_Bool)canInitFromProto;
@property(readonly, copy, nonatomic) SOJUBroadcastGroupModelLocation *geoFenceCenter; // @synthesize geoFenceCenter=_geoFenceCenter;
@property(readonly, copy, nonatomic) NSArray *selectedAudienceUserIds; // @synthesize selectedAudienceUserIds=_selectedAudienceUserIds;
@property(readonly, copy, nonatomic) NSArray *posterUserIds; // @synthesize posterUserIds=_posterUserIds;
@property(readonly, copy, nonatomic) NSString *privacy; // @synthesize privacy=_privacy;
@property(readonly, copy, nonatomic) NSString *displayName; // @synthesize displayName=_displayName;
@property(readonly, copy, nonatomic) NSString *idValue; // @synthesize idValue=_idValue;
- (void).cxx_destruct;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
- (_Bool)isEqual:(id)arg1;
- (void)setObject:(id)arg1 forUInt64Key:(unsigned long long)arg2;
- (void)decodeWithFasterDecoder:(id)arg1;
- (void)encodeWithFasterCoder:(id)arg1;
- (_Bool)preferFasterCoding;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithIdValue:(id)arg1 displayName:(id)arg2 privacy:(id)arg3 posterUserIds:(id)arg4 selectedAudienceUserIds:(id)arg5 geoFenceCenter:(id)arg6;
- (id)toJson;
- (id)toDictionary;
- (id)initWithJSONDictionary:(id)arg1;
- (long long)privacyEnum;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

