//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

@class NSNumber, NSString;

@interface SOJUGalleryRatingStickerStyleBuilder : NSObject
{
    NSNumber *_rating;
    NSString *_styleId;
}

+ (id)withJUGalleryRatingStickerStyle:(id)arg1;
- (void).cxx_destruct;
- (id)setStyleId:(id)arg1;
- (id)setRating:(id)arg1;
- (id)build;
- (id)setStyleIdEnum:(long long)arg1;
- (id)setRatingValue:(int)arg1;

@end

