//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "SOJULensData-Protocol.h"

@class NSArray, NSDictionary, NSNumber, NSString;

@interface SOJULensData : NSObject <SOJULensData>
{
    NSString *_code;
    NSString *_configPath;
    NSString *_iconLink;
    NSString *_lensLink;
    NSString *_hintId;
    NSDictionary *_hintTranslations;
    NSString *_signature;
    NSNumber *_demoStartDate;
    NSString *_bitmojiComicId;
    NSArray *_assetManifest;
    NSNumber *_hideUntilAssetsDownloaded;
    NSNumber *_isThirdParty;
    NSNumber *_isStudioPreview;
    NSString *_lensCreatorUsername;
    NSString *_lensAttributionName;
    NSString *_activationCamera;
    NSNumber *_isDisabledForVideoChat;
    NSString *_unlockCompanionBackReferenceId;
    NSString *_name;
    NSString *_filterImageLink;
    NSArray *_lensDescriptors;
    NSString *_snappableReplyType;
    NSString *_lensCreatorUserId;
}

+ (unsigned long long *)fasterCodingKeys;
+ (unsigned long long)fasterCodingVersion;
+ (_Bool)canInitFromProto;
@property(readonly, copy, nonatomic) NSString *lensCreatorUserId; // @synthesize lensCreatorUserId=_lensCreatorUserId;
@property(readonly, copy, nonatomic) NSString *snappableReplyType; // @synthesize snappableReplyType=_snappableReplyType;
@property(readonly, copy, nonatomic) NSArray *lensDescriptors; // @synthesize lensDescriptors=_lensDescriptors;
@property(readonly, copy, nonatomic) NSString *filterImageLink; // @synthesize filterImageLink=_filterImageLink;
@property(readonly, copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(readonly, copy, nonatomic) NSString *unlockCompanionBackReferenceId; // @synthesize unlockCompanionBackReferenceId=_unlockCompanionBackReferenceId;
@property(readonly, copy, nonatomic) NSNumber *isDisabledForVideoChat; // @synthesize isDisabledForVideoChat=_isDisabledForVideoChat;
@property(readonly, copy, nonatomic) NSString *activationCamera; // @synthesize activationCamera=_activationCamera;
@property(readonly, copy, nonatomic) NSString *lensAttributionName; // @synthesize lensAttributionName=_lensAttributionName;
@property(readonly, copy, nonatomic) NSString *lensCreatorUsername; // @synthesize lensCreatorUsername=_lensCreatorUsername;
@property(readonly, copy, nonatomic) NSNumber *isStudioPreview; // @synthesize isStudioPreview=_isStudioPreview;
@property(readonly, copy, nonatomic) NSNumber *isThirdParty; // @synthesize isThirdParty=_isThirdParty;
@property(readonly, copy, nonatomic) NSNumber *hideUntilAssetsDownloaded; // @synthesize hideUntilAssetsDownloaded=_hideUntilAssetsDownloaded;
@property(readonly, copy, nonatomic) NSArray *assetManifest; // @synthesize assetManifest=_assetManifest;
@property(readonly, copy, nonatomic) NSString *bitmojiComicId; // @synthesize bitmojiComicId=_bitmojiComicId;
@property(readonly, copy, nonatomic) NSNumber *demoStartDate; // @synthesize demoStartDate=_demoStartDate;
@property(readonly, copy, nonatomic) NSString *signature; // @synthesize signature=_signature;
@property(readonly, copy, nonatomic) NSDictionary *hintTranslations; // @synthesize hintTranslations=_hintTranslations;
@property(readonly, copy, nonatomic) NSString *hintId; // @synthesize hintId=_hintId;
@property(readonly, copy, nonatomic) NSString *lensLink; // @synthesize lensLink=_lensLink;
@property(readonly, copy, nonatomic) NSString *iconLink; // @synthesize iconLink=_iconLink;
@property(readonly, copy, nonatomic) NSString *configPath; // @synthesize configPath=_configPath;
@property(readonly, copy, nonatomic) NSString *code; // @synthesize code=_code;
- (void).cxx_destruct;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
- (_Bool)isEqual:(id)arg1;
- (void)setObject:(id)arg1 forUInt64Key:(unsigned long long)arg2;
- (void)decodeWithFasterDecoder:(id)arg1;
- (void)encodeWithFasterCoder:(id)arg1;
- (_Bool)preferFasterCoding;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithCode:(id)arg1 configPath:(id)arg2 iconLink:(id)arg3 lensLink:(id)arg4 hintId:(id)arg5 hintTranslations:(id)arg6 signature:(id)arg7 demoStartDate:(id)arg8 bitmojiComicId:(id)arg9 assetManifest:(id)arg10 hideUntilAssetsDownloaded:(id)arg11 isThirdParty:(id)arg12 isStudioPreview:(id)arg13 lensCreatorUsername:(id)arg14 lensAttributionName:(id)arg15 activationCamera:(id)arg16 isDisabledForVideoChat:(id)arg17 unlockCompanionBackReferenceId:(id)arg18 name:(id)arg19 filterImageLink:(id)arg20 lensDescriptors:(id)arg21 snappableReplyType:(id)arg22 lensCreatorUserId:(id)arg23;
- (id)toJson;
- (id)toDictionary;
- (id)initWithJSONDictionary:(id)arg1;
- (long long)snappableReplyTypeEnum;
- (_Bool)isDisabledForVideoChatValue;
- (long long)activationCameraEnum;
- (_Bool)isStudioPreviewValue;
- (_Bool)isThirdPartyValue;
- (_Bool)hideUntilAssetsDownloadedValue;
- (id)initWithProtoBuf:(id)arg1;
- (id)initWithProtoBinary:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

