//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "SOJUDiscoverConversationShareMediaRequest-Protocol.h"

@class NSNumber, NSString;

@interface SOJUDiscoverConversationShareMediaRequest : NSObject <SOJUDiscoverConversationShareMediaRequest>
{
    NSString *_timestamp;
    NSString *_reqToken;
    NSString *_username;
    NSString *_recipients;
    NSString *_recipientIds;
    NSString *_mediaId;
    NSString *_mediaType;
    NSString *_bodyType;
    NSNumber *_typeVersion;
    NSString *_mediaEncKey;
    NSString *_mediaEncIv;
    NSNumber *_mediaWidth;
    NSNumber *_mediaHeight;
    NSString *_seqNums;
    NSString *_mediaAttributes;
    NSNumber *_sendStartTimestamp;
}

+ (unsigned long long *)fasterCodingKeys;
+ (unsigned long long)fasterCodingVersion;
+ (_Bool)canInitFromProto;
@property(readonly, copy, nonatomic) NSNumber *sendStartTimestamp; // @synthesize sendStartTimestamp=_sendStartTimestamp;
@property(readonly, copy, nonatomic) NSString *mediaAttributes; // @synthesize mediaAttributes=_mediaAttributes;
@property(readonly, copy, nonatomic) NSString *seqNums; // @synthesize seqNums=_seqNums;
@property(readonly, copy, nonatomic) NSNumber *mediaHeight; // @synthesize mediaHeight=_mediaHeight;
@property(readonly, copy, nonatomic) NSNumber *mediaWidth; // @synthesize mediaWidth=_mediaWidth;
@property(readonly, copy, nonatomic) NSString *mediaEncIv; // @synthesize mediaEncIv=_mediaEncIv;
@property(readonly, copy, nonatomic) NSString *mediaEncKey; // @synthesize mediaEncKey=_mediaEncKey;
@property(readonly, copy, nonatomic) NSNumber *typeVersion; // @synthesize typeVersion=_typeVersion;
@property(readonly, copy, nonatomic) NSString *bodyType; // @synthesize bodyType=_bodyType;
@property(readonly, copy, nonatomic) NSString *mediaType; // @synthesize mediaType=_mediaType;
@property(readonly, copy, nonatomic) NSString *mediaId; // @synthesize mediaId=_mediaId;
@property(readonly, copy, nonatomic) NSString *recipientIds; // @synthesize recipientIds=_recipientIds;
@property(readonly, copy, nonatomic) NSString *recipients; // @synthesize recipients=_recipients;
@property(readonly, copy, nonatomic) NSString *username; // @synthesize username=_username;
@property(readonly, copy, nonatomic) NSString *reqToken; // @synthesize reqToken=_reqToken;
@property(readonly, copy, nonatomic) NSString *timestamp; // @synthesize timestamp=_timestamp;
- (void).cxx_destruct;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
- (_Bool)isEqual:(id)arg1;
- (void)setObject:(id)arg1 forUInt64Key:(unsigned long long)arg2;
- (void)decodeWithFasterDecoder:(id)arg1;
- (void)encodeWithFasterCoder:(id)arg1;
- (_Bool)preferFasterCoding;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithTimestamp:(id)arg1 reqToken:(id)arg2 username:(id)arg3 recipients:(id)arg4 recipientIds:(id)arg5 mediaId:(id)arg6 mediaType:(id)arg7 bodyType:(id)arg8 typeVersion:(id)arg9 mediaEncKey:(id)arg10 mediaEncIv:(id)arg11 mediaWidth:(id)arg12 mediaHeight:(id)arg13 seqNums:(id)arg14 mediaAttributes:(id)arg15 sendStartTimestamp:(id)arg16;
- (id)toJson;
- (id)toDictionary;
- (id)initWithJSONDictionary:(id)arg1;
- (long long)sendStartTimestampValue;
- (int)mediaHeightValue;
- (int)mediaWidthValue;
- (int)typeVersionValue;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

