//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <Foundation/NSObject.h>

#import "SOJUSnapAdsPortalStats-Protocol.h"

@class NSNumber, NSString;

@interface SOJUSnapAdsPortalStats : NSObject <SOJUSnapAdsPortalStats>
{
    NSNumber *_impressions;
    NSNumber *_quartile1;
    NSNumber *_quartile2;
    NSNumber *_quartile3;
    NSNumber *_viewCompletion;
    NSNumber *_frequency;
    NSNumber *_avgViewTimeSec;
    NSNumber *_uniques;
    NSNumber *_spend;
    NSNumber *_frequencyDecimal;
    NSNumber *_effectiveCostPerMille;
    NSNumber *_effectiveCostPerCompletedViews;
    NSNumber *_effectiveCostPerSwipes;
    NSNumber *_longformAvgViewTimeInSec;
    NSNumber *_webviewAvgViewTimeInSec;
    NSNumber *_totalInstalls;
    NSNumber *_articleAvgReadPercentage;
    NSNumber *_swipeUps;
    NSNumber *_swipeUpPercentage;
    NSNumber *_iosInstalls;
    NSNumber *_androidInstalls;
    NSNumber *_avgViewTimeInSec;
    NSNumber *_attachmentAvgViewTimeInSec;
    NSNumber *_attachmentAvgReadPercentage;
    NSNumber *_avgCreativeLengthInSec;
    NSNumber *_attachmentAvgCreativeLengthInSec;
    NSNumber *_spendDecimal;
    NSNumber *_effectiveCostPerInstall;
    NSNumber *_effectiveCostPerIosInstall;
    NSNumber *_effectiveCostPerAndroidInstall;
    NSNumber *_videoViews;
    NSNumber *_effectiveCostPerVideoView;
}

+ (unsigned long long *)fasterCodingKeys;
+ (unsigned long long)fasterCodingVersion;
+ (_Bool)canInitFromProto;
@property(readonly, copy, nonatomic) NSNumber *effectiveCostPerVideoView; // @synthesize effectiveCostPerVideoView=_effectiveCostPerVideoView;
@property(readonly, copy, nonatomic) NSNumber *videoViews; // @synthesize videoViews=_videoViews;
@property(readonly, copy, nonatomic) NSNumber *effectiveCostPerAndroidInstall; // @synthesize effectiveCostPerAndroidInstall=_effectiveCostPerAndroidInstall;
@property(readonly, copy, nonatomic) NSNumber *effectiveCostPerIosInstall; // @synthesize effectiveCostPerIosInstall=_effectiveCostPerIosInstall;
@property(readonly, copy, nonatomic) NSNumber *effectiveCostPerInstall; // @synthesize effectiveCostPerInstall=_effectiveCostPerInstall;
@property(readonly, copy, nonatomic) NSNumber *spendDecimal; // @synthesize spendDecimal=_spendDecimal;
@property(readonly, copy, nonatomic) NSNumber *attachmentAvgCreativeLengthInSec; // @synthesize attachmentAvgCreativeLengthInSec=_attachmentAvgCreativeLengthInSec;
@property(readonly, copy, nonatomic) NSNumber *avgCreativeLengthInSec; // @synthesize avgCreativeLengthInSec=_avgCreativeLengthInSec;
@property(readonly, copy, nonatomic) NSNumber *attachmentAvgReadPercentage; // @synthesize attachmentAvgReadPercentage=_attachmentAvgReadPercentage;
@property(readonly, copy, nonatomic) NSNumber *attachmentAvgViewTimeInSec; // @synthesize attachmentAvgViewTimeInSec=_attachmentAvgViewTimeInSec;
@property(readonly, copy, nonatomic) NSNumber *avgViewTimeInSec; // @synthesize avgViewTimeInSec=_avgViewTimeInSec;
@property(readonly, copy, nonatomic) NSNumber *androidInstalls; // @synthesize androidInstalls=_androidInstalls;
@property(readonly, copy, nonatomic) NSNumber *iosInstalls; // @synthesize iosInstalls=_iosInstalls;
@property(readonly, copy, nonatomic) NSNumber *swipeUpPercentage; // @synthesize swipeUpPercentage=_swipeUpPercentage;
@property(readonly, copy, nonatomic) NSNumber *swipeUps; // @synthesize swipeUps=_swipeUps;
@property(readonly, copy, nonatomic) NSNumber *articleAvgReadPercentage; // @synthesize articleAvgReadPercentage=_articleAvgReadPercentage;
@property(readonly, copy, nonatomic) NSNumber *totalInstalls; // @synthesize totalInstalls=_totalInstalls;
@property(readonly, copy, nonatomic) NSNumber *webviewAvgViewTimeInSec; // @synthesize webviewAvgViewTimeInSec=_webviewAvgViewTimeInSec;
@property(readonly, copy, nonatomic) NSNumber *longformAvgViewTimeInSec; // @synthesize longformAvgViewTimeInSec=_longformAvgViewTimeInSec;
@property(readonly, copy, nonatomic) NSNumber *effectiveCostPerSwipes; // @synthesize effectiveCostPerSwipes=_effectiveCostPerSwipes;
@property(readonly, copy, nonatomic) NSNumber *effectiveCostPerCompletedViews; // @synthesize effectiveCostPerCompletedViews=_effectiveCostPerCompletedViews;
@property(readonly, copy, nonatomic) NSNumber *effectiveCostPerMille; // @synthesize effectiveCostPerMille=_effectiveCostPerMille;
@property(readonly, copy, nonatomic) NSNumber *frequencyDecimal; // @synthesize frequencyDecimal=_frequencyDecimal;
@property(readonly, copy, nonatomic) NSNumber *spend; // @synthesize spend=_spend;
@property(readonly, copy, nonatomic) NSNumber *uniques; // @synthesize uniques=_uniques;
@property(readonly, copy, nonatomic) NSNumber *avgViewTimeSec; // @synthesize avgViewTimeSec=_avgViewTimeSec;
@property(readonly, copy, nonatomic) NSNumber *frequency; // @synthesize frequency=_frequency;
@property(readonly, copy, nonatomic) NSNumber *viewCompletion; // @synthesize viewCompletion=_viewCompletion;
@property(readonly, copy, nonatomic) NSNumber *quartile3; // @synthesize quartile3=_quartile3;
@property(readonly, copy, nonatomic) NSNumber *quartile2; // @synthesize quartile2=_quartile2;
@property(readonly, copy, nonatomic) NSNumber *quartile1; // @synthesize quartile1=_quartile1;
@property(readonly, copy, nonatomic) NSNumber *impressions; // @synthesize impressions=_impressions;
- (void).cxx_destruct;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
- (_Bool)isEqual:(id)arg1;
- (void)setObject:(id)arg1 forUInt64Key:(unsigned long long)arg2;
- (void)decodeWithFasterDecoder:(id)arg1;
- (void)encodeWithFasterCoder:(id)arg1;
- (_Bool)preferFasterCoding;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithImpressions:(id)arg1 quartile1:(id)arg2 quartile2:(id)arg3 quartile3:(id)arg4 viewCompletion:(id)arg5 frequency:(id)arg6 avgViewTimeSec:(id)arg7 uniques:(id)arg8 spend:(id)arg9 frequencyDecimal:(id)arg10 effectiveCostPerMille:(id)arg11 effectiveCostPerCompletedViews:(id)arg12 effectiveCostPerSwipes:(id)arg13 longformAvgViewTimeInSec:(id)arg14 webviewAvgViewTimeInSec:(id)arg15 totalInstalls:(id)arg16 articleAvgReadPercentage:(id)arg17 swipeUps:(id)arg18 swipeUpPercentage:(id)arg19 iosInstalls:(id)arg20 androidInstalls:(id)arg21 avgViewTimeInSec:(id)arg22 attachmentAvgViewTimeInSec:(id)arg23 attachmentAvgReadPercentage:(id)arg24 avgCreativeLengthInSec:(id)arg25 attachmentAvgCreativeLengthInSec:(id)arg26 spendDecimal:(id)arg27 effectiveCostPerInstall:(id)arg28 effectiveCostPerIosInstall:(id)arg29 effectiveCostPerAndroidInstall:(id)arg30 videoViews:(id)arg31 effectiveCostPerVideoView:(id)arg32;
- (id)toJson;
- (id)toDictionary;
- (id)initWithJSONDictionary:(id)arg1;
- (double)effectiveCostPerVideoViewValue;
- (long long)videoViewsValue;
- (double)effectiveCostPerAndroidInstallValue;
- (double)effectiveCostPerIosInstallValue;
- (double)effectiveCostPerInstallValue;
- (double)spendDecimalValue;
- (double)attachmentAvgCreativeLengthInSecValue;
- (double)avgCreativeLengthInSecValue;
- (double)attachmentAvgReadPercentageValue;
- (double)attachmentAvgViewTimeInSecValue;
- (double)avgViewTimeInSecValue;
- (long long)androidInstallsValue;
- (long long)iosInstallsValue;
- (double)swipeUpPercentageValue;
- (long long)swipeUpsValue;
- (double)articleAvgReadPercentageValue;
- (long long)totalInstallsValue;
- (double)webviewAvgViewTimeInSecValue;
- (double)longformAvgViewTimeInSecValue;
- (double)effectiveCostPerSwipesValue;
- (double)effectiveCostPerCompletedViewsValue;
- (double)effectiveCostPerMilleValue;
- (double)frequencyDecimalValue;
- (long long)spendValue;
- (long long)uniquesValue;
- (long long)avgViewTimeSecValue;
- (long long)frequencyValue;
- (long long)viewCompletionValue;
- (long long)quartile3Value;
- (long long)quartile2Value;
- (long long)quartile1Value;
- (long long)impressionsValue;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) Class superclass;

@end

